acts-project/acts

.labels.yml
.policy.yml

Adds config for policybot, which will enforce approval by review, and a bot checking correct labeling.

Add config for new bots

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/coverage.yml

Previously, the coverage job only ran on PRs. This prevents codecov from showing coverage diffs, since there is not base branch

Run coverage job on master and PR to master

---

Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.ipp
Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFinderTests.cpp

Adds a unit test for user-defined track types for the AMVF and fixed one bug that appeared while testing it.

Add AMVF unit test for user-defined track type

---

Core/include/Acts/Propagator/AtlasStepper.hpp
Core/include/Acts/Propagator/EigenStepper.ipp

Some time ago, Andi studied the AtlasStepper and EigenStepper and found that they did not perform the same number of steps for a given propagation job.
As it turns out, the reason for this is that the AtlasStepper used an incorrect expression of the step error estimate. In the ATL-SOFT-PUB-2009-001 terminology that is used by the EigenStepper, the error estimate that was computed by the AtlasStepper was `h * | k1 - k2 - k3 + k4 |` when it actually should have been `h^2 * | k1 - k2 - k3 + k4 |`.
This PR fixes that along with a few more minor problems of the AtlasStepper and EigenStepper:
- The AtlasStepper tolerance used to be hardcoded. It now correctly honors the tolerance set in the propagation options.
- After performing a propagation step, the AtlasStepper would not save it back into …

Miscellaneous AtlasStepper and EigenStepper fixes, AtlasStepper docs

---

Core/include/Acts/Geometry/TrapezoidVolumeBounds.hpp
Core/include/Acts/Visualization/GeometryVisualization.hpp
Core/include/Acts/Visualization/ObjVisualization.hpp
Core/include/Acts/Visualization/detail/ObjVisualization.ipp
Core/src/Geometry/TrapezoidVolumeBounds.cpp
Tests/UnitTests/Core/Visualization/CMakeLists.txt
Tests/UnitTests/Core/Visualization/VolumeVisualizationBase.hpp
Tests/UnitTests/Core/Visualization/VolumeVisualizationTests.cpp

Second part of the visualisation package:
- visualizes volumes
Fixes also a bug in `TrapezoidVolumeBounds` which became visible.
Needs #84 to be merged first.

Visualization geometry

---

Core/include/Acts/Vertexing/GaussianTrackDensity.hpp
Core/include/Acts/Vertexing/TrackDensity.hpp
Core/include/Acts/Vertexing/TrackDensityVertexFinder.ipp
Core/src/Vertexing/TrackDensity.cpp
Tests/UnitTests/Core/Vertexing/AMVFTestData.ipp

There was a lot of unnecessary stuff going on in the gaussian track density vertex seed finder, that could be cleaned up. The physics performance has not changed, giving identical results with better CPU performance. 
Closes #97 .

Gaussian vertex seedfinder cleanup and performance updates

---

.github/workflows/build.yml
.github/workflows/coverage.yml

Relevant documentation : https://cmake.org/cmake/help/v3.1/manual/ctest.1.html .
I think a global env flag is reasonable, since we want all ctest jobs to do this and the env variable name is unambiguous enough that there is no risk of perturbating anything else.

Have CTest display test output if a test fails

---

.github/workflows/builds.yml

This (temporarily) disables building the examples and the DD4hep- and TGeo plugin. This sidesteps the build issue with the additional HEP-specific dependencies (ROOT, Geant4, DD4hep, ...).

Only build Core+Tests in the macOS CI build

---

Core/include/Acts/Propagator/EigenStepper.ipp

This PR will fix the stepping failure by replacing the return statement with its older form, `return (error_estimate <= state.options.tolerance);` as @HadrienG2  suggested in issue #142.

Fix the tryRungeKuttaStepper

---

Core/include/Acts/Fitter/KalmanFitter.hpp
Core/include/Acts/TrackFinder/CombinatorialKalmanFilter.hpp
Examples/Algorithms/GeneratorsPythia8/ACTFW/Options/Pythia8Options.cpp
Examples/Scripts/KF_timing.py
Examples/Scripts/KF_timing.sh

- Fix bug in CKF: before adding the track state, the last tip should be removed from the active tips. But when creating multiple states on ONE surface, the update of active tips should be done only ONCE so that states have the same previous state. In the current master branch, each call to `addSourcelinkState` will remove the last tip, which is not correct.
- Fix a bug in Pythia8 option: include the `pileup` generators as well instead of including the `hard` configurations twice.
- Clean the KF smoothing
- Add script for KF timing test (To produce plot as below)

Fix bug in CKF and add script for KF timing test

---

Examples/Run/Fatras/AlignedFatrasExample.cpp
Examples/Run/Fatras/PayloadFatrasExample.cpp

Some Fatras examples pass in a null `shared_ptr` in a place where a valid detector pointer is expected. They shouldn't do that.

Fix fatras example nullptrs

---

Core/include/Acts/Propagator/detail/PointwiseMaterialInteraction.hpp

Some elements in the covariance matrix are modified due to point-wise material interactions. The modification itself depends on the navigation direction. However the direction was not passed to the corresponding function. This PR fixes the behavior.

Fix covariance matrix modifications in point-wise material interactions

---

Examples/Framework/include/ACTFW/EventData/TruthFitTrack.hpp
Examples/Framework/src/Validation/ProtoTrackClassification.cpp

This PR is splitted from #162  and will fix the bug to sort number of hits to identify majority particle.

Fix the bug to identify majority particle

---

Core/include/Acts/Fitter/KalmanFitter.hpp
Core/include/Acts/TrackFinder/CombinatorialKalmanFilter.hpp

This PR fixes a problem in KF/CKF:
- The method `reverse`/`reset` will reinitialize the navigation status in KF/CKF when needed. But the navigation will skip targeting for extra layers (because the `navLayers` are empty) in the reinitialized starting volume if there is navigation surface found in the reinitialized starting layer. This is temporarily fixed by resetting the navigation stage to `layerTarget` after the starting layer has been processed. In the future, all of the reinitialization should be done by the navigator.

Fix KF/CKF navigation reinitialization

---

Core/include/Acts/Geometry/HierarchicalGeometryContainer.hpp
Tests/UnitTests/Core/Geometry/HierarchicalGeometryContainerTests.cpp

Adds index-based access methods `.idAt(...)` and `.valueAt(...)`. These are needed to create a generic reader/writer infrastructure for this container.
Updates the documentation of the container to better describe the interface.

Add index-based access to HierarchicalGeometryContainer

---

Core/include/Acts/TrackFinder/CKFSourceLinkSelector.hpp
Tests/UnitTests/Core/TrackFinder/CombinatorialKalmanFilterTests.cpp

This PR simplify the CKF source link selection by using the hierarchical geometry container for the selection criteria.

Use HierarchicalGeometryContainer to simplfiy CKF source link selection

---

.github/workflows/builds.yml

... for now. DD4hep should build again, and hopefully we're now more robust since the dependencies now include fixed version builds of 
- boost
- tbb
- xercesc
- heppdt
- pythia8
- root
- geant4
- hepmc3
- dd4hep
These dependencies are build automatically at https://github.com/acts-project/ci-dependencies/, the master branch deploys to https://acts.web.cern.ch/ACTS/ci/macOS/, the commit hash to pull is hard coded in the CI in this repo.

Fix the macOS CI build

---

.github/workflows/coverage.yml

This is an attempt at keeping the coverage job disk usage below the 14GB limit. It sets `-g1 and -gz` which compresses the debug info (thanks @HadrienG2)

Reduce size of debug symbols in coverage job

---

Tests/CommonHelpers/Acts/Tests/CommonHelpers/BenchmarkTools.hpp
Tests/UnitTests/Benchmarks/BenchmarkTools.cpp

So, I recently opened yet another stats book in the hope of finally becoming a little less miserably bad at statistical analysis, and that led me to notice a couple of new issues with the stats computed by `BenchmarkTools`.
Therefore, this PR...
- Fixes the invalid definition of standard error on median run time
- Clarifies mathematical hypotheses of the underlying statistical analysis (FWIW, I know from manual data inspection that some of them are not well verified by some of our microbenchmarks, and have plans to try to improve upon this in the future...)
- Recommends having many iterations per run (we do rely on the hypothesis of a normal run time distribution in quite a few places)
- Fixes invalid error bars (need a 1.96 factor wrt standard error in order to use the de factor standard …

Clean up BenchmarkTool statistics

---

Core/include/Acts/Fitter/GainMatrixSmoother.hpp

Since the jacobian stored in a track state is between the previous state and this state (instead of between this state and the following state), when calculating the KF smoothing gain matrix for state `k-1`, the jacobian used in the formalism should be that stored in state `k`.

Fix the smoothing gain matrix

---

Core/include/Acts/EventData/MultiTrajectoryHelpers.hpp
Examples/Algorithms/Fitting/src/FittingAlgorithm.cpp
Examples/Framework/CMakeLists.txt
Examples/Framework/include/ACTFW/EventData/SimMultiTrajectory.hpp
Examples/Framework/include/ACTFW/EventData/Track.hpp
Examples/Framework/include/ACTFW/EventData/TruthFitTrack.hpp
Examples/Framework/src/EventData/SimMultiTrajectory.cpp
Examples/Io/Performance/ACTFW/Io/Performance/TrackFitterPerformanceWriter.cpp
Examples/Io/Root/src/RootTrajectoryWriter.cpp

The PR includes the following changes:
- Add `MultiTrajectoryHelpers` to help retrieve trajectory info like nHits, nHoles etc.
- Rename the `TruthFitTrack` to `SimMultiTrajectory`
- Extend the `SimMultiTrajectory` to cases with multiple trajectories
- Adapt the `TrackFitterPerformanceWriter` and `RooTrajectoryWriter` to use `SimMultiTrajectory`

Extend TruthFitTrack for CKF results

---

.github/workflows/builds.yml
docs/CMakeLists.txt
docs/Doxyfile
docs/conf.py
docs/getting_started.md

This changes the build configuration for local documentation builds. The default `docs` target builds the documentation without the automatic api generation but with the Sphinx/Doxygen bridge available. The full documentation can now be built via the `docs-with-api` instead. The default target should be fast and allow quick feedback. For the local build, Doxygen is also run separately from Sphinx and only if the source code changes. On readthedocs.org, all steps are run by Sphinx as before.

Faster local documentation builds

---

Core/include/Acts/Geometry/ConeVolumeBounds.hpp
Core/include/Acts/Geometry/CuboidVolumeBounds.hpp
Core/include/Acts/Geometry/CutoutCylinderVolumeBounds.hpp
Core/include/Acts/Geometry/CylinderVolumeBounds.hpp
Core/include/Acts/Geometry/TrapezoidVolumeBounds.hpp
Core/include/Acts/Surfaces/ConvexPolygonBounds.ipp
Core/src/Geometry/CMakeLists.txt
Core/src/Geometry/ConeVolumeBounds.cpp
Core/src/Surfaces/CMakeLists.txt
Core/src/Surfaces/ConvexPolygonBounds.cpp
Tests/CommonHelpers/Acts/Tests/CommonHelpers/ObjTestWriter.hpp
Tests/UnitTests/Core/Geometry/CMakeLists.txt
Tests/UnitTests/Core/Geometry/ConeVolumeBoundsTests.cpp
Tests/UnitTests/Core/Geometry/CutoutCylinderVolumeBoundsTests.cpp
Tests/UnitTests/Core/Geometry/CylinderVolumeBoundsTests.cpp
Tests/UnitTests/Core/Surfaces/PolyhedronSurfacesTests.cpp
Tests/UnitTests/Core/Visualization/VolumeVisualizationBase.hpp

Cherry-pick of `ConeBounds` introduction.
It replaces #198 (more information there).
Despite having introducing `ConeBounds` it also fixes a bug & a spelling mistake:
Unfortunately I do not have separate commits for the latter, but I think the changes are still limited.

Introducing ConeVolumeBounds

---

Core/include/Acts/TrackFinder/CombinatorialKalmanFilter.hpp
Examples/Algorithms/TrackFinding/include/ACTFW/TrackFinding/TrackFindingAlgorithm.hpp
Examples/Algorithms/TrackFinding/src/TrackFindingAlgorithm.cpp
Examples/Algorithms/TrackFinding/src/TrackFindingAlgorithmTrackFinderFunction.cpp

This PR makes the CKF templated on the source link container (instead of using `std::vector`).
This could avoid redundant container conversion from `boost::flat_multiset` to `std::vector`.

Use template for source link container in CKF

---

CMakeLists.txt
README.md
docs/getting_started.md

Update the Getting-started guide in the documentation:
- Include all (and correct) build options
- Consistent options help/ ordering in the `CMakeLists.txt` and in the documentation
- Update build instructions on lxplus and with a docker container

Update the Getting-Started guide

---

Examples/Io/HepMC3/src/HepMC3Event.cpp
Examples/Io/HepMC3/src/HepMC3Particle.cpp
Examples/Run/HepMC3/HepMC3Example.cpp

This fixes some warnings on my machine, and the `std::move`s are
unnecessary anyway.

Remove std::move in some HepMC3 code

---

Core/include/Acts/Visualization/EventDataVisualization.hpp

This PR includes a simple fix to the `drawBoundParameters` function. 
Before this fix, the ellipse showing covariance of local position is displaced from the cone showing the covariance of momentum direction as below:
After the fix, they origin of the cone overlaps with the center of the ellipse as expected:

Fix bound parameters visualization

---

Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.ipp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFitter.ipp
Core/include/Acts/Vertexing/KalmanVertexTrackUpdater.ipp
Core/include/Acts/Vertexing/KalmanVertexUpdater.ipp

This PR removes all unnecessary ```auto``` keywords in the ```KalmanVertexUpdater``` and ```KalmanVertexTrackUpdater``` and replaces them with the explicit types instead. Some recent, already fixed (and extremely hard to find) bugs appeared only in release (and not debug) build mode due to weird behaviour in the combined usage of ```auto``` and Eigens ```.block<>``` operations (in a different place). 
//Edit: AMVFitter and AMVFinder have also been updated.

Replace auto keywords in KalmanVertexUpdaters by explicit types

---

CMakeLists.txt
Tests/CommonHelpers/Acts/Tests/CommonHelpers/DataDirectory.cpp
Tests/CommonHelpers/Acts/Tests/CommonHelpers/DataDirectory.hpp
Tests/CommonHelpers/CMakeLists.txt
Tests/Data/README.md
Tests/IntegrationTests/CMakeLists.txt
Tests/IntegrationTests/PrintDataDirectory.cpp
cmake/FindFilesystem.cmake

This adds the `Tests/Data` directory for test-related data files and adds a `getDataPath()` utility to access them.
The implementation hard-codes the data path at compile time for the following reasons:
* Avoid unnecessary copies from source to build directory.
* Allow usage in unit tests where there is no access to `argv`.
* Tests are *never* installed. Hard coding the path is therefore not an issue.
This also includes a cmake module for handling `std::filesystem`. This also prepares for #193.

Add a test data directory

---

.github/workflows/builds.yml
.github/workflows/checks.yml
.github/workflows/coverage.yml

Currently the CI only runs on pushes to master, and on PRs that go into master.
This PR changes this (hopefully) to also run on release/* branches.

Run CI on release branches

---

Core/include/Acts/MagneticField/SharedBField.hpp
Core/include/Acts/Propagator/AtlasStepper.hpp
Core/include/Acts/Propagator/EigenStepper.hpp
Tests/UnitTests/Core/Propagator/AtlasStepperTests.cpp

Does exactly what the title says. This fixes a build issue on GCC 10.

Do not default-construct the stepper field input

---

.github/stale.yml

I think I misunderstood how this number is interpreted. I set it to 60,
but that means 60 days after the issue is marked stale it will be
deleted. This PR changes that number down to 14, which means after 30+14
= 44 days an issue without any activity other than this bot will be
closed.

Change stalebot days until close time

---

Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.ipp

The vertex seed finders return a vertex at the position of the vertex constraint if no more seed can be found. The AMVF should therefore check for the constraint z position rather than ```z==0``` as a break condition. This change has already been available in a different branch for AMVF timing measurements and was unfortunately not ported into master yet.

Backport: Change seed vertex break condition in AMVF

---

Core/include/Acts/Visualization/EventDataVisualization.hpp
Core/include/Acts/Visualization/GeometryVisualization.hpp
Core/src/Visualization/CMakeLists.txt
Core/src/Visualization/GeometryVisualization.cpp
Tests/UnitTests/Core/Geometry/ProtoLayerHelperTests.cpp
Tests/UnitTests/Core/Geometry/SurfaceArrayCreatorTests.cpp
Tests/UnitTests/Core/Visualization/EventDataVisualizationBase.hpp
Tests/UnitTests/Core/Visualization/PrimitivesVisualizationBase.hpp
Tests/UnitTests/Core/Visualization/PrimitivesVisualizationTests.cpp
Tests/UnitTests/Core/Visualization/SurfaceVisualizationBase.hpp
Tests/UnitTests/Core/Visualization/VolumeVisualizationBase.hpp

As shown in the briefing meeting, this allows to visualize the grid of surface arrays.
I also moves the code from the GeometryVisualization from inlined to a compilation unit.

Adding SurfaceArray visualization

---

cmake/ActsCompilerOptions.cmake
docs/getting_started.md

As discussed in #228, we currently don't set a default build type. This
PR sets `CMAKE_BUILD_TYPE` to `RelWithDebInfo` if it is not set
explicitly.

Set default build type to RelWithDebInfo

---

Core/ActsVersion.hpp.in
Tests/UnitTests/Core/CMakeLists.txt
Tests/UnitTests/Core/VersionTests.cpp

Also adds a unit test so the version header is actually included somewhere.
Fixes #28.

Clean up the version header

---

Core/src/Geometry/CutoutCylinderVolumeBounds.cpp

Previously, this was rMin -> rMax for the inner disks, and rMed -> rMax
for the outer disks. This has been changed to rMin -> rMed and rMin ->
rMax, respectively.

Fix CCVB outer disk boundary sized

---

.github/workflows/coverage.yml

This is a temporary measure to reduce the size of the output artifacts to avoid running out of disk space in the CI.

Remove non-core components from coverage build

---

Core/src/Geometry/CutoutCylinderVolumeBounds.cpp

Previously, this was rMin -> rMax for the inner disks, and rMed -> rMax
for the outer disks. This has been changed to rMin -> rMed and rMin ->
rMax, respectively.

Fix CCVB outer disk boundary sized (backport of #261)

---

.github/workflows/builds.yml
docs/getting_started.md

This could help alleviate pressure on the CI.

Drop the SLC6 build from CI

---

Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.hpp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.ipp

This PR removes the ```estimateDeltaZ``` function (which contributed 5.5% to the overall AMVF timing, see below) and replaces it with a simple z position diff check which is way less expensive and gives the same outputs.

More AMVF performance upgrades

---

Core/include/Acts/Fitter/GainMatrixSmoother.hpp
Core/include/Acts/Fitter/GainMatrixUpdater.hpp
Core/include/Acts/Fitter/KalmanFitter.hpp
Core/include/Acts/Fitter/detail/VoidKalmanComponents.hpp
Core/include/Acts/TrackFinder/CombinatorialKalmanFilter.hpp
Examples/Algorithms/Fitting/src/FittingAlgorithmFitterFunction.cpp
Examples/Algorithms/TrackFinding/src/TrackFindingAlgorithmTrackFinderFunction.cpp
Tests/UnitTests/Core/Fitter/GainMatrixSmootherTests.cpp
Tests/UnitTests/Core/Fitter/GainMatrixUpdaterTests.cpp
Tests/UnitTests/Core/Fitter/KalmanFitterTests.cpp
Tests/UnitTests/Core/TrackFinder/CombinatorialKalmanFilterTests.cpp
Tests/UnitTests/Core/Visualization/EventDataVisualizationBase.hpp

This PR removes unnecessary template parameters from the the (C)KF and the gain matrix formulation. Additionally unused variables, typedefs and a function are removed in this cleanup.

Remove unnecessary/unused elements from (C)KF

---

Core/include/Acts/Vertexing/GridDensityVertexFinder.ipp

This PR introduces a check if removable tracks (that pass the seed finder track selection) still exist.
Previously, the seed track collection could have had still tracks that were never added to the density grid (since they did not pass the internal seed finder track selection) and hence the seed finder could not remove them from the grid. The client AMVF would then just continue iterating and removing all of these tracks one by one. This check directly stops the seeding and vertex finding process and speeds up things dramatically.

Check for removable tracks in GridDensityVertexFinder

---

Examples/Algorithms/MaterialMapping/include/ACTFW/MaterialMapping/MaterialMappingOptions.hpp
Examples/Algorithms/MaterialMapping/src/MaterialMapping.cpp
Examples/Run/Common/src/MaterialMappingBase.cpp

Modify the mapping algorithm in the examples to allow to map surface and volume at the same time (instead of doing it one after the other).
Added 3 option to the mapping : 
- mat-mapping-surfaces that determine if material is mapped on surface (true by default)
- mat-mapping-volumes that determine if material is mapped on volume (false by default)
- mat-mapping-volume-stepsize that correspond to that size of the extra step used to sample the material on the volume, infinite by default (no additional step created)

Improvement of the Mapping Example

---

Core/include/Acts/Material/AccumulatedVolumeMaterial.hpp
Core/src/Material/AccumulatedVolumeMaterial.cpp
Core/src/Material/VolumeMaterialMapper.cpp

Solve two issue with the volume material mapping :
- When the sampling step size of the volume was larger than the distance between two geantino interaction this would result in an incorrect thickness for the material Step.
- Replace float by double for the accumulated volume material as if the number of step per bin became too large this would result in rounding error.

Fix Volume material mapping

---

Tests/UnitTests/Core/Utilities/ResultTests.cpp

Fixes Result related warnings surfaced in #267. They are due to `Result<double>` being assigned integer literals, which `Result` just passes through. This is what the compiler complains about then.

Fix narrowing conversions in Result Test

---

Core/include/Acts/Surfaces/detail/VerticesHelper.hpp
Core/src/Surfaces/CMakeLists.txt
Core/src/Surfaces/EllipseBounds.cpp
Core/src/Surfaces/VerticesHelper.cpp

Move non-template function implementations to a `.cpp` file. This fixes compiler warnings that appear with #267.

Fix compiler warning in VerticesHelper

---

Core/include/Acts/Material/Material.hpp
Core/src/Material/Material.cpp
Tests/UnitTests/Core/Material/MaterialTests.cpp

Remove the public `enum` within the `Material` class that describes the content of the classification numbers vector. The classification numbers can still be used to stored the encoded material information. In order to interpret it, a `Material` object has to be constructed again.
The functionality was no used in the code base and removing it will make it easier to change the internal parametrization as planned in #31. Should also fix compiler warning regarding enum name clashes that show up in #267.

Make the material classification numbers an opaque vector

---

Core/include/Acts/Fitter/GainMatrixSmoother.hpp
Core/include/Acts/Propagator/Propagator.ipp
Core/include/Acts/Vertexing/GaussianTrackDensity.hpp

Fixes some more compiler warnings that show up in #267.

Fix even more compiler warnings

---

Core/include/Acts/Propagator/RiddersPropagator.ipp
Core/include/Acts/Utilities/Result.hpp

Ensure correct rvalue reference forwarding and use `default` implementations where possible. Update the `RiddersPropagator` to use explicit return types. This fix some remaining compiler warning for #267.

Fix Result constructor

---

.github/workflows/builds.yml
.github/workflows/checks.yml
.github/workflows/coverage.yml
Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.hpp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.ipp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFitter.hpp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFitter.ipp
Core/include/Acts/Vertexing/FullBilloirVertexFitter.hpp
Core/include/Acts/Vertexing/FullBilloirVertexFitter.ipp
Core/include/Acts/Vertexing/HelicalTrackLinearizer.hpp
Core/include/Acts/Vertexing/HelicalTrackLinearizer.ipp
Core/include/Acts/Vertexing/ImpactPointEstimator.hpp
Core/include/Acts/Vertexing/ImpactPointEstimator.ipp
Core/include/Acts/Vertexing/IterativeVertexFinder.hpp
Core/include/Acts/Vertexing/IterativeVertexFinder.ipp
Core/include/Acts/Vertexing/LinearizerConcept.hpp
Core/include/Acts/Vertexing/VertexFitterConcept.hpp
Examples/Algorithms/Vertexing/include/ACTFW/Vertexing/AdaptiveMultiVertexFinderAlgorithm.hpp
Examples/Algorithms/Vertexing/src/IterativeVertexFinderAlgorithm.cpp
Examples/Algorithms/Vertexing/src/VertexFitAlgorithm.cpp
Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFinderTests.cpp
Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFitterTests.cpp
Tests/UnitTests/Core/Vertexing/FullBilloirVertexFitterTests.cpp
Tests/UnitTests/Core/Vertexing/ImpactPointEstimatorTests.cpp
Tests/UnitTests/Core/Vertexing/IterativeVertexFinderTests.cpp
Tests/UnitTests/Core/Vertexing/KalmanVertexTrackUpdaterTests.cpp
Tests/UnitTests/Core/Vertexing/KalmanVertexUpdaterTests.cpp
Tests/UnitTests/Core/Vertexing/LinearizedTrackFactoryTests.cpp

This PR is similar to #306 but targets the release v0.27 branch.

Backport v0.27: Introduce bfield caching in vertexing and remove refitAfterBadVertex AMVF option

---

Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.ipp
Plugins/Cuda/src/Seeding/Kernels.cu
Tests/UnitTests/Plugins/Cuda/Seeding/SeedfinderCudaTest.cpp

calling __syncthreads in a conditional that depends on the threadID results in undefined behaviour.
Interestingly, this wasn't apparent on older versions of the NVidia drivers, but is now.
Also, added option to SeedFinderCudaTest to not run on CPU, so as to test the GPU faster for large input files.

fix CUDA kernel syncthread usage

---

CMakeLists.txt
docs/getting_started.md

- Add `Tests` subdirectory only if at least one test-like option is active.
- Order test-related options alphabetically.

Small CMake fixes

---

Plugins/Json/include/Acts/Plugins/Json/JsonMaterialDecorator.hpp
Plugins/Json/src/JsonGeometryConverter.cpp

Fix two issue with the json material decoration/conversion : 
- The decorator was not using the config provided.
-  All the surface and volume material present in the json file were created even when the mapkey was false.

Json converter fix

---

Core/include/Acts/EventData/SingleBoundTrackParameters.hpp
Core/include/Acts/EventData/SingleCurvilinearTrackParameters.hpp
Core/include/Acts/EventData/SingleFreeTrackParameters.hpp
Core/include/Acts/EventData/SingleTrackParameters.hpp
Core/include/Acts/EventData/TrackParametersConcept.hpp
Core/include/Acts/Fitter/detail/KalmanGlobalCovariance.hpp
Core/include/Acts/TrackFinder/CKFSourceLinkSelector.hpp
Examples/Framework/include/ACTFW/Validation/ResPlotTool.hpp
Examples/Framework/src/Validation/ResPlotTool.cpp
Tests/UnitTests/Core/EventData/BoundTrackParametersTests.cpp
Tests/UnitTests/Core/EventData/MultiTrajectoryTests.cpp
Tests/UnitTests/Core/Fitter/GainMatrixSmootherTests.cpp
Tests/UnitTests/Core/Fitter/GainMatrixUpdaterTests.cpp
Tests/UnitTests/Core/Fitter/KalmanFitterTests.cpp
Tests/UnitTests/Core/TrackFinder/CombinatorialKalmanFilterTests.cpp
Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFitterTests.cpp
Tests/UnitTests/Core/Vertexing/ImpactPointEstimatorTests.cpp
Tests/UnitTests/Core/Vertexing/KalmanVertexTrackUpdaterTests.cpp
Tests/UnitTests/Core/Vertexing/KalmanVertexUpdaterTests.cpp
Tests/UnitTests/Core/Visualization/EventDataViewBase.hpp

This PR ensures consistently named nested typedefs for the underlying scalar/vector/matrix types of all concrete track parameters classes. All track parameters types provide `Scalar`, `ParametersVector`, and `CovarianveMatrix` typedefs. The longer names are chosen over just `Parameters` and `Covariance` to avoid any confusion between the raw vectors and the track parameters types (that store parameters and covariance). The `{Bound,Free}TrackParametersConcept` are adapted accordingly.
This is the second smaller PR split from #298.

Consistent nested track parameters vector/matrix types

---

Core/include/Acts/EventData/SingleBoundTrackParameters.hpp
Core/include/Acts/EventData/SingleCurvilinearTrackParameters.hpp
Core/include/Acts/EventData/SingleFreeTrackParameters.hpp
Core/include/Acts/EventData/SingleTrackParameters.hpp
Core/include/Acts/EventData/detail/PrintParameters.hpp
Core/src/EventData/CMakeLists.txt
Core/src/EventData/PrintParameters.cpp

Add compiled print helper functions to remove `#include <iostream>` from the track parameters headers.
This is the third smaller PR split from #298.

Add print helpers for track parameters

---

Core/include/Acts/Propagator/Navigator.hpp
Tests/UnitTests/Core/Propagator/NavigatorTests.cpp

The current `Navigator` workflow allows a fast initialisation iff a `startSurface` and no `startVolume` is set. Given the inverse scenario, a slow lookup from the world volume is started, ignoring a potential set `startVolume`. This PR adds the possibility to start also from a given volume.

Allow navigation initialisation from a given volume

---

Core/include/Acts/EventData/MultiTrajectory.hpp
Tests/UnitTests/Core/EventData/MultiTrajectoryTests.cpp

The number of columns for projectors in the `MultiTrajectory` is using the maximal size of the measurements instead of the track parameters size. This is fixed with this PR.

Fix number of columns for projectors

---

Core/include/Acts/Utilities/Helpers.hpp
Core/include/Acts/Utilities/ParameterDefinitions.hpp
Core/include/Acts/Vertexing/AMVFInfo.hpp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.ipp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFitter.ipp
Core/include/Acts/Vertexing/FullBilloirVertexFitter.ipp
Core/include/Acts/Vertexing/HelicalTrackLinearizer.hpp
Core/include/Acts/Vertexing/HelicalTrackLinearizer.ipp
Core/include/Acts/Vertexing/KalmanVertexTrackUpdater.hpp
Core/include/Acts/Vertexing/KalmanVertexTrackUpdater.ipp
Core/include/Acts/Vertexing/LinearizedTrack.hpp
Core/include/Acts/Vertexing/LinearizerConcept.hpp
Core/include/Acts/Vertexing/Vertex.hpp
Core/include/Acts/Vertexing/Vertex.ipp
Core/include/Acts/Vertexing/ZScanVertexFinder.ipp
Tests/UnitTests/Core/Utilities/HelpersTests.cpp
Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFitterTests.cpp
Tests/UnitTests/Core/Vertexing/FullBilloirVertexFitterTests.cpp
Tests/UnitTests/Core/Vertexing/ImpactPointEstimatorTests.cpp
Tests/UnitTests/Core/Vertexing/IterativeVertexFinderTests.cpp
Tests/UnitTests/Core/Vertexing/KalmanVertexTrackUpdaterTests.cpp
Tests/UnitTests/Core/Vertexing/KalmanVertexUpdaterTests.cpp
Tests/UnitTests/Core/Vertexing/LinearizedTrackFactoryTests.cpp

This removes all `SpacePoint` related types and definitions and replaces them with `Vector4D` and related types. Access to the vector components is always performed via enum values and the unused vector helpers are removed.
This is a followup to #143 and #286.

Remove SpacePoint

---

Core/include/Acts/EventData/MultiTrajectory.hpp
Core/include/Acts/EventData/MultiTrajectory.ipp
Core/include/Acts/Fitter/GainMatrixSmoother.hpp
Core/include/Acts/Fitter/GainMatrixUpdater.hpp
Tests/UnitTests/Core/EventData/MultiTrajectoryTests.cpp

The track parametrisation has `eBoundParametersSize` dimensions. As this is already fixed in the current `ParametersSize` in the `MultiTrajectory` and is therefore already constant, this PR replaces `ParametersSize` by `eBoundParametersSize`.

Fix parameter dimension in MultiTrajectory

---

Plugins/Json/src/JsonGeometryConverter.cpp

Fix an issue with the jsonToBinUtility. The bin the the json file can be 3 or 4 elements depending on if we read a geometry map or a material map. 
The old code was causing segfault within athena, that issue will be solve by this PR.

Fix of the jsonToBinUtility

---

Core/include/Acts/EventData/Measurement.hpp
Core/include/Acts/EventData/ParameterSet.hpp
Examples/Io/Root/src/RootTrajectoryWriter.cpp

Within this PR multiple smaller changes occur. 
1. The parameter indices are renamed to match the new pattern.
2. The reference surface is always picked from the uncalibrated `SourceLink`.
3. The constructions of `BoundParameters` were constructed in order to access member variables/methods that can be provided otherwise. This PR avoids all these constructor calls.
4. A single calculation of the residual to a measurement is needed. Due to the changes in 3. a residual function using a vector is added to the `ParameterSet` and `Measurement` API.

RootTrajectoryWriter cleanup

---

Tests/UnitTests/Core/Utilities/MaterialMapUtilsTests.cpp

We are now using the library-based version of Boost.Test, rather than the header-based version. But for some reason, this specific unit test retained the old usage. Which causes an invalid free of a global `std::string` from Boost.Test at runtime, when the test is built with clang.
The most likely explanation is that...
- A global variable ends up being defined twice, once by the header and once by the library.
- The linker manages to unify the two declarations since they are identical, so it does not error out.
- ...but it does not deduplicate the destructors, ergo an invalid free happens.
But I have no idea why that worked with GCC...

Fix usage of Boost.Test header in MaterialMapUtilsTest

---

Plugins/Json/src/JsonGeometryConverter.cpp

Added the creation of a default bin utility for rectangle bound (sensor) in the json converter.
The contains method that was used for reading the BinUtility transform has been replace by a for loop as it is only available in nlohmann::json 3.7.0 and athena use 3.5.0 (for now this seems easier than having people change the json version use in athena).

Json bin initialisation for rectangle bound

---

Examples/Io/Obj/src/ObjTrackingGeometryWriter.cpp

This fixes a small bug of the calling the `drawTrackingVolume` in the  'ObjTrackingGeometryWriter`.

Fix draw tracking volume invocation bug

---

Core/include/Acts/Fitter/KalmanFitter.hpp
Core/include/Acts/Fitter/KalmanFitterError.hpp
Core/include/Acts/TrackFinder/CombinatorialKalmanFilter.hpp
Core/include/Acts/TrackFinder/CombinatorialKalmanFilterError.hpp
Tests/UnitTests/Core/Fitter/KalmanFitterTests.cpp

We could expect that there is no target surface provided in the KF when fitted track parameter at an additional surface is not needed. For example, in the KF-based alignment, the fit is repeatedly done where we don't care about the fitted track parameter at a target surface. Currently, the `KalmanFitterOptions` could allow a null target surface, but the fit will actually break if no surface is provided. This PR includes the following changes:
- Allow non target surface in the KF
- Remove some redundancy to abort the KF/CKF propagation when track fitting/finding is supposed to finished
- Rename the KF/CKF error type

Allow KF fit without target surface

---

Core/include/Acts/Fitter/GainMatrixUpdater.hpp
Core/include/Acts/Fitter/KalmanFitter.hpp
Tests/UnitTests/Core/Fitter/KalmanFitterTests.cpp

Currently, the outlier check is done after the Kalman filtering. This PR moves the outlier check before the Kalman filtering. In this way, only those non-outlier measurement will be passed to the Kalman filtering.

Check the outlier before Kalman filtering

---

Examples/Detectors/TGeoDetector/include/ACTFW/TGeoDetector/TGeoDetectorOptions.hpp
Plugins/TGeo/src/TGeoLayerBuilder.cpp

Bugfix that prevented more than 3 sub detectors to be properly parsed with the `TGeoPlugin`.
With this, we can make the HGTD appear :-)

Bugfix in TGeoDetectorOptions

---

.policy.yml

Should invalidate reviews on push now, but ignore update merges. It will
(hopefully) also accept approvals by 'contributors', such as when an
approver clicks the 'Update branch' button.

Change policybot configuration: invalidate on push, contributors

---

Core/include/Acts/EventData/Measurement.hpp
Core/include/Acts/EventData/ParameterSet.hpp
Core/include/Acts/EventData/detail/initialize_parameter_set.hpp
Tests/UnitTests/Core/EventData/MeasurementTests.cpp
Tests/UnitTests/Core/EventData/ParameterSetTests.cpp

As discussed this morning, I encapsulated the problem from my work on the digitisation:
* this PR will hopefully first fix the ambiguity in constructing parameter sets
* then it should introduce a new `Measurement( ..., covariance, vector)` constructor

Introduce Measurement constructor from covariance and vector

---

Core/include/Acts/Propagator/Propagator.ipp
Core/include/Acts/Propagator/PropagatorError.hpp

Previously, this would not set the `terminatedNormally`
flag, and cause an error printout. This switches this error printout to
an error, but prevent the case of zero steps triggering it.
/cc @baschlag

Propagator: Terminate normally in case of 0 steps

---

Core/include/Acts/Fitter/GainMatrixUpdater.hpp

It seems that Eigen matrix constructors from expression templates have more build-time overhead than the assignment operator equivalent. When that extra overhead is sent through the `visitMeasurement` code bloat multiplier (see #350 for context), that ultimately translates into a +0.7GB build RSS hit in `EventDataView3D` tests. Let's revert that part of #359 for now.

refactor: Resolve build regression from #359

---

Core/include/Acts/Material/Interactions.hpp
Core/src/Material/Interactions.cpp

All interaction computations only consider the charge magnitude. This avoids unnecessary assertions in debug builds. The documentation is updated accordingly.
Includes some drive-by whitespace formatting.

fix: clarify interactions charge parameter

---

Core/include/Acts/Geometry/GeometryObject.hpp
Core/include/Acts/Geometry/NavigationLayer.hpp
Core/include/Acts/Geometry/Volume.hpp
Core/include/Acts/Surfaces/ConeSurface.hpp
Core/include/Acts/Surfaces/CylinderSurface.hpp
Core/include/Acts/Surfaces/DiscSurface.hpp
Core/include/Acts/Surfaces/LineSurface.hpp
Core/include/Acts/Surfaces/PlaneSurface.hpp
Core/include/Acts/Surfaces/Surface.hpp
Core/include/Acts/Surfaces/detail/ConeSurface.ipp
Core/include/Acts/Surfaces/detail/CylinderSurface.ipp
Core/include/Acts/Surfaces/detail/DiscSurface.ipp
Core/include/Acts/Surfaces/detail/LineSurface.ipp
Core/include/Acts/Surfaces/detail/PlaneSurface.ipp
Core/include/Acts/Surfaces/detail/Surface.ipp
Core/src/Geometry/Volume.cpp
Core/src/Surfaces/ConeSurface.cpp
Core/src/Surfaces/CylinderSurface.cpp
Core/src/Surfaces/DiscSurface.cpp
Core/src/Surfaces/Surface.cpp
Tests/UnitTests/Core/Surfaces/SurfaceStub.hpp
docs/core/geometry.md

This PR removes the unnecessary `const` qualifier within the `Surface` package in case of returning by value, e.g. 
```c++
const ReturnType bla() const 
```
is changed consistently to 
```c++
ReturnType bla() const
```
if `ReturnType` is an object returned by value.
It currently sits on top of #399 and thus is marked const, but is a single commit that can either be rebased after #399 is merged or cherry-picked.
BREAKING CHANGE: it changes the method signature of those return objects, but somewhat silently because clients could always convert into `const` or from `const` via copy/assignment.

refactor: Remove unnecessary const qualifiers

---

Core/include/Acts/Propagator/Propagator.ipp
Core/include/Acts/Propagator/PropagatorError.hpp

This was `unknown` before, because I had forgotton to add it in the switch statement. Also fixes a missing space in a related error printout.

fix: Add error message for StepCountLimitReached

---

Core/include/Acts/EventData/TrackStatePropMask.hpp
Core/include/Acts/Geometry/GeometryObject.hpp
Core/include/Acts/Geometry/GeometryObjectSorter.hpp
Core/include/Acts/Geometry/TrackingGeometryBuilder.hpp
Core/include/Acts/Seeding/BinnedSPGroup.hpp
Core/include/Acts/Seeding/SeedFilter.hpp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.hpp
Core/include/Acts/Vertexing/ImpactPointEstimator.hpp

Also fixes some instances of classes being reported outside the Acts namespace due to weird doc comments.
Fixes #426
BREAKING CHANGE: `TrackStatePropeMask` moves to `Acts::TrackStatePropMask`

fix!: Move TrackStatePropMask to Acts namespace

---

Core/include/Acts/Utilities/BinAdjustment.hpp
Core/include/Acts/Utilities/BinAdjustmentVolume.hpp
Core/include/Acts/Utilities/BinUtility.hpp
Core/src/Material/MaterialGridHelper.cpp
Plugins/Json/src/JsonGeometryConverter.cpp
Tests/UnitTests/Core/Utilities/BinUtilityTests.cpp

This is the last PR to change Transform3D storage to be done by value.
Is independent from #411, and closes #412.
No measurable change in timing is observed by omitting the check if a transforms exists and only then multiply by the transform.
BREAKING CHANGE: the interface of the constructor and retrieval of the Transform3D for the `BinUtility` class

refactor: BinUtility: Move Transform3D to storage by value

---

Core/include/Acts/Surfaces/DiscSurface.hpp
Core/src/Surfaces/DiscSurface.cpp

Closes #442 which revealed a bug actually.
The `DiscSurface` would construct `DiscTrapezoidBounds` with the wrong order of arguments.

fix: fixing rmin/rmax ordering in DiscSurface

---

Core/src/Material/VolumeMaterialMapper.cpp

I made a small mistake in the last PR leading to material being ignore if not thick enough. 
This PR fixes it.

refactor: Bugfix Volume material mapper

---

Core/include/Acts/EventData/SingleBoundTrackParameters.hpp
Core/include/Acts/EventData/SingleCurvilinearTrackParameters.hpp
Tests/UnitTests/Core/EventData/MultiTrajectoryTests.cpp
Tests/UnitTests/Core/Fitter/KalmanFitterTests.cpp
Tests/UnitTests/Core/Geometry/BVHDataTestCase.hpp
Tests/UnitTests/Core/Propagator/AtlasStepperTests.cpp
Tests/UnitTests/Core/Propagator/DirectNavigatorTests.cpp
Tests/UnitTests/Core/Propagator/ExtrapolatorTests.cpp
Tests/UnitTests/Core/Propagator/JacobianTests.cpp
Tests/UnitTests/Core/Propagator/KalmanExtrapolatorTests.cpp
Tests/UnitTests/Core/Propagator/LoopProtectionTests.cpp
Tests/UnitTests/Core/Propagator/MaterialCollectionTests.cpp
Tests/UnitTests/Core/Propagator/NavigatorTests.cpp
Tests/UnitTests/Core/Propagator/PropagatorTests.cpp
Tests/UnitTests/Core/Propagator/StepperTests.cpp
Tests/UnitTests/Core/Propagator/StraightLineStepperTests.cpp
Tests/UnitTests/Core/Surfaces/AlignmentHelperTests.cpp
Tests/UnitTests/Core/TrackFinder/CombinatorialKalmanFilterTests.cpp
Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFitterTests.cpp
Tests/UnitTests/Core/Vertexing/GridDensityVertexFinderTests.cpp
Tests/UnitTests/Core/Vertexing/ImpactPointEstimatorTests.cpp
Tests/UnitTests/Core/Vertexing/TrackDensityVertexFinderTests.cpp
Tests/UnitTests/Core/Visualization/EventDataView3DBase.hpp

Remove deprecated constructors from track parameters types and update the constructor calls mostly in the tests.
This is a follow up to #437 and needs to be merged afterwards.

refactor!: Remove deprecated parameters constructors (Rework charge types, Part 2)

---

Core/src/Geometry/CuboidVolumeBuilder.cpp

This PR fixes the hard-coded layer thickness (`1_um`) for the cuboid volume layers. Without this fix, a surface `thickness` in the ` SurfaceConfig` larger than 2 um will lead to layers overlapping error.

fix: hard-coded value for cuboid volume binning range

---

.github/workflows/analysis.yml
.github/workflows/builds.yml
.github/workflows/checks.yml
Tests/DownstreamProject/CMakeLists.txt
cmake/ActsConfig.cmake.in
docs/getting_started.md

Use container images from the public Github container registry in the CI builds. This removes one of the last dependencies on CERN infrastructure as the images were previously taken from the CERN Gitlab registry.
Some of the build jobs are unified to reduce variability between builds. The separated downstream build has been removed. An extended downstream test build is now part of the regular build jobs so that all build configurations are tested consistently.
Includes some fixes for errors in the installed CMake config.

ci: Use containers from the Github registry and unify CI jobs

---

cmake/FindSYCL.cmake

This removes the automatic linking of the "SYCL object files" of the oneAPI compiler by default. They were necessary when using the OpenCL backend, with a previous version of the SYCL plugin. But they are no longer needed. And they are actually outright harmful when using the CUDA backend of the oneAPI compiler. (As @cgleggett very rightfully complained about it.)
With this update, with the latest version of Intel's compiler that I have available, unfortunately it's still not possible to build a single binary for both OpenCL and CUDA backends. But at least separate builds can successfully made like:
```
[bash][Elrond]:build > cmake -DCMAKE_BUILD_TYPE=Release -DACTS_BUILD_PLUGIN_SYCL=TRUE -DACTS_BUILD_UNITTESTS=TRUE ../acts/
-- The CXX compiler identification is Clang 12.0.0
-- Detecting …
```

build: Make it easier to build the SYCL plugin correctly

---

cmake/FindSYCL.cmake

As @cgleggett made us aware with @czangela, the code was not handling it gracefully enough if one would ask for the build of the SYCL plugin while not having a SYCL capable compiler set up.
Previously I thought that just setting `SYCL_FOUND` to `FALSE` would be enough for `find_package(SYCL REQUIRED)` to fail. But apparently not... So now the code explicitly makes use of CMake's built-in function for handling such arguments passed to `find_package(...)`.

build: FindSYCL.cmake Improvement, master branch (2020.09.22.)

---

Tests/UnitTests/Fatras/Digitization/UncorrelatedHitSmearerTests.cpp

This fixes the clang compatibility issue that we see with `std::reference_wrapper<std::any>`, as from #343
Issue found when compiling with dpcpp/clang++ w/ the SYCL plugin.

fix: address std::any issue with clang

---

Core/include/Acts/Utilities/MultiIndex.hpp
Core/src/EventData/PrintParameters.cpp
Core/src/Geometry/GeometryIdentifier.cpp
Core/src/Material/Material.cpp
Fatras/src/Particle.cpp
Fatras/src/ParticleData.cpp
Tests/Data/material-map.json

These are cleanups and fixes to various print outputs as preparation for upcoming event data changes.
Track parameters are now printed by name with the covariance decomposed into standard deviations and correlations. The new output looks like this:
```
loc0:           0 +- 0.03         1.000
loc1:           0 +- 0.008092     0.000  1.000
phi:        2.645 +- 0.01745      0.000  0.000  1.000
theta:      2.864 +- 0.01745      0.000  0.000  0.000  1.000
q/p:     -0.06783 +- 6.778e-05    0.000  0.000  0.000  0.000  1.000
time:       -2041 +- 1499         0.000  0.000  0.000  0.000  0.000  1.000
on surface (vol=X|lay=Y|sen=Z) of type Acts::PlaneSurface
```
The `GeometryIdentifier` use names to identify its components as follows
```
(undefined) # if all components are zero
(vol=4|lay=3|sen=3) # …
```

refactor: Better print output

---

Core/include/Acts/Surfaces/ConeSurface.hpp
Core/include/Acts/Surfaces/CylinderSurface.hpp
Core/include/Acts/Surfaces/DiscSurface.hpp
Core/include/Acts/Surfaces/LineSurface.hpp
Core/include/Acts/Surfaces/PlaneSurface.hpp
Core/include/Acts/Surfaces/Surface.hpp
Core/include/Acts/Surfaces/detail/LineSurface.ipp
Core/src/Surfaces/ConeSurface.cpp
Core/src/Surfaces/CylinderSurface.cpp
Core/src/Surfaces/DiscSurface.cpp
Core/src/Surfaces/PlaneSurface.cpp
Tests/UnitTests/Core/Surfaces/PlaneSurfaceTests.cpp
Tests/UnitTests/Core/Surfaces/SurfaceStub.hpp

As brought up on Mattermost and #493, the static tolerance in the `globalToLocal` functions might not be desirable.
This PR adds an additional argument that sets the tolerance. It is defaulted to `s_onSurfaceTolerance`, which was hardcoded before. This should be backwards compatible.
/cc @osbornjd

feat: add tolerance parameter to globalToLocal functions

---

Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSmearing.cpp
Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSmearing.hpp
Examples/Framework/include/ActsExamples/EventData/Track.hpp

Change the `ParticleSmearing` to actually smear in the perigee frame with a common perigee surface for all particles originating from the same vertex instead of smearing each particle in its own curvilinear frame with projected uncertainties.
To do so, the default track parameters in the framework are changed to bound parameters. With the recent changes of the Core EDM this is no possible since curvilinear parameters are just bound parameters and can be store within.

refactor(examples): Smear particle in the perigee frame

---

Core/include/Acts/Propagator/ConstrainedStep.hpp
Core/include/Acts/Propagator/detail/LoopProtection.hpp
Core/include/Acts/Utilities/AnnealingUtility.hpp
Core/include/Acts/Vertexing/GaussianTrackDensity.ipp
Core/src/Utilities/AnnealingUtility.cpp

This PR fixes the FPE overflow issues that we've seen in running the AMVF on q221 and q431 jobs in Athena:
- We've first seen this issue in the propagator loop protection. The issue here was a square of ```pathLimit``` while 
```cpp
pathLimit = std::numeric_limits<double>::max();
```
- Same thing as above happened in the ```ConstrainedStep```.
-  A divide-by-zero protection was added to ```GaussianTrackDensity```.
- [This line in the annealing tool](https://github.com/acts-project/acts/blob/af17d414b9b4365e441101a8fbd636a37822151a/Core/src/Utilities/AnnealingUtility.cpp#L36) also threw an FPE for very large ```chi2``` values, since the denominator in the weight calculation will become extremely large. I've redone the math (+validated its correctness numerically) such that the ```chi2``` …

fix: Fix FPE overflow issue

---

Examples/Algorithms/Digitization/src/PlanarSteppingAlgorithm.cpp
Examples/Io/Csv/src/CsvPlanarClusterReader.cpp
Plugins/Digitization/include/Acts/Plugins/Digitization/DigitizationCell.hpp
Plugins/Digitization/include/Acts/Plugins/Digitization/DigitizationSourceLink.hpp
Plugins/Digitization/include/Acts/Plugins/Digitization/PlanarModuleCluster.hpp
Plugins/Digitization/include/Acts/Plugins/Digitization/PlanarModuleStepper.hpp
Tests/UnitTests/Plugins/Digitization/DoubleHitSpacePointBuilderTests.cpp

Remove the dependency of the digitization plugin on the generic `Identifier` and the `IdentificationPlugin`. Introduce a custom `DigitizationSourceLink` instead, that fulfills the `SourceLinkConcept` and contains all the necessary information.

refactor(plugin/digitization): Add Digitization-specific SourceLink (EDM rework part 2a/4)

---

Examples/Algorithms/Printers/ActsExamples/Printers/HitsPrinter.cpp
Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TruthSeedSelector.cpp
Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TruthTrackFinder.cpp
Examples/Framework/include/ActsExamples/EventData/Index.hpp
Examples/Framework/include/ActsExamples/EventData/ProtoTrack.hpp
Examples/Framework/include/ActsExamples/EventData/ProtoVertex.hpp
Examples/Framework/include/ActsExamples/Validation/ProtoTrackClassification.hpp
Examples/Io/Csv/src/CsvPlanarClusterReader.cpp
Examples/Io/Performance/ActsExamples/Io/Performance/TrackFinderPerformanceWriter.cpp

Add a `Index` typeded to be used to identify indices into edm containers. The `IndexMultimap<...>` container is updated to always use this type as its key instead of being templated on it.

feat(examples): Add/use a concrete Index type for containers. (EDM rework part 2b/4)

---

Core/include/Acts/Surfaces/ConeSurface.hpp
Core/include/Acts/Surfaces/CylinderSurface.hpp
Core/include/Acts/Surfaces/DiscSurface.hpp
Core/include/Acts/Surfaces/LineSurface.hpp
Core/include/Acts/Surfaces/Surface.hpp
Core/include/Acts/Surfaces/detail/ConeSurface.ipp
Core/include/Acts/Surfaces/detail/CylinderSurface.ipp
Core/include/Acts/Surfaces/detail/DiscSurface.ipp
Core/include/Acts/Surfaces/detail/LineSurface.ipp
Core/include/Acts/Surfaces/detail/Surface.ipp
Core/include/Acts/Utilities/AlignmentDefinitions.hpp
Core/src/Propagator/detail/CovarianceEngine.cpp
Core/src/Surfaces/Surface.cpp
Tests/UnitTests/Core/Surfaces/DiscSurfaceTests.cpp
Tests/UnitTests/Core/Surfaces/LineSurfaceTests.cpp
Tests/UnitTests/Core/Surfaces/PlaneSurfaceTests.cpp

BREAKING CHANGE: This PR refactors the interfaces for calculating the Jacobian/derivatives between bound parameters/alignment parameters and free parameters. There are four types of functions involved for those calculations:
1. The free parameters transportation function
2. The transforms between free parameters and bound parameters (In principle, the transforms could be further split into the free parameters <=> local cartesian coordinates, and local cartesian coordinates <=> bound parameters)
3. The geometry constraint for the intersection or the POCA
This PR changes/fixes the relevant functions to explicitly calculate the derivatives of the above 2 and 3. This could allow validation of those calculations by comparing the results with those from Autodiff.

refactor!: split fit/alignment derivatives calculation

---

Examples/Io/HepMC3/CMakeLists.txt
Examples/Io/HepMC3/include/ActsExamples/Io/HepMC3/HepMC3Event.hpp
Examples/Io/HepMC3/include/ActsExamples/Io/HepMC3/HepMC3Options.hpp
Examples/Io/HepMC3/include/ActsExamples/Io/HepMC3/HepMC3Reader.hpp
Examples/Io/HepMC3/include/ActsExamples/Io/HepMC3/HepMC3Writer.hpp
Examples/Io/HepMC3/src/HepMC3Event.cpp
Examples/Io/HepMC3/src/HepMC3Options.cpp
Examples/Io/HepMC3/src/HepMC3Reader.cpp
Examples/Io/HepMC3/src/HepMC3Writer.cpp
Examples/Run/HepMC3/CMakeLists.txt
Examples/Run/HepMC3/HepMC3Example.cpp

This PR modifies the `HepMCWriter` and `HepMCReader` such that they can be used as algorithms in the `Sequencer`.

refactor(examples): HepMCWriter and Reader as algorithm

---

Examples/Io/Performance/ActsExamples/Io/Performance/CKFPerformanceWriter.cpp
Examples/Io/Performance/ActsExamples/Io/Performance/TrackFitterPerformanceWriter.cpp
Examples/Io/Root/src/RootTrajectoryWriter.cpp
Examples/Run/Fatras/Common/FatrasDigitization.cpp

As a follow-up to #511, this PR adds those missing output collections in the `FatrasDigitization.cpp` and fixes some input collections in a few Root/Performance writers.

fix(examples): Missing digitization output collections

---

Plugins/Json/src/JsonGeometryConverter.cpp

In the json converter, for a give volume, only write the boundary surface associated to said volume. If all boundary are written they could over-right each other of multiple boundary have the same boundary id.

fix: Only write boundary surface associated to curent volume

---

Core/include/Acts/Propagator/EigenStepper.hpp
Core/include/Acts/Propagator/EigenStepper.ipp
Core/include/Acts/Propagator/StraightLineStepper.hpp
Core/include/Acts/Propagator/detail/CovarianceEngine.hpp
Core/include/Acts/Surfaces/DiscSurface.hpp
Core/include/Acts/Surfaces/LineSurface.hpp
Core/include/Acts/Surfaces/Surface.hpp
Core/include/Acts/Surfaces/detail/ConeSurface.ipp
Core/include/Acts/Surfaces/detail/CylinderSurface.ipp
Core/include/Acts/Surfaces/detail/DiscSurface.ipp
Core/include/Acts/Surfaces/detail/LineSurface.ipp
Core/include/Acts/Surfaces/detail/Surface.ipp
Core/src/Propagator/StraightLineStepper.cpp
Core/src/Propagator/detail/CovarianceEngine.cpp
Core/src/Surfaces/Surface.cpp

BREAKING CHANGE: This PR simplifies the calculation within the `covarianceTransport` by changing the `surfaceDerivative` method to `localToLocalJacobian` which packs up the calculation for the full jacobian from local parameters at start surface to local parameters at the final surface. Among the `localToLocalJacobian` input parameters, only the `jacFull` is updated. Reinitializations of other jacobians are done separately within the `covarianceTransport`. In this way, how different jacobians are updated with each `covarianceTransport` is more clear.
This PR also packs the global `position` and `direction` to a `FreeVector` as the input parameter of `initJacobianToLocal` and `initJacobianToGlobal`. This could make the interfaces for jacobian/derivative calculation more consistent.

refactor!: Simplify interface for jacobian between local and global parameters

---

Core/include/Acts/EventData/Charge.hpp
Core/include/Acts/EventData/SingleBoundTrackParameters.hpp
Core/include/Acts/EventData/SingleCurvilinearTrackParameters.hpp
Core/include/Acts/EventData/SingleFreeTrackParameters.hpp
Core/include/Acts/EventData/TrackParametersConcept.hpp

BREAKING CHANGE: Bound track parameters loose the `.getParameterSet()` accessor.
Implements all track parameters types without `ParameterSet` using the appropriate vector/matrix types directly. The track parameters concepts are updated such that the `.parameters()` and `.covariance()` return types only need to be convertible to the expected plain vector/matrix types.
These changes prepare for the eventual removal of the `ParameterSet` infrastructure as part of the EDM rework.
Contains changes from #553 and must be merged afterwards.

refactor!: Implement track parameters without ParameterSet (EDM rework 4b/4)

---

Core/include/Acts/Surfaces/AnnulusBounds.hpp
Core/include/Acts/Surfaces/DiscTrapezoidBounds.hpp
Core/src/Surfaces/AnnulusBounds.cpp
Core/src/Surfaces/DiscTrapezoidBounds.cpp
Fatras/CMakeLists.txt
Fatras/include/ActsFatras/Digitization/Channelizer.hpp
Fatras/include/ActsFatras/Digitization/DigitizationError.hpp
Fatras/include/ActsFatras/Digitization/PlanarSurfaceMask.hpp
Fatras/include/ActsFatras/Digitization/UncorrelatedHitSmearer.hpp
Fatras/src/Digitization/Channelizer.cpp
Fatras/src/Digitization/DigitizationError.cpp
Fatras/src/Digitization/PlanarSurfaceMask.cpp
Tests/UnitTests/Core/Surfaces/DiscTrapezoidBoundsTests.cpp
Tests/UnitTests/Fatras/Digitization/BoundRandomValues.hpp
Tests/UnitTests/Fatras/Digitization/CMakeLists.txt
Tests/UnitTests/Fatras/Digitization/ChannelizerTests.cpp
Tests/UnitTests/Fatras/Digitization/DigitizationCsvOutput.hpp
Tests/UnitTests/Fatras/Digitization/PlanarSurfaceMaskTests.cpp
Tests/UnitTests/Fatras/Digitization/PlanarSurfaceTestBeds.hpp

This PR is the second step of the new Digitisation.
It introduces the `SurfaceMasker` that is run before the `Channelizer` which was introduced in part 1.
The `PlanarSurfaceMasker` clips/masks a segment onto the surface (= readout) bounds.
Additionally, it harmonizes the input/output between Channelized / Masker.
It also reorders the PlanarSurface testbeds to be used for `ChannelizerTest` and `PlanarSurfaceMaskTest`.
* `RectangleBounds`
- green : inside from the the start (untouched)
- blue: clipped
* `TrapezoidBounds`
* `RadialBounds`
- ref: segment fully outside

feat: Digitization 2, introduce SurfaceMasker

---

Examples/Io/HepMC3/include/ActsExamples/Io/HepMC3/HepMC3Event.hpp
Examples/Io/HepMC3/include/ActsExamples/Io/HepMC3/HepMC3Particle.hpp
Examples/Io/HepMC3/include/ActsExamples/Io/HepMC3/HepMC3Vertex.hpp
Examples/Io/HepMC3/src/HepMC3Event.cpp
Examples/Io/HepMC3/src/HepMC3Particle.cpp
Examples/Io/HepMC3/src/HepMC3Reader.cpp
Examples/Io/HepMC3/src/HepMC3Vertex.cpp
Examples/Run/HepMC3/HepMC3Example.cpp

This PR changes the stateless HepMC3 converter structs to become namespaces instead.

refactor: HepMC3 converter as namespace instead of struct

---

Core/include/Acts/Surfaces/SurfaceArray.hpp

This is a backport of #556 with the HepMC3 changes removed
This showed up we believe after GitHub Actions bumped to AppleClang 12.

fix: Warning about unneeded ref in ranged for loop

---

Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.hpp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.ipp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFitter.ipp
Core/include/Acts/Vertexing/HelicalTrackLinearizer.ipp
Core/include/Acts/Vertexing/TrackAtVertex.hpp

These changes fix the issues we've seen when employing the ACTS AMVF on data in Athena, targeting an ACTS v1.2.1 bug fix release. Changes made:
- In case the algorithm finds a bad vertex and deletes it at some point again, I need to force it to relinearize the tracks in the next iteration since they were linearized with respect to the bad vertex.
- If the seed constraint is turned off, the old (e.g. beamspot) constraint will now be correctly applied.
- For consistency reasons with Athena, a negative determinant check in the track linearizer is added.
The corresponding master PR [can be found here](https://github.com/acts-project/acts/pull/550).

fix: AMVF track linearization and seed constraint fix for q431 test (backport)

---

Tests/UnitTests/Core/Vertexing/ImpactPointEstimatorTests.cpp

This is a clean up/ rewrite of the `ImpactPointEstimator` tests in order to understand and fix the problem discussed in #455. The iteration over multiple tracks is now handled via data-driven tests, common code has been moved into helper functions, and the multi track compatibility test has been removed.
The issue discussed in #455 happens in the multi track compatibility test: The vertex distance and compatibility score (chi2) for multiple (random) tracks is calculated. For all possible track combinations the (relative) difference in real distance and in compatibility score was computed. The test then checked that both differences have the same sign. This is equivalent to testing that a track w/ a smaller real distance to the vertex also has a smaller score. This was the test that failed …

refactor: Clean up ImpactPointEstimator tests

---

Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.hpp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.ipp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFitter.ipp
Core/include/Acts/Vertexing/HelicalTrackLinearizer.ipp
Core/include/Acts/Vertexing/TrackAtVertex.hpp

This PR targets master and fixes the remaining issue we see in the q431 job in the CI of [this Athena MR](https://gitlab.cern.ch/atlas/athena/-/merge_requests/37283) where in one single event 17 jets (ACTS AMVF enabled) are reconstructed instead of 15 jets (Athena AMVF enabled):
- In case the algorithm finds a bad vertex and deletes it at some point again, I need to force it to relinearize the tracks in the next iteration since they were linearized with respect to the bad vertex. 
- If the seed constraint is turned off, the old (e.g. beamspot) constraint will now be correctly applied.
- For consistency reasons with Athena, a negative determinant check in the track linearizer is added.
The corresponding backport PR for a bug fix release v.1.2.1 [can be found …

fix: AMVF track linearization and seed constraint fix for q431 test (master)

---

Core/include/Acts/TrackFitting/GainMatrixSmoother.hpp
Core/include/Acts/TrackFitting/GainMatrixUpdater.hpp

Includes the following changes:
- Removal of unused includes and adding of missing ones.
- Update of the documentation to match the code.
- Removal of unnecessary `std::optional` use.
- Apply naming guidelines.
- Reduce indenting by adding early exits where possible.

refactor: Clean up gain matrix smoother/updater

---

Core/include/Acts/Propagator/AtlasStepper.hpp

This PR changes the triple-call to `std::hypot`, a clever compiler may fix that for you but it did reduce the call number in my tests.

feat: simple speed improvement AtlasStepper

---

Examples/Algorithms/Propagation/include/ActsExamples/Propagation/PropagationAlgorithm.hpp
Examples/Algorithms/Propagation/include/ActsExamples/Propagation/PropagationAlgorithm.ipp
Examples/Algorithms/Propagation/include/ActsExamples/Propagation/PropagationOptions.hpp

The loop protection for the ActsExamples was set to a 0.3 GeV threshold, but this left the chance for some loopers to still exist.
This PR sets the default higher, but at the same time properly catches & checks the `Result` object of the `propagate(...)` call.
Addresses #581.

fix: Avoid Loopers in ActsExamples

---

Core/include/Acts/Vertexing/AdaptiveMultiVertexFitter.ipp
Core/include/Acts/Vertexing/KalmanVertexTrackUpdater.ipp

This PR fixes a last issue that was seen when running on data events in Athena, where the linearization point needs only to be updated in certain cases (i.e. not if the track is not linearized).
Also a small track weight cut is applied for the vertex smoothing.
Both changes have only a very small impact on the AMVF outcome, but are still needed for it to function properly.

fix: Fix linearization point updates in AMVFitter

---

Plugins/Autodiff/include/Acts/Plugins/Autodiff/AutodiffExtensionWrapper.hpp
thirdparty/README.md
thirdparty/autodiff/autodiff/common/meta.hpp
thirdparty/autodiff/autodiff/forward/forward.hpp
thirdparty/autodiff/autodiff/reverse/reverse.hpp

This PR updates the Autodiff-Plugin, since it is dependent on the internal data layout of the `StepperState`, which was changed in PR #569.
PS: I'm not sure how this works internally, but shouldn't such things be catched by the CI? Or does this not apply for Plugins?

fix: Resolve compile errors of Autodiff Plugin caused by PR  #569

---

CMakeLists.txt
cmake/ActsConfig.cmake.in

Previously we didn't correctly propagate our autodiff dependency in case the autodiff plugin was enabled. This PR adds this to the generated ACTS config, so that it's picked up from a downstream project.
/cc @benjaminhuth

fix: Propagate autodiff dependency to installed config

---

Examples/Run/Common/src/GeometryExampleBase.cpp
Examples/Run/Common/src/MaterialMappingBase.cpp
Examples/Run/Common/src/MaterialValidationBase.cpp
Plugins/Json/include/Acts/Plugins/Json/JsonGeometryConverter.hpp
Plugins/Json/src/JsonGeometryConverter.cpp

Added the geometry context as one of the config augment for the json geometry converter. The geometry and material mapping example have been updated to use the context. It don't think anything like a "nominal context" exist so for now the geometry context of event 0.
This resolve Issue #488.

fix: Geometry context in Json converter

---

.github/workflows/builds.yml

We need to fetch dependencies from https://acts.web.cern.ch/ci/macOS/ rather than the old https://acts.web.cern.ch/ACTS/ci/macOS.
This PR changes the URL.
See #602 and #507 where we see the macOS CI failing.
/cc @asalzburger @irinaene

ci: CERN public website URL has changed

---

Core/include/Acts/Vertexing/AdaptiveGridDensityVertexFinder.hpp
Core/include/Acts/Vertexing/AdaptiveGridDensityVertexFinder.ipp
Core/include/Acts/Vertexing/AdaptiveGridTrackDensity.hpp
Core/include/Acts/Vertexing/AdaptiveGridTrackDensity.ipp
Core/include/Acts/Vertexing/GaussianGridTrackDensity.ipp
Tests/UnitTests/Core/Vertexing/AdaptiveGridTrackDensityTests.cpp
Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFinderTests.cpp
Tests/UnitTests/Core/Vertexing/CMakeLists.txt
Tests/UnitTests/Core/Vertexing/GridDensityVertexFinderTests.cpp

This PR introduces a new vertex seed finder that is based on the existing Grid density seed finder, however, it's an adaptive version that allows the track density grid to grow bigger dynamically over time as new tracks are added to the seed finder.
This should consume much less memory as no e.g. 10.000-dim density vector is required (that is potentially quite empty) and the vector just grows over time.
Having three different versions of a Gaussian seed finder in place now, I will soon open an issue to check if we can potentially combine these seed finders to a single finder in the future, that just uses different track density implementations in the background (continuous density, grid density, adaptive grid density).

feat: Introduce Adaptive gaussian track density vertex seed finder

---

.github/workflows/builds.yml

Set `CMAKE_CXX_STANDARD=17` explicitely for the macOS CI build.
The DD4hep CMake configurations seems to be buggy (surprise). It seems to require that the `CMAKE_CXX_STANDARD` options is set to a definite value, but this only gets triggered on recent CMake versions. The current CMake version installed via homebrew seems to do just that.

ci: fix macOS build failures due to DD4hep CMake

---

Tests/Benchmarks/SolenoidFieldBenchmark.cpp

It seems I never opened a PR for this.
This PR adds a few benchmark scenarios that cover advancing along a straight line in a B-Field, with and without caches.
The results I got are something like this:

test: Add more B-Field benchmark scenarios

---

.github/workflows/builds.yml
CI/check_format_local
CMakeLists.txt
Core/include/Acts/Vertexing/AdaptiveGridTrackDensity.ipp
Examples/Framework/CMakeLists.txt
cmake/FindTBB.cmake

Replace the LCG 95apython3 and 96 CI builds with new ones based on LCG 97apython3 and LCG 98python3 container images. That also means that all CI builds should have a recent Python 3 version available (because, you know, its 2020). According to [lcginfo](http://lcginfo.cern.ch/) there already exists an patch release LCG 98apython3 but that one does not seem to be available as RPMs and can not be used in our self-contained container images yet.
The DD4hep version provided by LCG 98 now requires TBB. The DD4hep CMake configuration seems to use a config-only `find_package(TBB CONFIG)` call internally. To avoid library missmatches TBB is searched for twice, once in config-only mode and once in module-only. This should ensure that consistent versions are found. The `FindTBB` CMake module is …

ci: Use LCG 97 and 98 for CI builds

---

.github/workflows/builds.yml

This got accidentally disabled when the plugin option names where changed.

ci: Re-enable CUDA plugin in the CUDA CI job

---

Core/include/Acts/Vertexing/IterativeVertexFinder.ipp

Hi @baschlag and @asalzburger, Sorry I accidentally closed the last pull request while making some changes. Creating this new request. @baschlag, yes the addition of this break statement is the only change that I have done in ACTS code. The matrix inversion that I talked about earlier was in Athena. 
Please comment!

fix: Iterative Vertex Finder algorithm updated for seed vertex at z = 0

---

.github/workflows/analysis.yml
.github/workflows/builds.yml
.github/workflows/checks.yml

Closes #642
@msmk0 I checked, but it appears it's not possible to use env vars in the expression for the container URL. So I guess we'll have to stick to hard-coding the version.

ci: Bump Image versions to v9

---

Examples/Run/Common/src/GeometryExampleBase.cpp
Examples/Run/Fatras/Common/FatrasDigitization.cpp
Plugins/Json/include/Acts/Plugins/Json/JsonGeometryConverter.hpp
Plugins/Json/src/JsonGeometryConverter.cpp
Tests/Data/material-map.json

This PR has two small fixes:
- in Core, it fixes a spelling mistake and naming mash-up (@Corentin-Allaire)
- in Examples, it fixes the GenericFatrasExample as it was broken due to the Options change (@msmk0)

fix: make generic examples work again

---

Fatras/CMakeLists.txt
Fatras/include/ActsFatras/Digitization/PlanarSurfaceDrift.hpp
Fatras/src/Digitization/PlanarSurfaceDrift.cpp
Tests/UnitTests/Fatras/Digitization/CMakeLists.txt
Tests/UnitTests/Fatras/Digitization/PlanarSurfaceDriftTests.cpp

This PR splits out the addition of the surface merger to the `Fatras/Digitzation` module. 
The `PlanarSurfaceDrift` struct allows to project an intersection segment to a readout surface,
it is tested in a new `UnitTest`.

feat: introduce surface drift 

---

Core/include/Acts/Utilities/BinUtility.hpp
Core/include/Acts/Utilities/BinningData.hpp
Plugins/Json/CMakeLists.txt
Plugins/Json/include/Acts/Plugins/Json/AlgebraJsonConverter.hpp
Plugins/Json/include/Acts/Plugins/Json/UtilitiesJsonConverter.hpp
Plugins/Json/src/AlgebraJsonConverter.cpp
Plugins/Json/src/UtilitiesJsonConverter.cpp
Tests/UnitTests/Plugins/Json/AlgebraJsonConverterTests.cpp
Tests/UnitTests/Plugins/Json/CMakeLists.txt
Tests/UnitTests/Plugins/Json/UtilitiesJsonConverterTests.cpp

This PR introduces the first modules of the updated `Json` converters that use the `nlohmann::json::to_json/from_json`  interface.

feat: streamline json plugin

---

Core/include/Acts/Utilities/BinUtility.hpp
Core/include/Acts/Utilities/BinnedArray.hpp
Core/include/Acts/Utilities/BinnedArrayXD.hpp
Core/include/Acts/Utilities/BinningData.hpp
Tests/Benchmarks/BinUtilityBenchmark.cpp
Tests/Benchmarks/CMakeLists.txt
Tests/UnitTests/Core/Utilities/BinUtilityTests.cpp
Tests/UnitTests/Core/Utilities/BinningDataTests.cpp

This PR cleans the `BinUtility` and  `BinningData` objects:
- removes dead code
- removes hand-written search in vector in favour of `std::lower_bound`
It adds/removes relevant `UnitTests` and adds a new benchmark test, the benchmark before the changes shows:
```shell
16:36:17    BinUtility     INFO      Execution stats small: 1000 runs of 1 iteration(s), 0.0ms total, 0.0430+/-0.0001µs per run, 43.000+/-0.058ns per iteration
16:36:17    BinUtility     INFO      Fraction is: 21968011 vs. 21968011
16:36:19    BinUtility     INFO      Execution stats medium: 1000 runs of 1 iteration(s), 0.1ms total, 0.0510+/-0.0003µs per run, 51.000+/-0.346ns per iteration
16:36:19    BinUtility     INFO      Fraction is: 19641811 vs. 19641811
16:36:21    BinUtility     INFO      Execution stats many: 1000 …
```

feat: optimise BinningData, remove dead code

---

docs/requirements.txt

Attempt to fix the doc build by locking down breathe to `4.26.0`.

docs: Lock down breathe to 4.26.0

---

Core/include/Acts/Surfaces/SurfaceBounds.hpp
Plugins/Json/CMakeLists.txt
Plugins/Json/include/Acts/Plugins/Json/SurfaceBoundsJsonConverter.hpp
Plugins/Json/src/SurfaceBoundsJsonConverter.cpp
Plugins/Json/src/UtilitiesJsonConverter.cpp
Tests/UnitTests/Plugins/Json/AlgebraJsonConverterTests.cpp
Tests/UnitTests/Plugins/Json/CMakeLists.txt
Tests/UnitTests/Plugins/Json/SurfaceBoundsJsonConverterTests.cpp
Tests/UnitTests/Plugins/Json/UtilitiesJsonConverterTests.cpp

This PR includes the next `Json` converter, this time for `SurfaceBounds`.
All `SurfaceBounds` have a `values()` streaming method (providing a `std::vector`) and a constructor by providing a `std::array`. Hence, only one converter is needed, however, the type has to be given explicitely, no automated conversion is possible, as the `Surface` objects never swallow `SurfaceBounds` directly but a class extension of the appropriate type.
UnitTest for one is attached, no need to call the same functions on all inherited objects.

feat: introduce Json converter for SurfaceBounds

---

Examples/Framework/src/Framework/Sequencer.cpp

Previously this printed every event, which can pretty much saturate stdout. The old behavior is kept for total event range size up to 100 events

feat: Sequencer only prints out event progress every 100 events

---

Examples/Detectors/MagneticField/src/BFieldOptions.cpp

The B field options are added by the Payload Detector and the propagation example base. This prevents the options from working. This PR adds a check that skips option creation after the first time to fix this.

fix: Prevent B field options from being added multiple times

---

Examples/Detectors/ContextualDetector/src/PayloadDecorator.cpp

The payload decorator was set up to ONLY populate the context at IOV boundaries. This leads to any cast exceptions. This PR changes this to populate the context always, and adds an assertion.
@asalzburger: How to I verify that the alignment in the context is correct? Do I just look at the prop steps or is there an automated way?

fix: PayloadDecorator doesn't always populate the context

---

.github/workflows/builds.yml

Currently, the macOS CI job spends a considerable amount of time cleanup
up the homebrew install, which is pointless because it's erased at the
end of the job anyway. Adding an environment variable, this can be
disabled.

ci: Do not run automatic homebrew cleanup on install

---

Tests/UnitTests/Core/Propagator/AtlasStepperTests.cpp

Last September, #443 accidentally introduced a nonsensical operation in the AtlasStepperTests during a refactoring (compute bound parameters with a position which is not on the surface of interest). This happened because @msmk0 was understandably misled by a set of local and global variables with identical names and unrelated contents, with the local variables shadowing the global ones.
This nonsensical operation was not caught by the unit tests because passing an invalid position to the BoundParameters constructors only leads to the emission of a FATAL log, and not to any stronger error reporting like throwing an exception (returning a Result would not be possible here as this happens inside of a class constructor).
However, the FATAL log was caught by #687, so in the interest of …

fix: Fix confusion between shadowed variables in the AtlasStepperTests

---

Plugins/Json/include/Acts/Plugins/Json/MaterialMapJsonConverter.hpp
Plugins/Json/src/MaterialMapJsonConverter.cpp
Tests/UnitTests/Plugins/Json/MaterialMapJsonConverterTests.cpp

When the material map and tracking geometry where written to file they were not using ordered_json due to an oversight (the ordered_json had been converted to json before being written). This fix this issue so that the key appear in proper order in the files.

fix: use of ordered_json

---

Fatras/CMakeLists.txt
Fatras/include/ActsFatras/EventData/ProcessType.hpp
Fatras/include/ActsFatras/Physics/EnergyLoss/BetheHeitler.hpp
Fatras/src/Physics/EnergyLoss/BetheHeitler.cpp
Tests/UnitTests/Fatras/Physics/EnergyLossTests.cpp

The current implementation of the Bethe-Heitler process just reduces the particles energy. This PR adds the corresponding emission of a photon and adapts the angle of the radiating particle accordingly.

fix: Bethe-Heitler photon emission

---

CI/run_examples.sh
docs/howto/run_material_mapping.rst

While full material mapping CI will wait for #733 to be fixed, starting to follow the material mapping tutorial in search for new example configurations already gave me some ideas for the geometry examples and the Geantino example.
**EDIT:** Oh, and while spending too much time looking at the examples' help strings, I also found a typo in the option for controlling material output for sensitive surfaces: it is "--mat-output-sensitive**s**", and not "--mat-output-sensitive".
**EDIT:** Synchronized Geantino example configuration too.

ci: Run geometry and Geantino examples as in the material mapping tutorial

---

CI/run_examples.sh
docs/howto/run_fatras.rst
docs/howto/run_material_mapping.rst

PR #685 accidentally invalidated the Fatras tutorial's particle generation CLI examples. This fixes that, and uses the offending command line in our CI of the corresponding examples, which benefits both the docs (they won't accidentally get out of date anymore) and the examples CI (it tests evgen in a slightly more elaborate/realistic configuration).
**EDIT:** While I was at it, I also fixed the `--output-xyz` options of the material mapping tutorial in the same manner.

fix: Fix particle generation docs commands and add them to CI

---

Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp
Core/include/Acts/TrackFitting/KalmanFitter.hpp

This PR changes the `inputMeasurements` in (C)KF actor to use pointer. This could save the data copy time vastly.

refactor: Use pointer for (C)KF inputMeasurements

---

Examples/Algorithms/Propagation/include/ActsExamples/Propagation/PropagationAlgorithm.hpp
Examples/Algorithms/Propagation/include/ActsExamples/Propagation/PropagationAlgorithm.ipp
Examples/Run/Common/src/PropagationExampleBase.cpp

This PR switches the SteppingLogger to `sterile` when no persistent output is requested in the `PropgationExample`. This aides the time measurement of the propagation, as otherwise the `getSharedPtr(...)` within the logger is a signficant factor.

feat: Switching SteppingLogger to sterile when no output requested

---

CMakeLists.txt

Since #686 , we bundle nlohman-json v3.9.1 and use the ordered_json feature that received many bugfixes in that release. Therefore, I think we should bump our external nlohman-json version requirement accordingly.

fix: Sync up nlohman-json version requirement

---

Examples/Io/NuclearInteractions/src/RootNuclearInteractionParametersWriter.cpp
Examples/Io/NuclearInteractions/src/detail/NuclearInteractionParametrisation.cpp

This PR fixes the construction of the parametrisation by fixing the indices and the construction of a CDF.
Occasionally the writing of the parametrisation was not performed. This PR fixes this issue.

fix: NuclearInteractionParametrisationWriter fixes

---

Examples/Algorithms/Propagation/include/ActsExamples/Propagation/PropagationAlgorithm.ipp
Examples/Detectors/ContextualDetector/include/ActsExamples/ContextualDetector/AlignedDetectorElement.hpp
Examples/Detectors/ContextualDetector/include/ActsExamples/ContextualDetector/AlignmentDecorator.hpp
Examples/Detectors/ContextualDetector/src/AlignmentDecorator.cpp

This PR changes the demonstrator for the AlignmentDetector to a map in order not to overwrite accidentally prior IOV transforms.
Obviously this is not the most performant contextual data approach on the client side.

fix: change Alignment store to map in Examples

---

Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvTrackingGeometryWriter.hpp
Examples/Io/Csv/src/CsvOutputData.hpp
Examples/Io/Csv/src/CsvTrackingGeometryWriter.cpp

This PR adds a new CVS writer component to be able to write out the Detector surfaces for navigation inspection.

feat: csv surface grid writer

---

Core/include/Acts/EventData/SingleBoundTrackParameters.hpp
Core/include/Acts/EventData/SingleFreeTrackParameters.hpp

In order to make compilers happier, and enable compilation for GPUs via hipSYCL, the `charge()` method of SingleBountTrackParameters and SingleFreeTrackParameters should not be marked constexpr, as the called method `get()` is not constexpr.
see https://github.com/acts-project/acts/issues/757

refactor: remove constexpr from charge method

---

Core/include/Acts/Propagator/EigenStepper.ipp
Tests/UnitTests/Core/Propagator/StepperTests.cpp

The `EigenStepper` will either keep the step size or reduce it. This depends on the error of the numerical integration. A step accepted if the error is below the tolerance. Calculating the next step size according to ATL-SOFT-PUB-2009-001 Eqs. (6) and (7), the next step size can be estimated to be larger or equal to the accepted one. Therewith the next step could be larger (potentially) reducing the required amount of steps.
The changes were tested using the ATLAS magnetic field, the GenericDetector, 100k events with 100 events per p_T configuration. It was found that this additional scaling leads to step size adjustments (due to energy loss & magnetic field fluctuations). Without the transport of covariance matrices the propagation tend to take longer than the current implementation. …

perf: EigenStepper step size adjustment

---

Examples/Algorithms/Digitization/src/DigitizationAlgorithm.cpp
Examples/Detectors/TGeoDetector/src/TGeoDetector.cpp
Examples/Io/Json/src/JsonDigitizationConfig.cpp
Examples/Run/Digitization/CMakeLists.txt
Examples/Run/Digitization/Common/CMakeLists.txt
Examples/Run/Digitization/Common/DigitizationConfigExample.cpp
Examples/Run/Digitization/Common/DigitizationConfigExample.hpp
Examples/Run/Digitization/Common/detail/DigitizationConfigurator.hpp
Examples/Run/Digitization/TGeoDigitizationConfigExample.cpp

This PR adds a configuration generator for digitisation that allows from a very simplified input to create a full fledged digitisation file.
```json
{
"acts-geometry-hierarchy-map": {
"format-version": 0,
"value-identifier": "digitization-configuration"
},
"entries": [{
"volume": 9,
"value": {
"geometric": {
"digital": false,
"indices": [
0,
1
],
"segmentation": {
"binningdata": [{
"bins": 1,
"max": 0.05,
"min": 0.00,
"option": "open",
"type": "equidistant",
"value": "binX"
},
{
"bins": 1,
"max": 0.05,
"min": 0.0,
"option": "open",
"type": "equidistant",
"value": "binY"
}
]
},
"thickness": 0.15,
"threshold": 0.01
}
}
}]
}
```
It will then produce a json file with filled in parameters:
```json
{
"volume": 9,
"layer": 2,
"sensitive": 2,
"value": {
"geometric": {
"digital": false,
"indices": …
```

feat: add digitisation configuration example 

---

Core/include/Acts/Vertexing/HelicalTrackLinearizer.ipp

I replaced  maxRho with sgnH*maxRho (case of B=0, straight tracks) in the HelicalTrackLinearizer, since generally the curvature is signed.
In my case (vertex fitting with straight tracks), the missing sign of maxRho resulted into negative diagonal covariance matrix entries of the vertex fit for negatively charged particles.

fix: added sgnH to maxRho in HelicalTrackLinearizer.

---

Core/include/Acts/Material/SurfaceMaterialMapper.hpp
Core/include/Acts/Propagator/detail/PointwiseMaterialInteraction.hpp
Core/src/Geometry/TrackingVolume.cpp
Core/src/Material/SurfaceMaterialMapper.cpp
Examples/Algorithms/Geant4/src/SteppingAction.cpp
Examples/Algorithms/Propagation/include/ActsExamples/Propagation/PropagationOptions.hpp
Examples/Detectors/DD4hepDetector/src/TestTracker/ZPlanarTracker_geo.cpp
Examples/Io/Root/include/ActsExamples/Io/Root/RootMaterialWriter.hpp
Examples/Io/Root/src/RootMaterialTrackWriter.cpp
Examples/Run/Common/src/MaterialMappingBase.cpp
Examples/Run/Common/src/PropagationExampleBase.cpp
Examples/Scripts/propagation_timing.sh
Plugins/DD4hep/src/DD4hepLayerBuilder.cpp
Plugins/Json/src/MaterialMapJsonConverter.cpp
thirdparty/OpenDataDetector/factory/ODDPixelBarrel_geo.cpp
thirdparty/OpenDataDetector/factory/ODDPixelEndcap_geo.cpp
thirdparty/OpenDataDetector/factory/ODDStripBarrel_geo.cpp
thirdparty/OpenDataDetector/factory/ODDStripEndcap_geo.cpp

This PR fixes a few things in the material mapping and DD4Hep description:
* ODD has now by-hand-envelopes (fixes navigation issues), copy and repo is updated
* Pre/Post step of material user action was wrongly calculated 
* Naming convention is fixed in `HierachySurface...` and `HierarchyVolume...`
Still an issue of not being able to map onto the last boundary surfaces:

feat:  material mapping fixes odd

---

CI/run_examples.sh
Examples/Algorithms/Generators/ActsExamples/Generators/ParametricParticleGenerator.cpp
Examples/Algorithms/Generators/ActsExamples/Generators/ParametricParticleGenerator.hpp
Examples/Algorithms/Generators/ActsExamples/Options/ParticleGunOptions.cpp
Examples/Scripts/KF_timing.sh
docs/howto/run_fatras.rst

This PR is super minimal and enables to generate constant PT particles for validation.
Validation screenshot below:

feat: enable option for transverse momentum in Examples

---

Plugins/Json/src/MaterialMapJsonConverter.cpp

With this PR when converting a tracking geometry to a Hierarchy the volume that have already been added to the hierarchy won't be added a second time. This solve the issue that if a volume belong to multiple volumes (as it is the case for the Calorimeter in the Acts ATLAS implementation) the code would result in an error (since hierarchy can only have each identifier appear once)

fix: Write surface only once in the MaterialMapJsonConverter

---

Core/include/Acts/Seeding/SpacePointGrid.ipp

For no magnetic field or pseudorapidity == 0, the SpacePointGrid now creates 100 phi bins respectively 100 z bins instead of crashing

fix: division by 0 in SpacePointGrid

---

Examples/Framework/include/ActsExamples/Framework/Sequencer.hpp
Examples/Framework/src/Framework/Sequencer.cpp
Examples/Run/Common/src/GeometryExampleBase.cpp
Examples/Run/MagneticField/BFieldAccessExample.cpp

Previously, `SIZE_MAX` was used to indicate that the full available end range of an input file was to be used. This caused issues when no input file was present (for example in the geometry examples) and `--events` was not given., since it would run `SIZE_MAX` events (see #707). 
This PR changes this to use `std::optional<size_t>`, so that the default is clearly communicated. The geometry example should now default to `1` if `--events` isn't supplied.
Fixes #707

refactor: Use std::optional for event range end requested

---

.github/workflows/builds.yml

Fixes one replacement of `master` to `main` that we missed.

ci: Run build jobs on main branch

---

.github/workflows/builds.yml

Pip changed it's dependency resolution algorithm a while ago. The job used an older version of pip which installed an inconsistent set of dependencies with a dependency update over the weekend. The job now updates pip first to get the new resolution behavior, which should fix the issue.

ci: Fix doxygen doc job

---

Core/include/Acts/Seeding/EstimateTrackParamsFromSeed.hpp
Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/TrackParamsEstimationAlgorithm.hpp
Examples/Algorithms/TrackFinding/src/TrackParamsEstimationAlgorithm.cpp
Examples/Io/Performance/ActsExamples/Io/Performance/CKFPerformanceWriter.cpp
Examples/Run/Reconstruction/Common/RecCKFTracks.cpp
Examples/Run/Reconstruction/Common/RecTruthTracks.cpp

This PR fixes a few selections during the reconstruction and performance writing, including the truth seed selection (selecting the truth seed with maximum deltaR between bottom and top space point), truth particle selection and reconstructed tracks selection.

fix: reco selection criteria

---

CI/headwind.yml

As I was saying, CI is fiddly.
The target path for the metric storage is wrong I think. I think this should fix it.

ci: Fix metric generation path

---

Core/include/Acts/Propagator/AtlasStepper.hpp
Core/include/Acts/Propagator/EigenStepper.hpp
Core/include/Acts/Propagator/Navigator.hpp
Examples/Algorithms/Geant4/include/ActsExamples/Geant4/Geant4Options.hpp
Examples/Algorithms/Propagation/include/ActsExamples/Propagation/PropagationAlgorithm.hpp
Examples/Algorithms/Propagation/include/ActsExamples/Propagation/PropagationOptions.hpp
Examples/Detectors/EmptyDetector/include/ActsExamples/EmptyDetector/EmptyDetectorOptions.hpp
Examples/Io/Performance/ActsExamples/Io/Performance/CKFPerformanceWriter.hpp
Examples/Run/Geant4/GeantinoRecordingBase.hpp
Examples/Run/Reconstruction/Common/RecInput.cpp
Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoLayerBuilder.hpp
Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoParser.hpp
Tests/UnitTests/Core/Visualization/EventDataView3DBase.hpp
Tests/UnitTests/Plugins/TGeo/TGeoLayerBuilderTests.cpp

We got a bit lenient with not doing 
```cpp
using namespace Acts::UnitLiterals;
```
in header code. This is a bad idea, because it pollutes the global namespace in every compilation unit such a header is included in. As a workaround, you can put `using namespace` in any functions where the literals are needed.
This PR removes all of these cases, and also removes a few other instances of `using namespace` in headers.

refactor: Remove usage of using namespace in headers

---

Core/include/Acts/MagneticField/ConstantBField.hpp
Core/include/Acts/MagneticField/InterpolatedBFieldMap.hpp
Core/include/Acts/MagneticField/MagneticFieldProvider.hpp
Core/include/Acts/MagneticField/NullBField.hpp
Core/include/Acts/MagneticField/SharedBField.hpp
Core/include/Acts/MagneticField/SolenoidBField.hpp
Core/src/MagneticField/SolenoidBField.cpp
Examples/Algorithms/TrackFinding/src/TrackParamsEstimationAlgorithm.cpp
Examples/Detectors/MagneticField/include/ActsExamples/MagneticField/ScalableBField.hpp
Examples/Io/Root/include/ActsExamples/Io/Root/RootBFieldWriter.hpp
Examples/Run/MagneticField/BFieldAccessExample.cpp
Examples/Run/MagneticField/CMakeLists.txt
Tests/Benchmarks/AtlasStepperBenchmark.cpp
Tests/Benchmarks/EigenStepperBenchmark.cpp
Tests/IntegrationTests/Fatras/FatrasSimulationTests.cpp
Tests/IntegrationTests/InterpolatedSolenoidBFieldTest.cpp
Tests/UnitTests/Core/MagneticField/ConstantBFieldTests.cpp
Tests/UnitTests/Core/Propagator/DirectNavigatorTests.cpp
Tests/UnitTests/Core/Propagator/ExtrapolatorTests.cpp
Tests/UnitTests/Core/Propagator/LoopProtectionTests.cpp
Tests/UnitTests/Core/Propagator/MaterialCollectionTests.cpp
Tests/UnitTests/Core/Propagator/PropagatorTests.cpp
Tests/UnitTests/Core/Propagator/StepperTests.cpp
Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFitterTests.cpp
Tests/UnitTests/Core/Vertexing/FullBilloirVertexFitterTests.cpp
Tests/UnitTests/Core/Vertexing/IterativeVertexFinderTests.cpp
Tests/UnitTests/Core/Vertexing/KalmanVertexTrackUpdaterTests.cpp
Tests/UnitTests/Core/Vertexing/KalmanVertexUpdaterTests.cpp
Tests/UnitTests/Core/Vertexing/LinearizedTrackFactoryTests.cpp
Tests/UnitTests/Core/Vertexing/ZScanVertexFinderTests.cpp

This PR removes the overloads of `getField` and `getFieldGradient` from `Acts::MagneticFieldProvider`. The individual field provider can still implement such overloads, but aren't forced to anymore by the provider. This only requires a few changes, but one is that it effectively renders `BFieldAccessExample` void of functionality, other than being a literal example of how to use the provider.
Closes #782
BREAKING CHANGE: `Acts::MagneticFieldProvider` loses the following pure virtual overloads:
```cpp
virtual Vector3 getField(const Vector3& position) const = 0; 
virtual Vector3 getFieldGradient(const Vector3& position, ActsMatrix<3, 3>& derivative) const = 0;
```
Clients of generic magnetic field providers need to be adapted.

refactor!: Remove overloads of B field retrieval without cache

---

Plugins/DD4hep/src/DD4hepLayerBuilder.cpp

- Not sure why it is needed but the ProtoLayer construction does not set the values.
See the [discussion here](https://github.com/acts-project/acts/issues/822)

fix: Added missing radial extent

---

Core/src/Geometry/CylinderVolumeBuilder.cpp

A problem that only occurs on the positive endcap despite being
a mirror of the negative endcap.
Here is the output of the dd4hep plugin in verbose mode:
[output.txt](https://github.com/acts-project/acts/files/6565645/output.txt)
Here is the output after the changes:
[output2.txt](https://github.com/acts-project/acts/files/6565683/output2.txt)
I seem to have made a little bit of progress but maybe created more problems... 
Here are some images of the detector: 
@asalzburger Did something change in the geometry construction in the last few major versions?

fix: Prevent rmin from going negative.

---

docs/howto/howto.rst
docs/howto/run_ckf_tracking.rst
docs/howto/run_fatras.rst
docs/howto/run_truth_tracking.rst

This PR fixes a few obsolete configurations for running the Fatras simulation and reco examples in the how-to guides. The how-to for ODD simulation is added.

docs: Update how-to

---

cmake/ActsCompilerOptions.cmake

We don't set any RPATH on install at all right now. This means you have to reconstruct where the dependency libraries are that we built with, and you have to supply `LD_LIBRARY_PATH` to ACTS libs in the install directory. 
RPATH is there to solve exactly this, this PR makes it so that the RPATH includes
- Library directories from which libraries were taken, if they didn't come from a standard path (`/usr/lib`, `/usr/local/lib` etc)
- A relative path from the binaries to the `lib` directory
With this the install directory should stay relocatable, as long as no external dependencies were taken from non standard paths, or in that case, on the same machine.
Closes #831

build: Set RPATH values on install

---

Core/include/Acts/MagneticField/BFieldMapUtils.hpp
Core/include/Acts/MagneticField/InterpolatedBFieldMap.hpp
Core/include/Acts/MagneticField/MagneticFieldProvider.hpp
Core/src/MagneticField/BFieldMapUtils.cpp
Examples/Detectors/MagneticField/CMakeLists.txt
Examples/Detectors/MagneticField/include/ActsExamples/MagneticField/MagneticField.hpp
Examples/Detectors/MagneticField/src/FieldMapRootIo.cpp
Examples/Detectors/MagneticField/src/FieldMapRootIo.hpp
Examples/Detectors/MagneticField/src/FieldMapTextIo.cpp
Examples/Detectors/MagneticField/src/FieldMapTextIo.hpp
Examples/Detectors/MagneticField/src/MagneticFieldOptions.cpp
Examples/Io/Root/include/ActsExamples/Io/Root/RootBFieldWriter.hpp
Tests/Benchmarks/SolenoidFieldBenchmark.cpp
Tests/IntegrationTests/InterpolatedSolenoidBFieldTest.cpp
Tests/UnitTests/Core/MagneticField/InterpolatedBFieldMapTests.cpp
Tests/UnitTests/Core/Utilities/BFieldMapUtilsTests.cpp

Since we're already on a streak of breaking changes related to the B field infrastructure, I thought this would be a good idea as well.
Turns out, with all B field types inheriting from `MagneticFieldProvider` we don't actually need `InterpolatedBFieldMapper` anymore, or rather, `InterpolatedBField**Mapper**` and `InterpolatedBField**Map**` can be one single type. This PR does that.
This depends on #825 and remains WIP until that is merged.
BREAKING CHANGE:
The instantiation of an interpolated B field changes from 
```cpp
using Grid_t = detail::Grid<Vector3, detail::EquidistantAxis, detail::EquidistantAxis>;
using Mapper_t = InterpolatedBFieldMapper<Grid_t>;
using BField_t = InterpolatedBFieldMap<Mapper_t>;
Grid_t g(std::make_tuple(std::move(r), std::move(z)));
Mapper_t …
```

refactor!: Remove interpolated magnetic field mapper

---

CI/run_examples.sh

The examples runner script currently leaves a Geant4 data archive lying around, even though it's only using the extracted version of said archive's contents. Let's not do that.

fix: Remove Geant4 data archive after extraction

---

Core/include/Acts/Propagator/Navigator.hpp
Examples/Algorithms/Fatras/src/FatrasAlgorithm.cpp
Examples/Algorithms/TrackFinding/src/TrackFindingAlgorithmFunction.cpp
Examples/Algorithms/TrackFitting/src/TrackFittingAlgorithmFunction.cpp
Examples/Run/Common/src/MaterialMappingBase.cpp
Examples/Run/Common/src/MaterialValidationBase.cpp
Examples/Run/Common/src/PropagationExampleBase.cpp
Tests/IntegrationTests/Autodiff/PropagationAutodiffDenseConstant.cpp
Tests/IntegrationTests/Fatras/FatrasSimulationTests.cpp
Tests/IntegrationTests/PropagationDenseConstant.cpp
Tests/UnitTests/Core/Geometry/BVHDataTestCase.hpp
Tests/UnitTests/Core/Material/SurfaceMaterialMapperTests.cpp
Tests/UnitTests/Core/Material/VolumeMaterialMapperTests.cpp
Tests/UnitTests/Core/Propagator/DirectNavigatorTests.cpp
Tests/UnitTests/Core/Propagator/ExtrapolatorTests.cpp
Tests/UnitTests/Core/Propagator/KalmanExtrapolatorTests.cpp
Tests/UnitTests/Core/Propagator/MaterialCollectionTests.cpp
Tests/UnitTests/Core/Propagator/NavigatorTests.cpp
Tests/UnitTests/Core/Propagator/StepperTests.cpp
Tests/UnitTests/Core/Seeding/EstimateTrackParamsFromSeedTest.cpp
Tests/UnitTests/Core/TrackFinding/CombinatorialKalmanFilterTests.cpp
Tests/UnitTests/Core/TrackFitting/KalmanFitterTests.cpp
Tests/UnitTests/Core/Visualization/EventDataView3DBase.hpp

Navigator currently has a number of members that act as configuration properties. In order to comply with our general philosophy to use nested `Config` structs for these kinds of properties, this PR adds `Navigator::Config`.
BREAKING CHANGE: The constructor and public members of `Acts::Navigator` changes. When before it could be created like
```cpp
Acts::Navigator nav{tGeometry};
nav.resolveSensitive = true;
nav.resolveMaterial = true;
nav.resolvePassive = true;
```
it must now be created like 
```cpp
Acts::Navigator::Config cfg;
cfg.trackingGeometry = tGeometry;
nav.resolveSensitive = true;
nav.resolveMaterial = true;
nav.resolvePassive = true;
Acts::Navigator nav{cfg};
```
Since `trackingGeometry` is the first member of `Acts::Navigator::Config`, if you don't want to change the …

refactor!: Make Navigator use a config struct

---

Examples/Io/Root/include/ActsExamples/Io/Root/RootMaterialTrackReader.hpp
Examples/Io/Root/include/ActsExamples/Io/Root/RootMaterialTrackWriter.hpp
Examples/Io/Root/include/ActsExamples/Io/Root/RootParticleReader.hpp
Examples/Io/Root/include/ActsExamples/Io/Root/RootTrajectoryParametersReader.hpp
Examples/Io/Root/src/RootMaterialTrackReader.cpp
Examples/Io/Root/src/RootMaterialTrackWriter.cpp
Examples/Io/Root/src/RootParticleReader.cpp
Examples/Io/Root/src/RootTrajectoryParametersReader.cpp
Examples/Run/Vertexing/TrackReaderVertexingPerformanceWriterExample.cpp

The current Root readers read the event from the root file assuming that the event `eventId` is the entry `eventId` in the tree. This is OK if only one root file is being read, but in case two different root files are read in, objects from two different events might be processed if the root files are written in multi-threaded modes.
This PR fixes the issue by finding the entry that has the desirable event id first. This might be expensive and could be improved by a better solution in the future.

fix: Root readers ensure event ordering is consistent

---

Core/include/Acts/Propagator/AtlasStepper.hpp
Core/include/Acts/Propagator/EigenStepper.hpp
Core/include/Acts/Propagator/Navigator.hpp
Core/include/Acts/Propagator/StepperConcept.hpp
Core/include/Acts/Propagator/StraightLineStepper.hpp
Core/include/Acts/Propagator/detail/SteppingHelper.hpp
Core/src/Geometry/TrackingVolume.cpp
Tests/UnitTests/Core/Propagator/NavigatorTests.cpp

Debugging intersection issues is tricky. This PR adds `LoggerWrapper` to the surface update function, enabling it to provide more granular verbose log output. The output is structured to make it easy to understand what is going on during the intersection calculation.

refactor: Make intersection verbose logging a lot more verbose

---

Core/src/Material/AccumulatedSurfaceMaterial.cpp

This PR fixes a small potential issue when the surface has zero dimension binning during the surface material mapping.

fix: trackAverage when surface has zero binning

---

Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp

This PR fixes the search of last measurement index for the multitrajectory in the CKF.

fix: Search of last measurement index

---

codecov.yml

This has proven to be unreliable and hard to follow.

ci: Disable codecov-patch check

---

Examples/Run/CMakeLists.txt
Examples/Run/Geant4/CMakeLists.txt

For some reason, in `Examples/Run/Geant4/CMakeLists.txt` the target
`ActsExampleGeantinoRecordingGdml` links against `ActsExamplesDD4hep`,
which I don't think it has to. Consequently, the `Examples/Run/Geant4`
directory is only added if DD4hep is enabled. There is an extra
subdirectory that inside with DD4hep-aware code, so I think it's safe to
drop the dependency of all of `Examples/Run/Geant4` on DD4hep here.

fix: GdmlGeantinoRecording does not need DD4hep

---

Examples/Scripts/MaterialMaping/Mat_map.C
Examples/Scripts/MaterialMaping/Mat_map_detector_plot.C
docs/howto/run_material_mapping.rst

Fix the Howto for material mapping. Include the fact that the Z0 and D0 sigma need to be set to 0 in the validation to be correctly compare to the Geantino scan.  
Also modify the root  script to take into account that the Geantino scan is flat in theta where the Validation is flat in eta.

fix: Howto material without spread

---

Core/src/Surfaces/CylinderSurface.cpp
Core/src/Surfaces/DiscSurface.cpp
Tests/UnitTests/Core/Surfaces/CylinderSurfaceTests.cpp
Tests/UnitTests/Core/Surfaces/DiscSurfaceTests.cpp

`DiscBounds` has special logic for `binR`, where it asks its `DiscBounds` for a binning value. This logic is not invoked for `binPhi`, which I believe it should. Added a unit test to assert this behavior.
Also **I believe** binning value should be in global coordinates here. Previously this worked **if** local-to-global was only a translation along `z`, because the center `z` position was explicitly added. I think generically it should be global, therefore I changed it to apply the transform.
/cc @asalzburger @Corentin-Allaire

fix: DiscBounds binningValue incorrect for binPhi

---

Tests/UnitTests/Core/Utilities/PolymorphicValueTest.cpp

#855 broke the build on my end because of a missing include in a test file. Here we simply add that include, and all is well.
cc @paulgessinger

fix: Add missing include in PolymorphicValueTest.cpp

---

Core/include/Acts/Utilities/Helpers.hpp
docs/requirements.txt

Doxygen+breathe started breaking when bumping breathe to `4.26.1`, which was tracked in #661. While the error might be fixed with an as-of-yet unreleased version of doxygen, this PR includes a workaround that seems to make the doc build run through on breathe `4.30.0.`, which I believe is the current version and also showed this failure.
Resolves #661

docs: Fix doxygen parser problem by a workaround

---

Examples/Framework/src/Framework/Sequencer.cpp

Including `tbb/tbb.h` is apparently deprecated:
```console
In file included from ../Examples/Framework/src/Framework/Sequencer.cpp:23:
/usr/include/tbb/tbb.h:21:154: note: #pragma message: TBB Warning: tbb.h contains deprecated functionality. For details, please see Deprecated Features appendix in the TBB reference manual.
21 | #pragma message("TBB Warning: tbb.h contains deprecated functionality. For details, please see Deprecated Features appendix in the TBB reference manual.")
|
```
This PR replaces it with separate includes.

fix: Replace deprecated `tbb.h` include

---

thirdparty/OpenDataDetector/xml/OpenDataLongStrips.xml
thirdparty/OpenDataDetector/xml/OpenDataPixels.xml
thirdparty/OpenDataDetector/xml/OpenDataShortStrips.xml

This PR updates the ODD to have a synchronised module number in the endcap disks.

feat: Update open data detector with synchronized endcap modules

---

Core/include/Acts/Propagator/DirectNavigator.hpp
Core/include/Acts/Propagator/Navigator.hpp
Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp
Core/include/Acts/TrackFitting/KalmanFitter.hpp
Core/include/Acts/TrackFitting/KalmanFitterError.hpp
Tests/UnitTests/Core/TrackFitting/KalmanFitterTests.cpp

This PR simplifies the reset of the navigation state to enable the navigation to start from a new surface with provided position and momentum. It requires the `Navigator` `State` struct has a method `reset`.

refactor!: Reset navigation state in (C)KF

---

Examples/Io/HepMC3/src/HepMC3Event.cpp
Examples/Io/HepMC3/src/HepMC3Vertex.cpp

In a few spots in the HepMC3 examples, `std::shared_ptr` were created with raw pointers to stack variables. This clearly results in `std::shared_ptr` calling `delete` on cleared memory.
@FabianKlimpel can you review this small change?

fix(HepMC3): Remove shared_ptr to stack variable

---

Examples/Algorithms/Geant4/include/ActsExamples/Geant4/GeantinoRecording.hpp
Examples/Algorithms/Geant4/include/ActsExamples/Geant4/PrimaryGeneratorAction.hpp
Examples/Algorithms/Geant4/src/EventAction.cpp
Examples/Algorithms/Geant4/src/EventAction.hpp
Examples/Algorithms/Geant4/src/GeantinoRecording.cpp
Examples/Algorithms/Geant4/src/PrimaryGeneratorAction.cpp
Examples/Algorithms/Geant4/src/RunAction.cpp
Examples/Algorithms/Geant4/src/RunAction.hpp
Examples/Algorithms/Geant4/src/SteppingAction.cpp
Examples/Algorithms/Geant4/src/SteppingAction.hpp
Examples/Algorithms/Geant4HepMC/include/ActsExamples/Geant4HepMC/EventRecording.hpp
Examples/Algorithms/Geant4HepMC/src/EventAction.cpp
Examples/Algorithms/Geant4HepMC/src/EventAction.hpp
Examples/Algorithms/Geant4HepMC/src/EventRecording.cpp
Examples/Algorithms/Geant4HepMC/src/PrimaryGeneratorAction.cpp
Examples/Algorithms/Geant4HepMC/src/PrimaryGeneratorAction.hpp
Examples/Algorithms/Geant4HepMC/src/RunAction.cpp
Examples/Algorithms/Geant4HepMC/src/RunAction.hpp
Examples/Algorithms/Geant4HepMC/src/SteppingAction.cpp
Examples/Algorithms/Geant4HepMC/src/SteppingAction.hpp

Previously these had the same symbol names between ExamplesGeant4 and ExamplesGeant4HepMC3. This is fine if these libraries are never linked together, but if that happens, it leads to crashes due to incompatible clashes. This moves both sets of classes into namespaces, to avoid clashes.
Fixes #874
/cc @FabianKlimpel

fix: Move Geant4 actions into namespaces

---

Examples/Detectors/TGeoDetector/CMakeLists.txt
Examples/Detectors/TGeoDetector/include/ActsExamples/TGeoDetector/BuildTGeoDetector.hpp
Examples/Detectors/TGeoDetector/src/BuildTGeoDetector.cpp
Examples/Detectors/TGeoDetector/src/TGeoDetectorOptions.cpp
Examples/Run/Common/src/CommonOptions.cpp
Plugins/Legacy/include/Acts/Seeding/AtlasSeedfinder.ipp
Plugins/TGeo/CMakeLists.txt
Plugins/TGeo/include/Acts/Plugins/TGeo/ITGeoDetectorElementSplitter.hpp
Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoCylinderDiscSplitter.hpp
Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoDetectorElement.hpp
Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoLayerBuilder.hpp
Plugins/TGeo/src/TGeoCylinderDiscSplitter.cpp
Plugins/TGeo/src/TGeoDetectorElement.cpp
Plugins/TGeo/src/TGeoLayerBuilder.cpp

This PR introduces a new interface in the `TGeo` plugin that allows splitting of `TGeoDetectorElement` objects and adds a necessary constructor for this to the `TGeoDetectorElement`.
This will be needed for the ALICE o2 studies (generic splitter from disk to trapezoids), but also for the TGeo version of the ATLAS ITk, where dedicated splitters need to be written.
Tagging some interested parties: @paulgessinger @niermann999 @noemina 
The splitting has to be activated with a switch:
```shell
--geo-tgeo-cyl-disc-split
```
And then, consequently, all volumes need to define how they wanna perform the splitting, e.g. for no splitting:
```shell
--geo-tgeo-cyl-nz-segs -1
--geo-tgeo-cyl-nphi-segs -1
--geo-tgeo-disc-nr-segs -1
--geo-tgeo-disc-nphi-segs -1
```
versus splitting:
```shell …
```

feat: introduce TGeoDetectorElementSplitter & splitted detector element constructors

---

Plugins/DD4hep/src/ConvertDD4hepDetector.cpp

This PR fixes an issue that only the beam pipe was regarded as a passive layer to be built, an issue easily spotted in the OpenDataDetector setup.
With this one-line fix, suddenly the Solenoid and the Pixel Support Tube show up.
```shell
12:21:38    DD4hepConver   INFO      Translating DD4hep geometry into Acts geometry
12:21:38    DD4hepConver   INFO      Translating DD4hep sub detector: BeamPipe
12:21:38    DD4hepConver   INFO      Translating DD4hep sub detector: Pixels
12:21:38    DD4hepConver   INFO      Translating DD4hep sub detector: PST
12:21:38    DD4hepConver   INFO      Translating DD4hep sub detector: ShortStrips
12:21:38    DD4hepConver   INFO      Translating DD4hep sub detector: LongStrips
```

fix: build passive layers for DD4hep

---

thirdparty/OpenDataDetector/factory/ODDPixelEndcap_geo.cpp
thirdparty/OpenDataDetector/factory/ODDStripEndcap_geo.cpp
thirdparty/OpenDataDetector/xml/OpenDataLongStrips.xml
thirdparty/OpenDataDetector/xml/OpenDataPixels.xml
thirdparty/OpenDataDetector/xml/OpenDataShortStrips.xml

This PR updates the OpenDataDector to the version where both Long Strips endcaps are now covered with a sensible number of elements.
It also introduces a manual setting of the number of bins for the surface binning if requested.

feat: update OpenDataDetector to tip

---

Examples/Run/MagneticField/BFieldAccessExample.cpp
Tests/UnitTests/Core/MagneticField/MagneticFieldInterfaceConsistencyTests.cpp

Had to reopen from #665, because the target branch had changed.
Let's see what this looks like now.

fix: Boost warnings due to deprecations

---

Plugins/TGeo/src/TGeoCylinderDiscSplitter.cpp

This PR contains a fix of the bug in the `TGeoCylinderDiscSplitter` class that prevented splitting the disk layers only, i.e.: 
```
--geo-tgeo-cyl-nz-segs -1
--geo-tgeo-cyl-nphi-segs -1
--geo-tgeo-disc-nr-segs 1
--geo-tgeo-disc-nphi-segs 32
```

fix: TGeo disc and cylinder splitting

---

Core/include/Acts/Propagator/StepperExtensionList.hpp
Core/include/Acts/Propagator/detail/GenericDefaultExtension.hpp
Core/include/Acts/Propagator/detail/GenericDenseEnvironmentExtension.hpp
Plugins/Autodiff/include/Acts/Plugins/Autodiff/AutodiffExtensionWrapper.hpp

The argument `knew` is defaulted to `Vector3D{}` which is uninitialized. This shows up as a warning in GCC10, see #887. This PR initializes the values to zero in this location, and also in a few other related locations.
Fixes #887.
@benjaminhuth , can you review?

fix: GCC10 warning about uninitialized value

---

Examples/Framework/src/Utilities/Paths.cpp

This uses a local logger which is not configurable. It is set to `VERBOSE` by default leading to a lot of output if reading in CSV files. This PR changes the default to `INFO`.

fix: determineEventFilesRange is VERBOSE by default

---

Examples/Algorithms/Digitization/include/ActsExamples/Digitization/Smearers.hpp
Examples/Io/Json/src/JsonDigitizationConfig.cpp

The smearing callable structs used in the digitization have member variables to various `std::*_distribution` objects. These types of objects are not thread-safe as they contain state. This lead to non-reproducibility in the smearing. This PR moves the distribution object to the `operator()()` body, ensuring they are not shared across threads.
Fixes #869 
/cc @robertlangenberg

fix: Make smearers used in digitization thread-safe

---

Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/TrackFindingAlgorithm.hpp
Examples/Algorithms/TrackFinding/src/TrackFindingAlgorithm.cpp
Examples/Algorithms/TrackFinding/src/TrackFindingAlgorithmFunction.cpp
Examples/Algorithms/TrackFitting/include/ActsExamples/TrackFitting/TrackFittingAlgorithm.hpp
Examples/Algorithms/TrackFitting/src/TrackFittingAlgorithmFunction.cpp

Changes both the fitting and the finding algorithm to use a regular
interface with virtual methods rather than std::function to decouple the
actual fitter/finder instances. The decoupling is only for compile-time
memory usage reduction. The reason is that pybind11 does a round trip
throught python with std::function, which we want to avoid. This is
functionally equivalent, but uses a different mechanism.
Also adds factory functions for these decoupled objects. We don't
foresee these to be switchable, this decoupling is done for purely
technical reasons anyway.

refactor: Fitting and Finding algorithm function interface

---

Examples/Io/Root/include/ActsExamples/Io/Root/RootTrajectorySummaryWriter.hpp
Examples/Io/Root/src/RootTrajectorySummaryWriter.cpp

This PR adds the writing of variable of truth impact parameters in the `RootTrajectorySummaryWriter`.

feat: Add truth impact parameters to RootTrajectorySummaryWriter

---

Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp
Core/include/Acts/TrackFitting/KalmanFitter.hpp

In the current (C)KF, a curvilinear state is created if the track reaches the passive material surface. This was initially implemented due to the reason that a bound state on a Cylinder surface is not working properly. However, this seems to be not the case any more. Hence, bound states are alwasy created, which should be more accurate.

refactor: Always create bound states in (C)KF

---

Core/include/Acts/Propagator/AtlasStepper.hpp
Core/include/Acts/Propagator/EigenStepper.hpp
Core/include/Acts/Propagator/EigenStepper.ipp
Core/include/Acts/Propagator/StepperConcept.hpp
Core/include/Acts/Propagator/StraightLineStepper.hpp
Core/include/Acts/Surfaces/Surface.hpp
Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp
Core/include/Acts/TrackFitting/KalmanFitter.hpp
Core/src/Propagator/StraightLineStepper.cpp
Examples/Run/Reconstruction/Common/RecTruthTracks.cpp
Tests/UnitTests/Core/Propagator/AtlasStepperTests.cpp
Tests/UnitTests/Core/Propagator/NavigatorTests.cpp
Tests/UnitTests/Core/Propagator/StepperTests.cpp
Tests/UnitTests/Core/Propagator/StraightLineStepperTests.cpp

Currently, the stepper only update the `cov` and `pars` in the `update` invocation. However, the updated `pars` means the `jacToGlobal` should be updated as well, in particular the `pars` has underwent some big change after the KF filtering.
So this PR fixes the issue. It adds the update of the `jacToGlobal` in the stepper `update` method.

fix: update jacToGlobal after KF filtering

---

Core/include/Acts/Utilities/MultiIndex.hpp
Examples/Algorithms/Generators/ActsExamples/Options/ParticleGunOptions.cpp

Add a `--gen-nvertex` option to `ActsExampleParticleGun` which allows setting the event multiplicity. Also adds functionality to `Acts::MultiIndex` to retrieve the number of bits per level, and use this to do error checks on the input parameters in `ActsExampleParticleGun`.
Should fix #913.

feat: Add num-vertex option to PG, error check

---

Examples/Framework/include/ActsExamples/Framework/Sequencer.hpp
Examples/Framework/src/Framework/Sequencer.cpp

The default is a noop function pointer.
The background is that for the python bindings, I need to hook into the
event loop to be able to correctly respond to Ctrl+C. This is the most
decoupled way to do this I could think of.
Also increases the amount of output `Sequencer` produces in verbose
mode.

feat: Sequencer gets configurable iteration callback

---

README.md

To use the Zenodo Github integration, I had to create another upload on Zenodo, which is not a successor to the previous DOI. I linked the two uploads together, but there is a new 'stable' DOI now.

chore: Update readme with new Zenodo DOI

---

Core/include/Acts/Definitions/Units.hpp
Core/include/Acts/Seeding/BinnedSPGroup.hpp
Core/include/Acts/Seeding/BinnedSPGroup.ipp
Core/include/Acts/Seeding/SeedFilter.ipp
Core/include/Acts/Seeding/SeedFilterConfig.hpp
Core/include/Acts/Seeding/Seedfinder.ipp
Core/include/Acts/Seeding/SeedfinderConfig.hpp
Core/include/Acts/Seeding/SpacePointGrid.hpp
Core/include/Acts/Seeding/SpacePointGrid.ipp
Examples/Run/Reconstruction/Common/SeedingExample.cpp
Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/Seedfinder.ipp
Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding2/SeedFinder.ipp
Plugins/Sycl/include/Acts/Plugins/Sycl/Seeding/Seedfinder.ipp
Tests/UnitTests/Core/Seeding/SeedfinderTest.cpp
Tests/UnitTests/Plugins/Cuda/Seeding/SeedfinderCudaTest.cpp
Tests/UnitTests/Plugins/Cuda/Seeding2/main.cpp
Tests/UnitTests/Plugins/Sycl/Seeding/SeedfinderSyclTest.cpp

The seed finding config currently uses implicit units. This PR switches to explicit units using the common `Acts::UnitConstants`. Since we don't want to do the conversion to seeding-internal units all the time, it does this once in the constructor, where special methods `toInternalUnits` are called which return a copy of the config with the members converted to internal units.
This should result in no changes to the actual calculations, and only to the configuration interface.
BREAKING CHANGE:
The seeding configuration structs `SpacePointGridConfig`, `SeedFilterConfig` and `SeedFinderConfig` change to now use ACTS units.

refactor!: Use common units for seed finding

---

Examples/Scripts/TrackingPerformance/CMakeLists.txt
Examples/Scripts/TrackingPerformance/CommonUtils.h
Examples/Scripts/TrackingPerformance/PerigeeParameters.cpp
Examples/Scripts/TrackingPerformance/ResidualsAndPulls.cpp
Examples/Scripts/TrackingPerformance/boundParamResolution.C
Examples/Scripts/TrackingPerformance/perigeeParamResolution.C

This PR partly harmonizes the Executables in the `Script/TrackingPerformance` folder.
Currently one can run:
* ActsExampleResidualAndPulls
* ActsExamplePerigeeParameters
both steered by program options, the efficiency & fake-rate executable with also follow in a separate PR.
The naming of the plots is slightly refined and a quite option to produce plots from shell scripts (e.g. automatically from test runs in the CI is added).

feat: add another script executable, add program options

---

Examples/Algorithms/TrackFinding/src/TrackParamsEstimationAlgorithm.cpp

While I was playing around with the seeding, I noticed that the `TrackParamsEstimationAlgorithm` was a significant source of overhead for high pile-up events. When processing events with 4000 pions, the time taken to run this algorithm starts to approach the runtime of seeding itself. For much larger events, in the neighbourhood of 12000 pions (where we get higher fake rates), the result was even worse with the track parameter estimation taking hundreds of milliseconds. The reason for this is simple: given |_S_| spacepoints (which in itself linear in the number of particles), the track parameter estimation performs an _O_(|_S_|) lookup operation for each of the _O_(1) hits in each seed. In total, there are _O_(|_S_|) (or even _O_(|_S_|<sup>3</sup>) in the uncapped case) seeds, and so the …

perf: Use map to accelerate parameter estimator

---

Core/include/Acts/Seeding/Seedfinder.hpp
Core/include/Acts/Seeding/Seedfinder.ipp

This is just a tiny little improvement on #905. I noticed that we are currently using an output iterator function to write some results to a vector, and then copying that vector over to append it to another, existing vector. I think it would be (very marginally) quicker and neater to avoid this extra copy and just have the function take the insertion iterator of the vector we are planning to write to in the end.

perf: Remove extraneous copies in seedfinder

---

Examples/Algorithms/CMakeLists.txt
Examples/Algorithms/Digitization/CMakeLists.txt
Examples/Algorithms/Digitization/include/ActsExamples/Digitization/DigitizationConfig.hpp
Examples/Algorithms/Digitization/include/ActsExamples/Digitization/DigitizationConfigurator.hpp
Examples/Algorithms/Digitization/src/DigitizationConfig.cpp
Examples/Run/Digitization/Common/DigitizationConfigExample.cpp

This was previously only privately used in the
DigitizationConfigExample, but can be useful in other context.
At the same time, this introduces a constructor for `DigitizationConfig`
that only takes a finished geometry hierachy map (and no program options), which can for instance
be built with the configurator.

refactor: Make the DigitizationConfigurator usable

---

Core/include/Acts/Utilities/BinningType.hpp
Core/src/Geometry/Extent.cpp
Core/src/Geometry/ProtoLayerHelper.cpp
Core/src/Geometry/TrackingVolumeArrayCreator.cpp
Plugins/DD4hep/src/ConvertDD4hepMaterial.cpp
Plugins/Json/src/UtilitiesJsonConverter.cpp
Plugins/TGeo/src/TGeoLayerBuilder.cpp

This caused problems for me when opening the ActsCore shared lib through python. Also, it's generally safer to try not to use statically initialized global variables. This changes this to a function that statically initializes it in the body (safe) and returns a const ref only.

fix: Static initialization of vector of strings

---

Examples/Io/Root/include/ActsExamples/Io/Root/RootTrajectorySummaryWriter.hpp
Examples/Io/Root/src/RootTrajectorySummaryWriter.cpp

Curretly, the residual and pull for perigee track parameters are written as histograms in the `performance_track_fitter.root`. 
This PR writes out these variables into the tree written out by the `RootTrajectorySummaryWriter`, which could allow customizable binning of those variables when plotting.

perf: write out perigee residual and pull in root tree

---

Core/src/Visualization/GeometryView3D.cpp
Examples/Run/Common/src/GeometryExampleBase.cpp

In #917 I introduced an output directory to `GeometryView3D`. I set the default to "." as that usually means the current directory. Due to the way we currently look for file extensions, this didn't actually work. I didn't actually test the default, so that broke the output writing.
This PR works around this by checking if the default value "." is given, and replaces this with the actual `$PWD`. This is not super robust, and ideally we should revise all of this using `boost::filesystem`, which I'll try to do in a future PR.
Aside from this, this PR also make the geometry examples correctly pipe through the `--output-dir` option to the geometry view output.

fix: GeometryView3D default output directory doesn't work.

---

Examples/Algorithms/Digitization/share/default-smearing-config-generic.json

Previously I carelessly set the smearing widths equal to the pixel or strip dimensions. This is ill-advised as the resulting measurement only falls in the right pixel ~68% of the time. In this PR, smearing widths are changed to dimensions/sqrt(12). 
closes #946 
cc @robertlangenberg

fix: Use width/sqrt(12) in smearing digi config file for generic detector

---

Core/include/Acts/Seeding/SeedfinderConfig.hpp

In #941, the collision region bounds in the _z_ axis were mistakenly defined to be in MeV where they should be in millimetres. This change doesn't negatively impact physics performance per se because it makes the collision region one thousand times larger than it should be, but it can have significant influence on the compute performance. This commit changes the unit back to millimetres, as it should be.

fix: Collision region should be in millimetres

---

README.md
docs/getting_started.md

Now that the OpenDataDetector is a submodule, people cloning the ACTS repository should probably default to using recursive git clone, otherwise docs examples based on the ODD will not work.

docs: Recommend recursive git clone for ODD compatibility

---

Examples/Algorithms/Geant4/src/Geant4Simulation.cpp
Examples/Algorithms/Geant4/src/MaterialSteppingAction.cpp

This PR fixes an issue that the vertex and momentum direction have not been appropriately set in the reworked MaterialRecording example.

fix: assign the vertex and direction at first step

---

Examples/Algorithms/Geant4/CMakeLists.txt
Examples/Algorithms/Geant4/include/ActsExamples/Geant4/Geant4Simulation.hpp
Examples/Algorithms/Geant4/include/ActsExamples/Geant4/MagneticFieldWrapper.hpp
Examples/Algorithms/Geant4/include/ActsExamples/Geant4/ParticleTrackingAction.hpp
Examples/Algorithms/Geant4/include/ActsExamples/Geant4/SensitiveSteppingAction.hpp
Examples/Algorithms/Geant4/include/ActsExamples/Geant4/SensitiveSurfaceMapper.hpp
Examples/Algorithms/Geant4/src/Geant4Simulation.cpp
Examples/Algorithms/Geant4/src/MagneticFieldWrapper.cpp
Examples/Algorithms/Geant4/src/ParticleTrackingAction.cpp
Examples/Algorithms/Geant4/src/SensitiveSteppingAction.cpp
Examples/Algorithms/Geant4/src/SensitiveSurfaceMapper.cpp
Examples/Framework/include/ActsExamples/EventData/SimHit.hpp
Examples/Io/Csv/src/CsvParticleReader.cpp
Examples/Run/Common/src/CommonSimulation.cpp
Examples/Run/Fatras/Common/Fatras.cpp
Examples/Run/Geant4/Common/Geant4.cpp
Examples/Run/Geant4/Common/Geant4.hpp
Examples/Run/Geant4/DD4hep/CMakeLists.txt
Examples/Run/Geant4/DD4hep/DD4hepGeant4Simulation.cpp

This PR is the second pull request for the Geant4 simulation and introduces the full simulation for single particles.
It uses the same `Geant4Simulation` algorithm and establishes a symmetric setup between `Fatras` and `Geant4` simulation.
e.g. `Fatras`:
```shell
./ActsExamplesFatrasDD4hep <args>
```
and `Geant4`:
```shell
./ActsExamplesGeant4DD4hep <args>
```
Can now be run with the same argument list.

feat: rework Geant4 simulation (2/X)

---

Core/include/Acts/Propagator/Navigator.hpp

This PR is a fix to #926.
It allows the search for layers after the (fast-associated) starting layer has been processed.

fix: allow layer search in original volume after fast initialization

---

Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp
Core/include/Acts/TrackFitting/KalmanFitter.hpp

This PR fixes #984 and #994 . 
The reason for #984 is that after #956, a track might have non-zero `processedStates`, but zero `measurementStates`. So we return a failure explicity in KF if `measurementStates` is zero.
The inaccurate logging in `addNonSourcelinkState` as mentioned in #994 is fixed.

fix: KF return and CKF logging

---

Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp

This PR fixes #961.
The reason for #961 is that the `reset` of navigation state with a target surface (i.e. a perigee surface at the beam line) in CKF will confuse the navigator. For example, when the navigation state is reset to `vol=13|lay=8|sen=1028`, the `Target volume estimated :` might be exactly the same as the start volume if a target surface is set. This will result in `Re-initialzing cancelled as it is the first step` and the navigator will not proceed to find the boundary surfaces.
Therefore, a `nullptr` `targetSurface` is passed to the navigator during `reset`.
The detailed logs with and without the fix can be found below.

fix: Set target surface to null for forward filtering in CKF

---

Examples/Algorithms/Geant4/include/ActsExamples/Geant4/EventStoreRegistry.hpp
Examples/Algorithms/Geant4/src/EventStoreRegistry.cpp
Examples/Algorithms/Geant4/src/Geant4Simulation.cpp
Examples/Algorithms/Geant4/src/MaterialSteppingAction.cpp
Examples/Algorithms/Geant4/src/ParticleTrackingAction.cpp
Examples/Algorithms/Geant4/src/SensitiveSteppingAction.cpp
Examples/Algorithms/Geant4/src/SimParticleTranslation.cpp
Examples/Run/Geant4/Common/Geant4.cpp

This PR changes the `EventRegistry` that was added for the G4 algorithm to not use an `std::map` with the event number as a key (which is unstable, and not the same between G4 and the ACTS sequencer) to simply use a thread local static variable.
I also renamed `EventRegistry::Access` to `EventRegistry::State`.

refactor: G4 event registry uses thread_local

---

Examples/Algorithms/Generators/ActsExamples/Generators/ParametricParticleGenerator.cpp
Examples/Algorithms/Generators/ActsExamples/Generators/ParametricParticleGenerator.hpp
Examples/Algorithms/Generators/ActsExamples/Options/ParticleGunOptions.cpp

This mini-PR adds a new option `--gen-sample-eta` to the `ParametricParticleGenerator` that allows to draw a flat eta distribution. This can be useful for detector performance classification, to populate the eta-phi plane uniquely. It can also be favourable for the material mapping to have a flat eta distribution.
The following shows the `eta` distributions of generated particles:
* blue: standard sampling in `cos(theta)`
* red: flat `eta` sampling with the `--gen-sample-eta` switch opted on

feat: allow sampling in eta

---

Examples/Detectors/TGeoDetector/include/ActsExamples/TGeoDetector/JsonTGeoDetectorConfig.hpp
Examples/Detectors/TGeoDetector/src/TGeoDetector.cpp

Our current minimum version of `nlohmann::json` is `3.2.0` as far as I know, and `ordered_json` was not intruduced until `3.9.0`. See https://github.com/acts-project/acts/pull/780/files
This PR removes usage of `ordered_json`.
@niermann999 is `ordered_json` needed here, or rather a convenience?

fix: remove usage of `ordered_json`

---

Examples/Algorithms/Geant4/src/SimParticleTranslation.cpp

`SimParticleTranslation` extracts and converts the particle momentum from our particle gun particles.
The momentum calculation is never eval'd, so I believe this results in `operator[]` not extracting sensible values, meaning the G4 particle gets random momentum. This PR adds an `.eval()`, and also some more verbose output in the `SimParticleTranslation`

fix: SimParticleTranslation does not correctly translate momentum

---

.github/workflows/builds.yml

We had more trouble with them than they add value, so let's get rid of them again for now.

ci: Remove CVMFS based LCG jobs again

---

Plugins/Sycl/src/Seeding/CreateSeedsForGroupSycl.cpp

As we found out with @krasznaa, there was a bug in the current implementation of the Sycl Seedfinder algorithm. It came out in a particular case when the first part of the algorithm - the `Duplet finding`, didn't find any duplets. In this scenario, the `Triplet finding` was running forever and the code didn't terminate.
The problem appeared inside the `loop` of the `Triplet finding`. 
In the current implementation, finding triplets is splitted into several parts to limit the memory allocations on the GPU. The range of the particular iteration is taken from the `firstMiddle` and `lastMiddle` indices. The current logic follows somewhat those steps:
```
firstMiddle = lastMiddle = 0
while  firstMiddle < MiddleSPs 
do 
++lastMiddle                  // until maxMemory is reached
numThreads = …
```

fix: A bug in the Triplet finding algorithm

---

Core/include/Acts/EventData/MultiTrajectory.hpp
Core/include/Acts/EventData/MultiTrajectoryHelpers.hpp
Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp

This PR makes `MultiTrajectory` always initialize the `chi2` value to `0`. In addition, I updated `MultiTrajectoryHelpers::trajectoryState` to only add track state `chi2` to the overall `chi2sum` for measurement track states.
Outlier track states' `chi2` is still recorded in the separate `outlierChi2`. 
I think this makes sense since the outlier is not actually used in the fit, and the track state can only contain the *predicted* `chi2` rather than the *filtered* `chi2` that the measurement states have.
Does this make sense @XiaocongAi?

feat: MultiTrajectory chi2 handling

---

.github/workflows/builds.yml
CMakeLists.txt

Made it possible not to set them up at all. In case Acts is built as part of a "larger" project, like [traccc](https://github.com/acts-project/traccc). And that "larger" project wants to set these up according to its own liking.
At the same time fixed the capitalisation of the flags in the CI configuration. (`on` != `ON` in CMake lingo.)
I used the same naming here that I've set up in the "traccc projects" in the last weeks. See for instance:
- https://github.com/acts-project/algebra-plugins/pull/27
- https://github.com/acts-project/detray/pull/129
Making this kind of update will be vital for setting up the build of Acts in [traccc](https://github.com/acts-project/traccc) in the same way.

feat: Introduced new flags for how Boost, Eigen and VecMem would be set up. (2021.11.05.)

---

Core/include/Acts/EventData/MultiTrajectory.hpp
Tests/UnitTests/Core/EventData/MultiTrajectoryTests.cpp

This does three things:
1. `MultiTrajectory` and it's internal column storage can be queried for
their size and "cleared", meaning their logical size reduced to zero,
while keeping their capacity
2. `ConstTrackStateProxy` is now (auto-)constructible from
`TrackStateProxy`. This is necessary to enable interfaces for certain
components to accept `ConstTrackStateProxy` and passing a non-const
`TrackStateProxy`
3. Allows `MultiTrajectory::TrackStateProxy::copyFrom` to also copy
regardless of underlying allocation. If this flag id set to `false`,
the method will copy everyhing which has a valid index **potentially
overwriting information in other track states via shared storage**

feat: MultiTrajectory improvements

---

Plugins/Json/src/AlgebraJsonConverter.cpp

Change the order of translation / rotation when reading transforms back from `json`.
This is necessary that the transforms are correctly re-created.

fix: json algebra reading

---

Core/include/Acts/Geometry/CylinderVolumeBuilder.hpp

It was notice in the building of the ATLAS tracking geometry that if two volumes overlap then the wrapping won't do anything but will also not return any error. This PR add a throw in case of overlapping volumes.

fix: Fail wrapping in case of overlap

---

Core/include/Acts/Propagator/Navigator.hpp
Core/include/Acts/Propagator/detail/SteppingHelper.hpp

This warning popped up in a number of places, but mostly when targeting
parigee surfaces, e.g. in the vertexing or in the KF when the backward
smoothing propagation is enabled. It's possible this only occurs with a
beampipe layer.
I **think** what's happening is two things:
- The on-surface tolerance wasn't applied correctly in one location (I think we do this in other spots, like when we're looking for compatible layers in volumes, and compatible surfaces in layers.)
- If we actually have a target surface (and it's still reachable), this
navigation state is probably still valid. We are on the final layer,
the navigator realizes it won't find the perigee surfaces through the
tracking geometry. It looks up the volume from the target surface
position, and determines that we are in fact in …

fix: Warning in navigation when targeting perigee

---

Core/include/Acts/Utilities/Intersection.hpp
Tests/UnitTests/Core/Utilities/IntersectionTests.cpp

This is the first part of my GSF pull-request series, where I often need to print the Intersection status for debugging. I split up this PR, since it is independent on the following ones.
Basically this pulls the nested `enum class Status` out of the `Intersection<DIM>` template struct to a `enum class IntersectionStatus` at namespace scope. The `IntersectionStatus` is broadcasted into the `Intersection<DIM>` with a `using Status = IntersectionStatus` to remain compatability.
This is done because otherwise the `Status`-enum would depend on the template-parameter `DIM` and thus the `operator<<` would also needed to be templated on `DIM` which makes things more complicated than they need to be.

feat: Add ostream-operator for IntersectionStatus

---

Core/src/Geometry/TrackingVolume.cpp

I noticed in #1103 that the navigation failed in backward mode after we merged #1107.
Indeed, during the change in #1107, `TrackingVolume` lost a line that copied the sign from the navigation direction onto the path length in `compatibleBoundaries`. This made the navigation go haywire when it tried to target boundaries in reverse propagation mode.
This PR adds that back in, and should fix #1103's test runs.

fix: TrackingVolume intersection check didn't copy sign

---

Core/include/Acts/Propagator/EigenStepper.hpp

Self explanatory. This doesn't give a compilation error because we never compile the Eigen Stepper header on it's own.

fix: Missing include in EigenStepper.hpp

---

Core/src/Geometry/CylinderVolumeBounds.cpp

Cylindrical volumes can cover only a sectoral part, if a `phi` opening angle and a `averagePhi` is defined.
The sectoral planes were only correct for `averagePhi=0`, as this parameter was missing in the rotation.

fix: adding missing averagePhi in CylinderVolumeBounds

---

Core/src/Geometry/GenericApproachDescriptor.cpp

Reduces the number of heap allocations in that method. As the number of approach surfaces is *almost always* 2, I think this makes sense to use a `small_vector` for.

refactor: Use `small_vector` in `surfaceOnApproach`

---

Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSmearingOptions.cpp
Examples/Run/Reconstruction/Common/RecCKFTracks.cpp

The CKF tracking example crashes due to missing particle smearing options. The initial inflation option clashes with an option of the same name in the fitting options and has been renamed.

fix: Add smearing options to ckf tracking example

---

Core/include/Acts/EventData/MultiTrajectory.hpp
Tests/UnitTests/Core/EventData/MultiTrajectoryTests.cpp

This adds a `friend class` statement in the `MultiTrajectory` that enables `copyFrom(...)` from a `ConstTrackStateProxy` to a mutable `TrackStateProxy`.
I added this to the UnitTest, but this for now only checks if this compiles.

fix: Enable copyFrom const track proxy for MultiTrajectory

---

Core/include/Acts/Utilities/Logger.hpp
Core/src/Utilities/Logger.cpp

We call `LoggerWrapper::operator()()` and `LoggerWrapper::doPrint` **a lot**, so I think it makes sense to have them in the header so they can be inlined.
Also changes the way the singleton `DummyWrapper` works: now it uses a safer idiom with static initialization right inside the function.

refactor: Move LoggerWrapper methods to inline

---

Core/include/Acts/Propagator/AtlasStepper.hpp
Core/include/Acts/Propagator/EigenStepper.hpp
Core/include/Acts/Propagator/Navigator.hpp
Core/include/Acts/Propagator/StandardAborters.hpp
Core/include/Acts/Propagator/StepperConcept.hpp
Core/include/Acts/Propagator/StraightLineStepper.hpp
Tests/UnitTests/Core/Propagator/AbortListTests.cpp
Tests/UnitTests/Core/Propagator/NavigatorTests.cpp

This PR is in preparation for the MultiStepper PR #1110 
Since a single `stepSize` isn't useful for a multi-component state, this removes the requirement to have such an object and add/modifies the accessors in the steppers. In particular it does:
* Modify the `stepper.setStepSize(...) function to allow it to replace calls to `stepSize.update(...)`
* This is done by adding an optional `bool` parameter to control wether or not release the stepSize. This defaults to true, so the default behaviour is unchanged, so I think this is not breaking.
* This does also modify the `previousStepSize` in the stepper-states. But I think this is not problematic, since this variable seems to be used just in unit tests, which still run through as far as I can tell.
```c++ …
```

refactor!: stepper-state does not have to contain a stepSize object anymore

---

.github/workflows/checks.yml
CI/check_license.py
Examples/Python/tests/test_examples.py
Examples/Python/tests/test_writer.py

The recent black (python formatter) version changed the format output. This PR updates the format of three files and locks black to `22.1.0` now.

ci: Black version locked to 22.1.0

---

Examples/Detectors/TGeoDetector/include/ActsExamples/TGeoDetector/JsonTGeoDetectorConfig.hpp

This PR makes the ITk specific module splitting entry in the TGeo example json config file optional. Fixes #1153

fix: Make ITk splitting json entry optional

---

Core/include/Acts/Utilities/KDTree.hpp

This popped up for me on GCC 8. Trivial fix.

fix: Maybe uninit warning in KDTree

---

Core/include/Acts/Propagator/AtlasStepper.hpp
Core/include/Acts/Propagator/EigenStepper.hpp
Core/include/Acts/Propagator/EigenStepper.ipp
Core/include/Acts/TrackFitting/KalmanFitter.hpp

When trying to use the ATLAS stepper with the KF I noticed that it wouldn't work since we use to set the stepping state jacobian to a BoundMatrix::Identity() which isn't compatible with the ATLAS stepper.
This PR add a method to the stepper to set the jacobian to the identity, and thus solve this issue. 
Similarly I had to transform the update to a reset for the propagation to the Perigee as it relied on manually setting some matrix afterward (which was not compatible with the ATLAS stepper).

refactor: Add method to reset jacobian in stepper

---

Core/include/Acts/Seeding/SeedfinderConfig.hpp

`rMinMiddleSP` and `rMaxMiddleSP` do not need to be configured in the SeedFinder config, so this PR removes them

fix: Remove rMinMiddleSP and rMaxMiddleSP in the SeedFinder config

---

Core/include/Acts/Seeding/SeedfinderConfig.hpp

This PR fixes the units of `deltaRMiddleSPRange` to external ACTS units and adds `deltaRMiddleSPRange`, `deltaRMinTopSP`, `deltaRMaxTopSP`, `deltaRMinBottomSP` and `deltaRMaxBottomSP` to the `toInternalUnits` method.

fix: Fixing units in SeedFinderConfig

---

Examples/Algorithms/Propagation/include/ActsExamples/Propagation/PropagationOptions.hpp

This was for some reason using matrix access with two arguments to set elements of a vector (the diagonal of a matrix). Switched to use single component element access.

fix: Assertion failure in propagation example

---

Core/include/Acts/Definitions/Units.hpp
Tests/UnitTests/Core/Definitions/UnitsTests.cpp

Since `e=1` the C unit should be `C = 1/1.602176634e-19 = 6.2415091e18` so that `e = 1.602176634e−19 C` is respected

fix: Coulombs Unit

---

Core/include/Acts/Utilities/BoundingBox.hpp

I noticed a warning:
```
[715/1093] Building CXX object Tests/UnitTests/Core/Geo...pezoidVolumeBounds.dir/TrapezoidVolumeBoundsTests.cpp.o
In file included from ../Tests/UnitTests/Core/Geometry/TrapezoidVolumeBoundsTests.cpp:13:
In file included from ../Core/include/Acts/Geometry/TrapezoidVolumeBounds.hpp:12:
In file included from ../Core/include/Acts/Geometry/Volume.hpp:15:
../Core/include/Acts/Utilities/BoundingBox.hpp:101:3: warning: definition of implicit copy assignment operator for 'AxisAlignedBoundingBox<Acts::Volume, double, 3>' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy]
AxisAlignedBoundingBox(const self_t& other) = default;
^
../Tests/UnitTests/Core/Geometry/TrapezoidVolumeBoundsTests.cpp:40:6: note: in implicit copy assignment operator for …
```

fix: Clang (13) warning in BoundingBox

---

Core/src/Geometry/CylinderVolumeBounds.cpp
Core/src/Surfaces/CylinderBounds.cpp

Applying transforms to the cylinder did not work as intended. These fixes should place the side disks at the right place as well as fixing the visualization of the cylinder length.

fix: Fix issue with applying transformation to bevelled cylinders

---

Core/include/Acts/Utilities/Helpers.hpp
Tests/UnitTests/Core/Utilities/HelpersTests.cpp

Eigen uses a built-in cost model to determine how it should perform certain matrix operations. In general, this works quite well, but there are some edge cases where Eigen can struggle to output efficient code. An especially apparent instance of this is when multiplying 8x8 matrices, which we do very commonly in operations such as stepping. In these cases, we observe that Eigen emits code for generalized matrix-matrix multiplication, rather than specialized code for small matrices. This adds significant overhead to the matrix multiplication, and it slows down some parts of our code a lot.
Our proposed solution is to implement a wrapper around Eigen's matrix multiplication code that breaks a multiplication down into smaller operations through a technique called blocking. A matrix of size …

feat: Implement blocked matrix multiplication

---

Core/include/Acts/Utilities/Logger.hpp
Tests/UnitTests/Core/Utilities/LoggerTests.cpp

The physics perf monitoring in #1193 runs on the ODD, which currently
throws a number of ERRORs. To circumvent this, this PR allows setting
the threshold through an environment variable, in addition to the
compile time option.
PLEASE FOLLOW THE CHECKLIST BELOW WHEN CREATING A NEW PULL REQUEST. THE
CHECKLIST IS FOR YOUR INFORMATION AND MUST BE REMOVED BEFORE SUBMITTING THE PULL
REQUEST.

feat: Allow setting ACTS_LOG_FAILURE_THRESHOLD at runtime

---

Examples/Python/CMakeLists.txt
Examples/Python/setup.sh.in

This PR adds some changes to enable the python bindings to be used from an install. Instead of `source $BUILD/python/setup.sh` you can now do `source $INSTALL/python/setup.sh`. 
The folder `python` won't make sense if ACTS is installed into a directory alongside other projects, but I would argue in that case you would not want to enable the python bindings anyway.

build: Allow python bindings to be used from install

---

Tests/UnitTests/Core/Utilities/HelpersTests.cpp

As mentioned in #1199, #1184 has ballooned the memory usage of the helper test build. This is because we are instantiating a lot of tests, generating a lot of function calls and types. The amount of tests is, to be honest, a little bit excessive. This commit reduces the number of tests, such that we only test MxN by NxP tests, where M,N,P is 3,3,3, 4,4,4, 8,8,8, and 8,7,4. This should still cover most of the edge cases and use cases.
Closes #1199.

fix: Reduce memory usage of multiplication tests

---

.github/workflows/builds.yml
.github/workflows/checks.yml

Click had a breaking change in a minor version bump `8.0.4` -> `8.1.0` (see https://github.com/tiangolo/typer/issues/377) and black `22.1.0` has an incompatibility with click `8.1.0` (bumping to
`22.3.0` should fix this)

ci: Python fixes

---

.github/semantic.yml
.github/workflows/pr-lint.yml

The app installation was needed to enable this on PRs from forks. With `pull_request_target` it should now be possible to run it in an action.

ci: Use semantic PR action instead of app

---

Examples/Scripts/MaterialMapping/MaterialComposition.cpp

The material composition script now returns `0` on success and `1` on error.

fix: Material composition script: return 0 on success

---

.github/workflows/analysis.yml
.github/workflows/builds.yml
.github/workflows/checks.yml
.gitlab-ci.yml

Bumps to v21 of the docker images for the CI, this should fix the failures seen in the ExaTrkX job.
Also works around [this](https://github.blog/2022-04-12-git-security-vulnerability-announced/) security vulnerability in git, which now requires you to make folders as safe for the search for a top-level `.git` folder.

ci: Bump docker image versions

---

Core/include/Acts/Seeding/SeedFinderOrthogonal.ipp

In the seedFinder we check the compatibility between the (r,z) slope of the two seed segments with a scattering term calculated assuming the minimum pT particle expected to be reconstructed and a second check using a scattering term scaled by the actual measured pT.
As discussed here in PR #1213, there was an error in these cuts. This PR fixes that same error in SeedFinderOrthogonal.

fix: fix scattering calculation in SeedFinderOrthogonal

---

Examples/Python/python/acts/examples/__init__.py
Examples/Scripts/Python/full_chain_itk.py

* Prevent `dump_args_calls` from instrumenting `Interval` and screwing up `TGeoDetector.create()`
* Add a couple of commented-out options to `full_chain_itk.py`:
* show different seeding options
* add `dump_args_calls` to debug Python bindings

fix: prevent debug printout crashing Python TGeoDetector.create()

---

.gitlab-ci.yml
Examples/Scripts/Python/common.py
docs/getting_started.md

This fix the common.py to be able to use the ODD with macOs. It also make the error message a bit more explicite if the path to the ODD factory was not set.

fix: ODD with macOS

---

Core/include/Acts/Seeding/Seedfinder.ipp
Core/include/Acts/Seeding/SeedfinderConfig.hpp
Examples/Python/src/TrackFinding.cpp
Examples/Scripts/Python/itk_seeding.py

This PR splits `deltaRMiddleSPRange ` into `deltaRMiddleMinSPRange ` and `deltaRMiddleMaxSPRange ` so these values can be configured separately.

feat: minimum and maximum values of deltaRMiddleSPRange in check for radial region of interest of middle SP

---

.github/workflows/builds.yml

CI was complaining about mismatch in python minor version in the macos build. this should both bump the version and relax the python requirements. also introduces recent changes in ci-dependencies by @andiwand

ci: Bump macos dependencies

---

CMakeLists.txt
Core/CMakeLists.txt
cmake/ActsCompilerOptions.cmake
docs/getting_started.md
docs/howto/profiling.md

Closes: #1273
This PR adds two new build options: `ACTS_ENABLE_CPU_PROFILING` and `ACTS_ENABLE_MEMORY_PROFILING` that will link libraries and add compile options to enable the use of gperftools' CPU profiler and memory profiler/heap checker respectively. The libraries are linked in the `Core` package as the code here is always built and is the main point of interest for performance profiling.
This PR also adds documentation to `docs/howto` for installing, enabling and using gperftools with ACTS, including some information about basic commands that I found useful when profiling ACTS as well as relevant links.

feat: Add Profiling Support with gperftools

---

Core/include/Acts/EventData/MultiTrajectory.ipp

When accessing `parameters` or `covariance` through the generic accessors (i.e. not `predicted`, `filtered`, or `smoothed`), the public `col()` function should be used instead of direct access to the private `data` member.
Marked WIP until some more tests complete and confirmed working as intended.

fix: `data` is private in MultiTrajectory GrowableColumns

---

Examples/Python/tests/test_examples.py

after having #1298 in we should be able to remove these thresholds
Closes #1215

test: remove kalman smoother related log thresholds

---

Examples/Io/EDM4hep/src/EDM4hepUtil.cpp

The current implementation tries to use the projector on the track parameters. This changes that.
Also, we need to consider what we actually write here. In principle we can do perigees relative to the surface center.

fix: Change edm4hep track state writing to write params

---

thirdparty/actsdd4hep/CMakeLists.txt

This bumps ODD to current main, and the ActsDD4hep glue library to `v1.0.1`.

feat: Bump ODD and ActsDD4hep glue lib

---

Examples/Python/tests/requirements.in
Examples/Python/tests/requirements.txt
Examples/Python/tests/test_examples.py

This test is unfortunately flaky and produces differing output
sometimes. Until we can fix the underlying issue, retry the job.
Example of failure: https://github.com/acts-project/acts/runs/7296836937?check_suite_focus=true
Issue: https://github.com/acts-project/acts/issues/1091

ci: Use rerunfailures to retry the flaky vertexing test

---

Examples/Python/tests/test_reader.py

If you give a single string it iterates over the characters. This might
depend on the DD4hep version.

fix: DD4hepSimulation expected compactFile be a list

---

Core/src/Utilities/Logger.cpp
Examples/Python/python/acts/__init__.py
Examples/Python/src/Base.cpp
Examples/Python/tests/conftest.py
Examples/Python/tests/helpers/__init__.py
Examples/Python/tests/test_examples.py

After some discussion on Mattermost, I'm updating the error reporting strategy for log failure thresholds again.
This PR changes pytest to not fail on init, but it will report a python warning if a compile time threshold is set, and it is not WARNING (as that is the baseline for the majority of python tests). `failure_threshold` (currently only used in the GSF tests) will throw an exception if the target level is different from the current one and the compile time threshold is set.
I also added a way to sort of automatically have tests fail that use subprocess (G4 based tests). Here we use env vars to set the log failure threshold of the child process at runtime.
The python `__init__.py` will check if the `ACTS_LOG_FAILURE_THRESHOLD` environment variable is set to anything else than the …

refactor: Log threshold error reporting

---

Examples/Scripts/Python/exatrkx.py

After #1309, there's an import missing in `exatrkx.py`. This job isn't in the *required* checks, so the PR was merged with this failure.
I think this should fix this.
/cc @tboldagh @benjaminhuth

fix: Add missing import for exatrkx example

---

Examples/Python/python/acts/examples/__init__.py
Examples/Python/python/acts/examples/simulation.py
Examples/Scripts/Python/full_chain_itk.py
Examples/Scripts/Python/seeding.py

Allow preselection of particles before Fatras using `ParticleSelectorConfig()`, eg.
```
s = addFatras(
s, trackingGeometry, field,
ParticleSelectorConfig(
eta=(-4.0, 4.0),
pt=(1 * u.GeV, 10 * u.GeV),
removeNeutral=True,
))
```
This is usually required to use Pythia8 with Fatras.
To this end, an example of using Pythia8 to generate ttbar + mu=200 pile-up is included (commented-out) in `full_chain_itk.py`.

feat: addFatras preselectParticles config for ParticleSelector

---

Examples/Scripts/TrackingPerformance/boundParamResolution.C

In the rare case of `(smoothed or filtered) == false` the residual plots accumulated with each layer, instead of only using the current layer.
After changing the hardcoded `"same"` to `drawOptions.c_str()`, as in all other places, this bug is fixed.

fix: accumulating residual plots in boundParamResolution if only `predicted==true`

---

Examples/Scripts/Python/full_chain_itk.py

For ttbar + PU200 example code (commented out in `full_chain_itk.py`), change particle selector pT > 1 GeV to pT > 0.15 GeV.
This change allows lower momentum particles to be included in the simulation. They may not be reconstructed and certainly won't be included in the efficiency calculation, but do provide more realistic hits in the detector to test the pattern recognition. @asalzburger suggested Fatras should still be able to cope with 150 MeV.
Note, that this is in code that is commented out in the example script. The PR merely provides a better example for anyone wanting to test ITk with ttbar and pile-up.

fix: improve Python full-chain ITk example

---

.github/workflows/backport.yml
.kodiak.toml

This PR should configure a backport action that can be triggered via
labels. The action will create a backport PR targetting the branch
specified in the label. Kodiak's config has been updated to deal with
this nicely (hopefully).

ci: Set up backport action that reacts to labels

---

.github/workflows/builds.yml

It's too much work to get the macOS job to build correctly for that old release, so I'm removing it for that series.

ci: Disable macOS job in v9.1.x

---

.clang-tidy
CI/clang_tidy/limits.yml
Examples/Algorithms/Geant4/src/DDG4DetectorConstruction.cpp
Examples/Detectors/DD4hepDetector/src/DD4hepGeometryService.cpp
Examples/Scripts/MaterialMapping/MaterialComposition.cpp
Examples/Scripts/TrackingPerformance/ResidualsAndPulls.cpp
Examples/Scripts/TrackingPerformance/TrackSummary.cpp
Fatras/Geant4/src/DummyDetectorConstruction.cpp
Tests/IntegrationTests/Legacy/ATLSeedingIntegrationTest.cpp

Backport 789ce6962892025d24dd08ae87766c4e6543a632 from #1358.
---
This enables the `modernize-use-nullptr` check in clang-tidy. This prevents using `0` for a null pointer.
This PR also changes `0` to `nullptr` wherever already used as a null pointer.

chore: clang-tidy modernize-use-nullptr [backport #1358 to develop/v19.x]

---

Core/include/Acts/Vertexing/HelicalTrackLinearizer.ipp

Backport 8639c37faff32a288e2417df0a7f099131132b35 from #1363.
---
Previously the `HelicalTrackLinearizer` assumed that the vertex we are fitting has to be reachable by back propagation. This is not always the case. In this PR we try to estimate the direction in which we will find the vertex and use it for the propagation.
@asalzburger mentioned that it would be good to back propagate from the first measurement of the particle on the track as this will always be "ahead" of the vertex
cc @paulgessinger

fix: any direction for helical track linearizer [backport #1363 to develop/v19.x]

---

Core/include/Acts/Geometry/detail/Layer.ipp
Core/include/Acts/Propagator/detail/SteppingHelper.hpp
Core/include/Acts/Utilities/Intersection.hpp
Core/src/Geometry/TrackingVolume.cpp

Backport 34adc81917fb6700e2c621414151f6008327f199 from #1107.
---
I think I found actually two small bugs in the `updateSingleSurfaceStatus` function:
1) The first one is older I think: when `pLimit == cLimit + s_onSurfaceTolerance`, then the intersection is not accepted, but there is also no message printed out, because it is only checkt for `<` and `>`, but one should be `<=` or `>=` in this case I think.
2) With the `s_onSurfaceTolerance`, I think we do not compare what we accually want here anymore:
What we check is something like `a*a < b*b + c`, but what we (I think) want to check is `|a| < |b| + c`. This is obviously not the same (e.g. with a=4, b=3, c=2).
So I know also added `std::abs` in the computation of the `accept`-boolean. Not sure if that is the best way, since it seems …

fix: Comparison bug in updateSingleSurfaceStatus [backport #1107 to develop/v9.1.x]

---

.github/workflows/builds.yml
.github/workflows/docs.yml
.merge-sentinel.yml

This should skip all the build jobs if only files inside docs were changed. Once merged, in principle merge-sentinel should only require the correct jobs 🤞

ci: Do not run build jobs on docs-only changes

---

.github/workflows/analysis.yml
.github/workflows/builds.yml

I had a typo in the previous yml file changes. This should make the default jobs run again.

ci: Fix path-ignore for docs

---

Core/src/Geometry/TrackingVolume.cpp

Backport 67afb407cae99d38c5ac061abb4d86aae1e67ce3 from #1115.
---
I noticed in #1103 that the navigation failed in backward mode after we merged #1107.
Indeed, during the change in #1107, `TrackingVolume` lost a line that copied the sign from the navigation direction onto the path length in `compatibleBoundaries`. This made the navigation go haywire when it tried to target boundaries in reverse propagation mode.
This PR adds that back in, and should fix #1103's test runs.

fix: TrackingVolume intersection check didn't copy sign [backport #1115 to develop/v9.1.x]

---

Core/include/Acts/Utilities/Delegate.hpp
Tests/UnitTests/Core/Utilities/DelegateTests.cpp

This PR adds functionality to the `Acts::Delegate`, that enables to construct, assign and connect stateful lambdas like this:
```c++
int n = 0;
auto lambda = [&](){ ++n; };
Acts::Delegate<void()> d(lambda);
d = lambda;
d.connect(lambda);
```
The use of temporary stateful lambdas is forbidden due to deleted overloads with `Callable &&`:
```c++
Acts::Delegate<void()> d([&](){ ++n; }); // compile error
```
I havn't checked yet if this can simplify code somewhere in Core or Examples, but I ran in situations myself where this would be useful.

feat: Enable Delegates to conveniently use stateful lambdas

---

Core/include/Acts/Propagator/MultiEigenStepperLoop.hpp
Core/include/Acts/Propagator/MultiEigenStepperLoop.ipp
Core/include/Acts/Propagator/MultiStepperError.hpp
Core/src/Propagator/MultiStepperError.cpp
Tests/UnitTests/Core/Propagator/MultiStepperTests.cpp

Backport 1b973d52cbd015bc0ef746f7a73b195ac5a8ae5e from #1339.
---
This PR does refactor the `MultiEigenStepperLoop` and fixes a situation, where a few stepping-erros could break the whole propagation.
- **Fix:** If some components had stepping errors and all other components where on a surface, the propagation terminated
- **Refactor:**
- remove internal logger from `MultiEigenStepperLoop` since it is not really configurable from outside
- improve `MultiEigenStepperLoop::step` (only construct summary-string in `VERBOSE` mode or on error, remove unnecessary loops and vectors, move things to lambdas, ...)
**NOTE:** This does not fix the reason why stepping errors occur in some situations, this (hopefully) will be done in a subsequent PR)

fix: Multi-Stepper stepping error in multiple components + refactoring [backport #1339 to develop/v19.x]

---

Core/include/Acts/Utilities/Delegate.hpp
Tests/UnitTests/Core/Utilities/DelegateTests.cpp

Backport f6731263d4ead325f67348c98a0a34eae30bb4ec from #1410.
---
This PR adds functionality to the `Acts::Delegate`, that enables to construct, assign and connect stateful lambdas like this:
```c++
int n = 0;
auto lambda = [&](){ ++n; };
Acts::Delegate<void()> d(lambda);
d = lambda;
d.connect(lambda);
```
The use of temporary stateful lambdas is forbidden due to deleted overloads with `Callable &&`:
```c++
Acts::Delegate<void()> d([&](){ ++n; }); // compile error
```
I havn't checked yet if this can simplify code somewhere in Core or Examples, but I ran in situations myself where this would be useful.

feat: Enable Delegates to conveniently use stateful lambdas [backport #1410 to develop/v19.x]

---

Examples/Framework/include/ActsExamples/Framework/WhiteBoard.hpp

Backport fdc6075366aa7020dfeba1c1676e834b95206b16 from #1409.
---
This PR changes the way we check for compatibility in the `WhiteBoard` as sometimes the typeid check would fail, even if the cast would work.
The reason for the failure is not fully understood, but a `dynamic_cast` is ok in this case, as this is not a time-critical operation.

fix: change typeid check to dynamic_cast [backport #1409 to develop/v19.x]

---

Examples/Python/python/acts/_adapter.py
Examples/Python/python/acts/examples/__init__.py
Examples/Python/python/acts/examples/reconstruction.py
Examples/Scripts/Python/full_chain_odd.py

* Improves how `acts.examples.dump_args_calls()` finds the `acts.ActsPythonBindings` functions to wrap with `dump_args()`. This should now find them all.
* I've used it with `full_chain_itk.py`, `full_chain_odd.py`, and `vertex_fitting.py`
* For brevity, `dump_args()` doesn't print `Config()` calls with no arguments.
* fix for `addSeeding(truthSeedRanges=None)` (unrelated, except the above helped debug)

refactor: Improve ActsPythonBindings tracing

---

Examples/Python/python/acts/_adapter.py
Examples/Python/python/acts/examples/__init__.py
Examples/Python/python/acts/examples/reconstruction.py
Examples/Scripts/Python/full_chain_odd.py

Backport b945729b1751cb2e991fc5f5538769ca3bfb294a from #1425.
---
* Improves how `acts.examples.dump_args_calls()` finds the `acts.ActsPythonBindings` functions to wrap with `dump_args()`. This should now find them all.
* I've used it with `full_chain_itk.py`, `full_chain_odd.py`, and `vertex_fitting.py`
* For brevity, `dump_args()` doesn't print `Config()` calls with no arguments.
* fix for `addSeeding(truthSeedRanges=None)` (unrelated, except the above helped debug)

refactor: Improve ActsPythonBindings tracing [backport #1425 to develop/v19.x]

---

docs/conf.py

I suspect this might have been failing our docs build for a while.

docs: Use DEVNULL instead of PIPE in apidoc subprocess

---

docs/conf.py

Backport d9117a0c595651461af9f9685fdfe5e5637c8a3f from #1431.
---
I suspect this might have been failing our docs build for a while.

docs: Use DEVNULL instead of PIPE in apidoc subprocess [backport #1431 to develop/v19.x]

---

Core/include/Acts/Definitions/Common.hpp
Core/include/Acts/Propagator/AtlasStepper.hpp
Core/include/Acts/Propagator/ConstrainedStep.hpp
Core/include/Acts/Propagator/EigenStepper.hpp
Core/include/Acts/Propagator/EigenStepper.ipp
Core/include/Acts/Propagator/StandardAborters.hpp
Core/include/Acts/Propagator/StraightLineStepper.hpp
Core/include/Acts/Propagator/detail/SteppingLogger.hpp
Tests/UnitTests/Core/Propagator/AbortListTests.cpp
Tests/UnitTests/Core/Propagator/ActionListTests.cpp
Tests/UnitTests/Core/Propagator/AtlasStepperTests.cpp
Tests/UnitTests/Core/Propagator/ConstrainedStepTests.cpp
Tests/UnitTests/Core/Propagator/NavigatorTests.cpp
Tests/UnitTests/Core/Propagator/StepperTests.cpp
Tests/UnitTests/Core/Propagator/StraightLineStepperTests.cpp

Backport 8f77ccf453310655c3050183073b9b59bd9761cf from #1347.
---
while working on https://github.com/acts-project/acts/issues/1345 I stumbled across `ConstrainedStep` and the way how it converts to a Scalar. I believe there are cases where it will return `+/- max` which will break the propagation
similar to https://github.com/acts-project/acts/pull/1346 but more intrusive and meant to fix the underlying bug
in this PR I rearranged the code and added a few short hands for common code in `ConstrainedStep`

refactor: Change ConstrainedStep to be explicit [backport of #1347 to develop/v9.1.x]

---

Core/src/Geometry/TrackingVolume.cpp

Backport 7ca1bb859256a2610ea52eebaac2ce99c4611506 from #1433.
---
trying to fix a bug discovered with fatras here https://github.com/acts-project/acts/issues/1385
in some special cases the propagation will get stuck in a loop as the navigator is flip-flopping the target boundary of two volumes. one ahead and one behind.
these changes reorder the priority of the boundaries. first we will target everything in propagation direction and only if there are none left we will allow opposite direction

fix: navigator priority with negative boundary distance [backport #1433 to develop/v19.x]

---

.github/workflows/builds.yml

This should hopefully fix the build failures.

ci: Update macOS CI dependencies

---

Examples/Python/python/acts/examples/reconstruction.py

`addCKFTracks(writeTrajectories=False)` disables writing potentially enormous `trackstates_ckf.root` and `tracksummary_ckf.root` ntuples, while still producing histograms in `performance_ckf.root`.

feat: addCKFTracks option to disable some output

---

Examples/Algorithms/TrackFitting/include/ActsExamples/TrackFitting/SurfaceSortingAlgorithm.hpp
Examples/Algorithms/TrackFitting/src/SurfaceSortingAlgorithm.cpp
Examples/Python/python/acts/examples/reconstruction.py
Examples/Python/src/TrackFitting.cpp
Examples/Run/Alignment/Common/DetectorAlignment.cpp
Examples/Run/Reconstruction/Common/RecTruthTracks.cpp
Examples/Run/Reconstruction/ExaTrkX/TrackFindingExaTrkXGeneric.cpp

rename `SimulatedHits` vs `SimHits`

refactor: consistent naming for simhits

---

Examples/Algorithms/TrackFitting/include/ActsExamples/TrackFitting/SurfaceSortingAlgorithm.hpp
Examples/Algorithms/TrackFitting/src/SurfaceSortingAlgorithm.cpp
Examples/Python/python/acts/examples/reconstruction.py
Examples/Python/src/TrackFitting.cpp
Examples/Run/Alignment/Common/DetectorAlignment.cpp
Examples/Run/Reconstruction/Common/RecTruthTracks.cpp
Examples/Run/Reconstruction/ExaTrkX/TrackFindingExaTrkXGeneric.cpp

Backport 50ad783b8424d44ad1cc6be4a2096e051f016d3e from #1451.
---
rename `SimulatedHits` vs `SimHits`

refactor: consistent naming for simhits [backport #1451 to develop/v19.x]

---

CI/physmon/physmon.py
Examples/Python/python/acts/examples/reconstruction.py
Examples/Python/python/acts/examples/simulation.py
Examples/Python/tests/test_examples.py
Examples/Scripts/Python/ckf_tracks.py
Examples/Scripts/Python/digitization.py
Examples/Scripts/Python/exatrkx.py
Examples/Scripts/Python/fatras.py
Examples/Scripts/Python/full_chain_itk.py
Examples/Scripts/Python/full_chain_odd.py
Examples/Scripts/Python/geant4.py
Examples/Scripts/Python/particle_gun.py
Examples/Scripts/Python/pythia8.py
Examples/Scripts/Python/seeding.py
Examples/Scripts/Python/truth_tracking_gsf.py
Examples/Scripts/Python/truth_tracking_kalman.py
Examples/Scripts/Python/vertex_fitting.py

Backport afb91a583e6db641c9b39354c7494da5726b8681 from #1404.
---
after working on the full chain doc I wondered why we do `s = addSomething(s, ...)` all the time. to me it looks kind of confusing as the reader might think `s` is changing every time we add something.
maybe we want to remove the return value of the add functions completely? @paulgessinger @timadye

refactor: no return for add* python helpers [backport #1404 to develop/v19.x]

---

Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/TrackFindingAlgorithm.hpp
Examples/Algorithms/TrackFinding/src/TrackFindingAlgorithm.cpp
Examples/Framework/include/ActsExamples/Framework/BareAlgorithm.hpp
Examples/Framework/include/ActsExamples/Framework/IAlgorithm.hpp
Examples/Framework/src/Framework/Sequencer.cpp
Examples/Python/src/ModuleEntry.cpp

While working on #1417, I was missing a way for an algorithm to collect performance numbers while running (thread-safe) and printing them when finalizing. I believe this is going to be more and more important, so this PR is adding simple `initialize` and `finalize` methods to our algorithm interface. They are defaulted by `BareAlgorithm` so all other algorithms don't necessarily have to implement.
This PR uses this mechanism to add some output on the number of failed seeds to the end of the TrackFindingAlgorithm, but there should be more cases where this will be helpful.

feat: Algorithm lifecycle methods: initialize & finalize

---

Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/TrackFindingAlgorithm.hpp
Examples/Algorithms/TrackFinding/src/TrackFindingAlgorithm.cpp
Examples/Framework/include/ActsExamples/Framework/BareAlgorithm.hpp
Examples/Framework/include/ActsExamples/Framework/IAlgorithm.hpp
Examples/Framework/src/Framework/Sequencer.cpp
Examples/Python/src/ModuleEntry.cpp

Backport 6410b0d3396ea6b69850c1eb1d1669d36e972bde from #1459.
---
While working on #1417, I was missing a way for an algorithm to collect performance numbers while running (thread-safe) and printing them when finalizing. I believe this is going to be more and more important, so this PR is adding simple `initialize` and `finalize` methods to our algorithm interface. They are defaulted by `BareAlgorithm` so all other algorithms don't necessarily have to implement.
This PR uses this mechanism to add some output on the number of failed seeds to the end of the TrackFindingAlgorithm, but there should be more cases where this will be helpful.

feat: Algorithm lifecycle methods: initialize & finalize [backport #1459 to develop/v19.x]

---

Core/include/Acts/Geometry/GeometryObjectSorter.hpp

Backport 7135dc8e2233498c6ccc3d6a25941874c6110687 from #1474.
---
My newest `gcc` warns about some code is inheriting from `std::binary_function`, which is indeed deprecated since C++11 and officially removed in C++17 (https://en.cppreference.com/w/cpp/utility/functional/binary_function), so maybe we should get rid of it.
It seems enough to just remove the inheritance, so its a pretty easy fix.

refactor: Remove dependency on deprecated std::binary_function [backport #1474 to develop/v19.x]

---

Tests/UnitTests/Core/Utilities/BoundingBoxTest.cpp
Tests/UnitTests/Core/Utilities/CMakeLists.txt

Use a temporary directory to store visualization outputs from the BoundingBox test.

test: Use tempdir to produce BB vis output

---

Core/include/Acts/Utilities/BinningType.hpp

Setting `s_binningValues` as `const` as well. The Atlas Thread-check is complaining about this since it suspect this may be not thread safe.

fix: Set s_binningValues as const

---

Core/include/Acts/Seeding/SeedfinderConfig.hpp
Examples/Algorithms/TrackFinding/src/SeedingAlgorithm.cpp

Backport c1dda470d82bf479e21e4488339351b340f63022 from #1378.
---
This changes the initialisation of `deltaRMinTopSP`, `deltaRMaxTopSP`, `deltaRMinBottomSP` and `deltaRMaxBottomSP` to quiet_NaN. If the user does not configure these values, they take the values of `deltaRMin` and `deltaRMax`.
I think this makes the configuration easier and avoids errors when the user wants to use the same values for top and bottom.
@robertlangenberg

feat: Checks for configuration of delta R values in seed finder [backport #1378 to develop/v19.x]

---

.github/workflows/docs.yml

Instead of exiting at the first warning that's treated as error, doxygen
will continue processing and exit fith a non-zero status code. This has
the benefit that all WARNINGs are visible at the same time.

docs: Switch to doxygen FAIL_ON_WARNINGS

---

Core/include/Acts/Vertexing/HelicalTrackLinearizer.ipp

Backport 8639c37faff32a288e2417df0a7f099131132b35 from #1363
---
Previously the `HelicalTrackLinearizer` assumed that the vertex we are fitting has to be reachable by back propagation. This is not always the case. In this PR we try to estimate the direction in which we will find the vertex and use it for the propagation.

fix: any direction for helical track linearizer [backport #1363 to develop/v9.1.x]

---

.github/workflows/builds.yml

Backport of 9587b8dc577b2c8bbf6cd922b945dd6431c7d17d from #1445 
---
Fix build failures for macOS

ci: Update macOS CI dependencies [backport of #1445 to develop/v19.0.x]

---

.gitlab-ci.yml

Backport 190d85b5e4fde34d0bcc0bf1bf728ba6ca7722f6 from #1252
---
Test if the ci job runs on the new a4000 GPU

ci: Fix GPU CI on A4000 [backport of #1252 to develop/v19.0.x]

---

Core/include/Acts/Definitions/Common.hpp
Core/include/Acts/Propagator/AtlasStepper.hpp
Core/include/Acts/Propagator/ConstrainedStep.hpp
Core/include/Acts/Propagator/EigenStepper.hpp
Core/include/Acts/Propagator/EigenStepper.ipp
Core/include/Acts/Propagator/StandardAborters.hpp
Core/include/Acts/Propagator/StraightLineStepper.hpp
Core/include/Acts/Propagator/detail/SteppingLogger.hpp
Tests/UnitTests/Core/Propagator/AbortListTests.cpp
Tests/UnitTests/Core/Propagator/ActionListTests.cpp
Tests/UnitTests/Core/Propagator/AtlasStepperTests.cpp
Tests/UnitTests/Core/Propagator/ConstrainedStepTests.cpp
Tests/UnitTests/Core/Propagator/NavigatorTests.cpp
Tests/UnitTests/Core/Propagator/StepperTests.cpp
Tests/UnitTests/Core/Propagator/StraightLineStepperTests.cpp

Backport 0c76d370479a4511bd399800100b18984bae00cc from #1347
---
while working on https://github.com/acts-project/acts/issues/1345 I stumbled across `ConstrainedStep` and the way how it converts to a Scalar. I believe there are cases where it will return `+/- max` which will break the propagation
similar to #1346 but more intrusive and meant to fix the underlying bug
in this PR I rearranged the code and added a few short hands for common code in `ConstrainedStep`

refactor: Change ConstrainedStep to be explicit [backport #1347 to develop/v19.0.x]

---

Examples/Framework/src/Framework/Sequencer.cpp

This was not happening due to a type previously.

fix: Sequencer correctly calls algorithm finalize

---

Core/include/Acts/TrackFitting/GaussianSumFitter.hpp
Core/include/Acts/Utilities/Result.hpp

Allows accessing the content of `Acts::Result` similar to `std::optional` with `res->foo`.
Additional, changes the comment style from `/* .. */` to `///` for the documentation as elsewhere in Acts.

feat: Add operator -> to Acts::Result

---

Examples/Framework/src/Framework/Sequencer.cpp

Backport 487a6cc58b9a5075575210d15f2b6485eb629219 from #1514.
---
This was not happening due to a type previously.

fix: Sequencer correctly calls algorithm finalize [backport #1514 to develop/v19.x]

---

Core/include/Acts/Seeding/SeedFinderOrthogonal.ipp
Core/include/Acts/Seeding/SeedFinderOrthogonalConfig.hpp
Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/SeedingOrthogonalAlgorithm.hpp
Examples/Algorithms/TrackFinding/src/SeedingOrthogonalAlgorithm.cpp
Examples/Python/python/acts/examples/reconstruction.py
Examples/Python/src/TrackFinding.cpp

Backport d54fa8491d7ef14e2c298418b289028310206794 from #1471.
---
This PR splits `deltaRMin` and `deltaRMax` in seedfinderOrthogonal into `deltaRMinBottomSP`, `deltaRMinTopSP`, `deltaRMaxBottomSP` and `deltaRMinTopSP` and allows for different deltaR values for the middle-bottom and middle-top duplets.

feat: split deltaR in seedFinderOrthogonal [backport #1471 to develop/v19.x]

---

Examples/Python/python/acts/examples/reconstruction.py

Backport 48f299336da30a4e79a5de923111a21c0223d1a5 from #1447
---
`addCKFTracks(writeTrajectories=False)` disables writing potentially enormous `trackstates_ckf.root` and `tracksummary_ckf.root` ntuples, while still producing histograms in `performance_ckf.root`.

feat: addCKFTracks option to disable some output [backport of #1447 to develop/v19.x]

---

Examples/Python/python/acts/examples/__init__.py
Examples/Python/python/acts/examples/itk.py
Examples/Python/python/acts/examples/odd.py
Examples/Python/python/acts/examples/reconstruction.py
Examples/Python/python/acts/examples/simulation.py

Backport 433a379bf53912a5ef3d515ebb23f2bf3d1af331 from #1448
---
I noticed that some python `add*` functions provide a mechanism to overwrite the `logLevel` but others don't which made me change `reconstruction.py` locally from time to time
I tried to generalize the existing functionality and extract it into a helper function. then I applied it to all the `add*` functions
after some [discussion](https://github.com/acts-project/acts/pull/1448#issuecomment-1225324331) I removed `dump_args_calls` from the `add*` functions as this can have side effects and break the CI

refactor: python examples log level overwrite mechanism [backport of #1448 to develop/v19.x]

---

Core/include/Acts/TrackFitting/GaussianSumFitter.hpp
Core/include/Acts/Utilities/Result.hpp

Backport of 91a1e8747282a066ff022efe68297ac98a61f57a from #1509 
---
Allows accessing the content of `Acts::Result` similar to `std::optional` with `res->foo`.
Additional, changes the comment style from `/* .. */` to `///` for the documentation as elsewhere in Acts.

feat: Add operator -> to Acts::Result [backport #1509 to develop/v19.x]

---

README.md
docs/getting_started.md

Our first quick-start command
```
git clone --recursive https://github.com/acts-project/acts
```
doesn't work out of the box for many (most?) people, because `--recursive` checks out `thirdparty/OpenDataDetector`, which requires `git-lfs`, which isn't usually installed by default. It's on lxplus, but I didn't find it anywhere else by default.
I propose to remove the `--recursive` option in the quick-start docs. The [ODD quick-start](https://acts.readthedocs.io/en/latest/getting_started.html#the-opendatadetector) already explains `git submodule`, so there is no assumption that the user has already used `git clone --recursive`. Maybe this could also add a link to `git lfs` (I'll see about a small update).
An alternative would be to add `git-lfs` to the list of dependencies, but this could …

docs: remove --recursive on git clone in quick start docs

---

Core/include/Acts/Geometry/Extent.hpp
Core/include/Acts/Utilities/BinningType.hpp
Core/include/Acts/Utilities/Enumerate.hpp
Core/src/Geometry/Extent.cpp
Core/src/Geometry/Polyhedron.cpp
Core/src/Geometry/ProtoLayerHelper.cpp
Examples/Algorithms/TrackFinding/src/SeedingAlgorithm.cpp
Plugins/DD4hep/src/DD4hepLayerBuilder.cpp
Tests/UnitTests/Core/Geometry/ExtentTests.cpp
Tests/UnitTests/Core/Geometry/LayerCreatorTests.cpp
Tests/UnitTests/Core/Geometry/ProtoLayerTests.cpp
Tests/UnitTests/Core/Surfaces/CylinderSurfaceTests.cpp
Tests/UnitTests/Core/Surfaces/PolyhedronSurfacesTests.cpp

Backport 81e9573deab82bb96645ad3a8d48800d535db527 from #1424.
---
This PR uses the later introduced `Range1D<>` class in the `Geometry/Extent` class instead of duplication of the code concerning intersection, min/max, shrinking.
As a direct consequence, the code becomes more readable, by explicitly calling `range(binValue).min()` instead of `ranges[binValue].first` when the meaning of first is not clear from the context.

feat: use Range1D<> class for extent [backport #1424 to develop/v19.x]

---

Examples/Scripts/Python/full_chain_itk.py

Backport b99368a581df64aaa03e2b25a998b155cc4c57ab from #1513.
---
* `full_chain_itk.py` can now run ttbar+PU200 selected by a flag (`ttbar_pu200`), rather than commented-out code.
* Remove truth selection for particle gun. This is not needed and can give problems if a lower generated pT range is selected.
* Remove previously commented-out `SeedingAlgorithm.TruthEstimated` and `SeedingAlgorithm.TruthSmeared` options.
* simplify imports

refactor: improve full_chain_itk.py example [backport #1513 to develop/v19.x]

---

Core/include/Acts/SpacePointFormation/detail/SpacePointBuilder.ipp

My new GCC does emit a `-Wmaybe-uninitialized` warning in the `SpacePointBuilder.ipp`. Indeed, in the Error case (the `else` branch in the `buildSpacePoint` function) the values `gpos` and `gCov` seems to stay uninitialized.
I'm not sure if zero initialization is actually the best thing to do here (maybe @toyamaza can comment on that), maybe return a `Result<void>` could  also be an option?

fix: maybe-uninitialized warning in SpacepointBuilder

---

Core/include/Acts/SpacePointFormation/detail/SpacePointBuilder.ipp

Backport f3b20f70284ab6e210f3c4681d08370750fdf010 from #1543.
---
My new GCC does emit a `-Wmaybe-uninitialized` warning in the `SpacePointBuilder.ipp`. Indeed, in the Error case (the `else` branch in the `buildSpacePoint` function) the values `gpos` and `gCov` seems to stay uninitialized.
I'm not sure if zero initialization is actually the best thing to do here (maybe @toyamaza can comment on that), maybe return a `Result<void>` could  also be an option?

fix: maybe-uninitialized warning in SpacepointBuilder [backport #1543 to develop/v19.x]

---

CI/physmon/physmon.py
Examples/Python/python/acts/examples/reconstruction.py
Examples/Scripts/Python/full_chain_odd.py
Examples/Scripts/Python/vertex_fitting.py

follow-up of https://github.com/acts-project/acts/pull/1538
@timadye noticed that we have to use `s.addAlgorithm(acts.examples.TrackSelector(...` in the full chain examples in order to have vertexing. this PR integrates the track selection into the `addVertexFitting` helper

refactor: use TrackSelector in addVertexFitting

---

.github/workflows/builds.yml
CI/physmon/phys_perf_mon.sh

Backport of 48a155c03198a8a645b200117a12c0ba889150b4 from #1556
---
This intends to fix the issue seen in #1541, along with some other improvements. The CI should be green on this one, otherwise I have to go back and fix histcmp accordingly.

ci: Bump histcmp to v0.5.1 [backport of #1556 to develop/v19.x]

---

CI/physmon/physmon.py
Examples/Python/python/acts/examples/reconstruction.py
Examples/Scripts/Python/full_chain_itk.py
Examples/Scripts/Python/full_chain_odd.py
Examples/Scripts/Python/vertex_fitting.py

Backport da71b1cf54c2e9a8802f9e78e6b9b293c8b3dd7e from #1545.
---
follow-up of https://github.com/acts-project/acts/pull/1538
@timadye noticed that we have to use `s.addAlgorithm(acts.examples.TrackSelector(...` in the full chain examples in order to have vertexing. this PR integrates the track selection into the `addVertexFitting` helper

refactor: use TrackSelector in addVertexFitting [backport #1545 to develop/v19.x]

---

Examples/Io/Performance/ActsExamples/Io/Performance/CKFPerformanceWriter.cpp

#1541 introduced a few clang-tidy warnings that weren't caught. This PR fixes those

fix: Clang-tidy warnings

---

Core/include/Acts/Seeding/SeedFinderOrthogonal.ipp

As pointed out in #1557, the existing orthogonal seed finding code uses the `SimSpacePoint` from the ACTS examples namespace, which should not be used in the ACTS core. This commit gets rid of the uses of this type.
Fixes #1557.

fix: Remove example spacepoint from seeding code

---

Core/include/Acts/Seeding/SeedFinderOrthogonal.ipp

Backport e693aed2be9e0433c93a89f2f1fda830e757f360 from #1564.
---
As pointed out in #1557, the existing orthogonal seed finding code uses the `SimSpacePoint` from the ACTS examples namespace, which should not be used in the ACTS core. This commit gets rid of the uses of this type.
Fixes #1557.

fix: Remove example spacepoint from seeding code [backport #1564 to develop/v19.x]

---

.github/workflows/builds.yml

Backport of 465fe6fa692aa672091c8eb1dac02a28abeb015c from #1583 
---
This is because the python version got out of sync again.

ci: Bump macOS dependencies again [backport #1583 to develop/v19.x]

---

Core/include/Acts/TrackFitting/KalmanFitter.hpp

Backport cd5da0c203c4daebc8eb5b57981373706cf2c985 from #1581.
---
This is a super small PR, that additionally prints some information in the KF verbose logger, I believe the current position of the propagation is a missing information there. I need this very often, e.g. during the debugging of the GSF and have it there in all my local branches.
I would like it to add this to the main branch, since it shouldn't cost performance and then I do not need to add this always manually.

refactor: Improve verbose logging in Kalman Filter [backport #1581 to develop/v19.x]

---

Examples/Scripts/TrackingPerformance/ResidualsAndPulls.cpp
Examples/Scripts/TrackingPerformance/TrackSummary.cpp

Backport 1941fbc99046a2b7fadff62778bd375a7cd56579 from #1570.
---
The analysis scripts could fail with `boost::any_cast` errors if some arguments where not provided. However, what arguments exactely could only be found out in the source code.
This adds a few required flags that explicitly say what is needed.

fix: Add required flags to cmdline args in analysis scripts [backport #1570 to develop/v19.x]

---

Core/include/Acts/Seeding/Seedfinder.ipp

break loop over triplets if reached the last top SP in seed finder to avoid unnecessary calculations

feat: break loop over triplets in seed finder

---

docs/core/seeding.md

By mistake I forgot to add a caption to one of the figures from #1476

docs: fix caption of figure in seeding documentation

---

.github/workflows/builds.yml

with https://github.com/acts-project/ci-dependencies/pull/12 I added a specific python version to the macos ci dependencies which hopefully resolves the root/dd4hep issue for now

ci: update macos deps

---

CMakeLists.txt

set `ACTS_BUILD_EXAMPLES` if `ACTS_BUILD_EXAMPLES_PYTHON_BINDINGS`

fix: enable examples if python examples are enabled

---

Core/include/Acts/Seeding/SeedConfirmationRangeConfig.hpp
Core/include/Acts/Seeding/SeedFilter.ipp
Core/include/Acts/Seeding/SeedFilterConfig.hpp
Examples/Python/python/acts/examples/itk.py
Examples/Python/src/TrackFinding.cpp

This PR moves some variables related to seed confirmation from `seedFilterConfig` to `seedConfirmationRangeConfig` and makes them configurable in python

refactor: configurable variables in seed confirmation

---

Examples/Python/python/acts/examples/reconstruction.py

https://github.com/acts-project/acts/pull/1579/ remove the track selector from `addVertexing` which is still required. see https://github.com/acts-project/acts/pull/1636
https://github.com/acts-project/acts/pull/1588 should clean this up a little

feat: examples restore vertexing track selector

---

Examples/Io/Csv/CMakeLists.txt
Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvBFieldWriter.hpp
Examples/Io/Csv/src/CsvBFieldWriter.cpp
Examples/Python/src/Output.cpp
Examples/Scripts/Python/bfield_writing.py

This PR adds a new example tool, `CsvBFieldWriter`, that dumps a B-field to disk in CSV format. The tool supports both grid-based and non-grid-based vector fields, it supports Cartesian and symmetrical cylindrical coordinates, and it supports user-specified ranges and bin counts.
Comes with free Python bindings.

feat: Add a tool for writing B-fields to disk in CSV format

---

Examples/Python/python/acts/examples/itk.py

New element names in `buildITkGeometry` for updated ATLAS ITk and HGTD geometry, `ATLAS-P2-RUN4-01-00-00`.
This supports the new geometry TGeo root file just added to the [`acts-itk`](https://gitlab.cern.ch/atlas/acts-itk) repo.
* Note that without this PR, the latest version of `acts-itk` (tag [`ATLAS-P2-RUN4-01-00-00`](https://gitlab.cern.ch/atlas/acts-itk/-/tree/ATLAS-P2-RUN4-01-00-00)) will not work. `acts-itk` tag [`ATLAS-P2-23`](https://gitlab.cern.ch/atlas/acts-itk/-/tree/ATLAS-P2-23) can be used instead.
* With this PR, `acts-itk` [`master`](https://gitlab.cern.ch/atlas/acts-itk) (or tag [`ATLAS-P2-RUN4-01-00-00`](https://gitlab.cern.ch/atlas/acts-itk/-/tree/ATLAS-P2-RUN4-01-00-00)) should be used.
* The error message from `itk.py` indicating a version mismatch is:
```
ValueError: …
```

refactor: required for new ITk geometry

---

Examples/Io/Csv/src/CsvOutputData.hpp
Examples/Io/Csv/src/CsvTrackingGeometryWriter.cpp

This is needed by the Exa.TrkX data reader. This was once part of ACTS, but was removed (not sure why).

feat: Add thickness and pitch again to csv geometry writing

---

Core/include/Acts/EventData/MultiTrajectory.hpp
Core/include/Acts/EventData/MultiTrajectory.ipp

If not checked, this leads to a segfault by trying to access the proxy or the previous proxy.

refactor: Add precondition check for MTJ `applyBackward` and `visitBackwards`

---

Examples/Detectors/TelescopeDetector/include/ActsExamples/TelescopeDetector/TelescopeDetector.hpp
Examples/Detectors/TelescopeDetector/src/TelescopeDetector.cpp
Examples/Python/src/Detector.cpp
Examples/Python/tests/test_detectors.py

This fixes the telescope detector which was not working anymore after the last clang-tidy changes.

fix: telescope detector python binding + add test

---

Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/DefaultHoughFunctions.hpp
Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/HoughTransformSeeder.hpp
Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/HoughVectors.hpp
Examples/Run/Reconstruction/Common/HoughExample.cpp
Examples/Run/Reconstruction/Common/HoughExample.hpp

based on https://github.com/acts-project/acts/pull/1305
clang tidy fixes

fix: Hough Transform first implementation clang-tidy

---

Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.ipp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFitter.ipp

reduce AMVF logging lines by transposing vectors before printing

refactor: transpose vectors in AMVF logging

---

Core/include/Acts/EventData/VectorMultiTrajectory.hpp
Core/src/EventData/VectorMultiTrajectory.cpp

As vector is specialized on bool, which prevents getting references to the underlying bool mechanisms, we have to specialize `DynamiColumn` to break this specialization of vector.
I'm also rolling in another small const-correctness fix to dynamic columns into this PR.

fix: MultiTrajectory specialize DynamicColumn for bool

---

docs/core/logging.md

As stated in issue [Issue#1734](https://github.com/acts-project/acts/issues/1734), the CI fails at the full-docs-build, after we removed the CustomDefaultLogger.
Since the logging will be revised, this part is now removed from the docs and should be updated in the future.
This PR is also a followup to [PR#1724](https://github.com/acts-project/acts/pull/1724) to some extent.

fix: remove `CustomDefaultLogger.cpp`-entry from docs

---

Core/include/Acts/EventData/SourceLink.hpp

This should be a transparent change in terms of the interface.

refactor: SourceLink uses custom Acts::Any

---

Core/include/Acts/Propagator/MultiEigenStepperLoop.ipp

There was a wrong abort condition in the `EigenMultiStepperLoop`'s step function, I think a leftover from a previous refactoring. This could lead to rare cases of not aborting the propagation, if all components have a stepping failure.
The new condition should fix this.

fix: Multistepper error condition

---

Core/include/Acts/EventData/MultiTrajectory.hpp
Core/include/Acts/EventData/VectorMultiTrajectory.hpp

This is to facilitate backends where the calibrated size is calculated on demand, and can't easily be returned by reference.
See also https://github.com/acts-project/acts/issues/1743

refactor!: MTJ calibrated size via dedicated method

---

Core/include/Acts/EventData/MultiTrajectory.hpp
Core/include/Acts/EventData/MultiTrajectory.ipp
Core/include/Acts/EventData/VectorMultiTrajectory.hpp
Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp
Core/include/Acts/TrackFitting/Chi2Fitter.hpp
Core/include/Acts/TrackFitting/KalmanFitter.hpp
Core/include/Acts/TrackFitting/detail/KalmanUpdateHelpers.hpp
Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/TrackFindingAlgorithm.hpp
Examples/Algorithms/TrackFinding/src/AmbiguityResolutionAlgorithm.cpp
Examples/Algorithms/TrackFinding/src/TrajectoriesToPrototracks.cpp
Examples/Framework/include/ActsExamples/EventData/Measurement.hpp
Examples/Framework/src/Validation/TrackClassification.cpp
Examples/Io/Root/src/RootTrajectoryStatesWriter.cpp
Tests/CommonHelpers/Acts/Tests/CommonHelpers/TestSourceLink.hpp
Tests/CommonHelpers/Acts/Tests/CommonHelpers/TestTrackState.hpp
Tests/UnitTests/Core/EventData/MultiTrajectoryTests.cpp
Tests/UnitTests/Core/TrackFinding/CombinatorialKalmanFilterTests.cpp
Tests/UnitTests/Core/TrackFitting/GainMatrixUpdaterTests.cpp

Closes #1613.
This changes the uncalibrated source link access functions to be symmetric with the calibrated functions.

refactor!: MTJ uncalibrated -> uncalibratedSourceLink

---

Core/src/Geometry/DetectorVolume.cpp

My GCC reports a `-Wmaybe-uninitialized` warning, this PR should fix it.

fix: maybe-uninitialized warning in DetectorVolume.cpp

---

Core/include/Acts/Utilities/Range1D.hpp
Tests/UnitTests/Core/Utilities/Range1DTests.cpp

Previously, the `Range1D` class checked for degeneracy as if it were a closed interval, but it is designed to be half-open. This commit changes the logic to represent this.

fix: Make `Range1D` a proper half-open interval

---

.zenodo.json
AUTHORS
CITATION.cff

This commit adds several of the recent CERN contributors to the `CITATION.cff` file. In particular, it adds @andiwand, @LuisFelipeCoelho, @AJPfleger, @guilhermeAlmeida1, and myself.
If you are listed above please check that I got your information right.
If you are not listed above but you would like to be please consider that I only added the people for whom I could pass by their office to ask for their affiliations. Feel free to add yourself. :smile:

docs: Add new CERN students to `CITATION.cff`

---

Core/include/Acts/Seeding/SeedFinder.ipp
Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/SeedFinder.ipp
Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding2/SeedFinder.ipp

PR #1378 has changed the default values of `deltaRMinTopSP`, `deltaRMaxTopSP`, `deltaRMinBottomSP` and `deltaRMaxBottomSP` to NAN.
As suggested by @osbornjd, we need to check that these variables have been correctly initialised in the seeder itself and not just in the SeedingAlgorithm, since the experiments will have their own seeding algorithms implemented within their own frameworks. This PR adds checks and exceptions to seedFinder if those values were NAN.

feat: throw runtime_error in seed finder if deltaR values were not initialised

---

Core/include/Acts/TrackFitting/BetheHeitlerApprox.hpp
Core/src/TrackFitting/BetheHeitlerApprox.cpp
Core/src/TrackFitting/CMakeLists.txt

Backport a58b7985beb89cb20197aa311d16f45a7a5ef91f from #1777.
---
This should fix violations of ODR by either adding the `inline` keyword or by moving functions to a cpp file.

fix: Linkage errors in BetheHeitlerApprox.hpp [backport #1777 to develop/v20.x]

---

Examples/Python/python/acts/examples/simulation.py

Fix the addGeant4 python function. With this fix the input of the geant4 simulation is changed to `particles_selected` which mean that the particle selector won't be ignored anymore.

fix: Let addGeant4 respect particle selection

---

Examples/Framework/src/Framework/Sequencer.cpp

only output timing data if we have an output directory

fix: sequencer timing output

---

Examples/Python/python/acts/examples/reconstruction.py
Examples/Scripts/Python/full_chain_odd.py

This add the option to use the G4 simulation with the Odd getting around the problem noticed in issue #1578.
Incidently it also fix a bug while using the odd full chain with only csv writting

feat: Add option to use odd with G4

---

.github/workflows/checks.yml

Somehow the combination of the `alpine` image we were using for python based actions was breaking github's checkout action. This should fix that.

ci: Change how we run python based check jobs

---

Core/include/Acts/TrackFitting/BetheHeitlerApprox.hpp
Core/src/TrackFitting/BetheHeitlerApprox.cpp
Core/src/TrackFitting/CMakeLists.txt

Backport a58b7985beb89cb20197aa311d16f45a7a5ef91f from #1777.
---
This should fix violations of ODR by either adding the `inline` keyword or by moving functions to a cpp file.

fix: Linkage errors in BetheHeitlerApprox.hpp [backport #1777 to develop/v21.1.x]

---

Plugins/Geant4/src/Geant4Converters.cpp

nucleus charge VS effective mass
somehow there is no nice solution to get the relative atomic mass in G4 so I had to go through the element class

fix: G4 material converter

---

Examples/Scripts/MaterialMapping/materialComposition.C

early exit and whitespace cleanup
picked up on this file because it crashed for me when `A >= 100`
changes are not critical so we can also drop it

refactor: move material composition code to the left

---

Plugins/Geant4/src/Geant4Converters.cpp

copied from here https://github.com/acts-project/acts/blob/main/Examples/Algorithms/Geant4/src/MaterialSteppingAction.cpp#L61

feat: G4 plugin material mixing

---

Examples/Detectors/TGeoDetector/include/ActsExamples/TGeoDetector/TGeoDetector.hpp
Examples/Detectors/TGeoDetector/include/ActsExamples/TGeoDetector/TGeoITkModuleSplitter.hpp
Examples/Detectors/TGeoDetector/src/TGeoDetector.cpp
Examples/Detectors/TGeoDetector/src/TGeoITkModuleSplitter.cpp
Examples/Python/python/acts/examples/itk.py
Examples/Python/src/Detector.cpp

When creating a TGeo detector and ITk module splitting is enabled also split the back sides of modules (not just the front side). Also made the patterns configurable which match sensor names to the barrel and disk split configuration categories.

fix: If ITk module splitting is enabled also split back side modules.

---

Core/include/Acts/TrackFitting/GaussianSumFitter.hpp

Building Athena (ATLAS' software platform) using ACTS v22.0.1 as externals and calling the GSF fitter lead to a fatal crash during compilation. This issue was fixed by explicitly using the SourceLink rather than its reference wrapper when storing the input measurements.
This PR should be ready to be merged.
Thanks to Hadrien Grasland for his help.

fix: GSF SourceLink reference

---

Examples/Python/tests/conftest.py
Examples/Python/tests/test_examples.py
Examples/Python/tests/test_reader.py
Examples/Python/tests/test_writer.py
pytest.ini

The event count checks should be covered by the hash checks, and we have a much better way of obtaining local references with the hashes in any case.

ci: Mark ODD tests, move away from exact event count checks

---

.github/workflows/checks.yml
CI/check_pragma_once.sh
Core/include/Acts/Utilities/Zip.hpp
Examples/Algorithms/Utilities/include/ActsExamples/Utilities/TracksToTrajectories.hpp
Examples/Algorithms/Utilities/include/ActsExamples/Utilities/TrajectoriesToPrototracks.hpp
Plugins/ActSVG/include/Acts/Plugins/ActSVG/TrackingGeometrySvgConverter.hpp
Plugins/ExaTrkX/src/weaklyConnectedComponentsCugraph.hpp
Plugins/TGeo/include/Acts/Plugins/TGeo/ITGeoIdentifierProvider.hpp
Tests/IntegrationTests/PropagationDatasets.hpp
Tests/IntegrationTests/PropagationTests.hpp
Tests/UnitTests/Core/Geometry/BVHDataTestCase.hpp
Tests/UnitTests/Core/Geometry/TrackingVolumeCreation.hpp
Tests/UnitTests/Core/Seeding/ATLASCuts.hpp
Tests/UnitTests/Core/Surfaces/BoundaryCheckTests.cpp
Tests/UnitTests/Core/Surfaces/BoundaryCheckTestsRefs.hpp
Tests/UnitTests/Core/Visualization/Visualization3DTester.hpp
Tests/UnitTests/Fatras/Physics/Dataset.hpp
Tests/UnitTests/Fatras/Selectors/Dataset.hpp
Tests/UnitTests/Plugins/Cuda/Seeding/ATLASCuts.hpp
Tests/UnitTests/Plugins/Json/EqualityHelpers.hpp
Tests/UnitTests/Plugins/Sycl/Seeding/ATLASCuts.hpp

I noticed a missing `#pragma once` in a file in `Core`, and thought it would be nice to check this in the CI.

ci: Add script checking for `#pragma once` to CI

---

Core/include/Acts/EventData/Track.hpp

This allows accessing the raw parameter elements by named methods, and to derive properties like absolute and transverse momentum.
Anything else that comes to mind we should add at this point?

feat: Add parameter getters to TrackProxy

---

Core/include/Acts/EventData/Track.hpp
Core/include/Acts/EventData/VectorTrackContainer.hpp
Core/include/Acts/EventData/detail/DynamicColumn.hpp
Core/src/EventData/CMakeLists.txt
Core/src/EventData/VectorTrackContainer.cpp

This also moves some method definitions to a cpp file for VectorTrackContainer, and adds the ability to copy a const track vector container to a mutable one (for modification).

feat: Enable removing tracks from container

---

thirdparty/actsvg/CMakeLists.txt

This bumps the ACTSVG version to 0.4.29, which should include at least some of the fixes for float-conversion.

chore: ACTSVG version 0.4.29

---

Core/include/Acts/Propagator/EigenStepper.hpp
Core/include/Acts/Propagator/EigenStepper.ipp
Examples/Python/src/Propagation.cpp

This was already a dynamic member, but hard-coded to 100um. This PR
makes this a constructor argument, but defaults it to the same value.

refactor: EigenStepper overstep limit is configurable

---

Examples/Scripts/TrackingPerformance/boundParamResolution.C

color of the fit used to be the same as the predicted which made the plots hard to read

chore: improve coloring for residuals and pulls script

---

Examples/Python/python/acts/examples/simulation.py
Examples/Python/src/Geant4Component.cpp
Examples/Scripts/Python/material_recording.py

- improve naming: `geant4SimulationConfig` -> `makeGeant4SimulationConfig`
- put sim and material track config generation on common grounds
- wire random numbers through arguments instead of setting it from the python wrappers
cc @Corentin-Allaire I hope this does not break your material tracks :crossed_fingers:

refactor: improve G4 python bindings

---

Examples/Python/python/acts/examples/itk.py
Examples/Python/python/acts/examples/reconstruction.py
Examples/Python/src/TrackFinding.cpp

This PR enables the configuration of `deltaPhiMax` with python bindings.
This variable is used only by the ortogonal seeding to restrict the phi search range. I believe this could be understood as something similar to what we do in the default seeding when we choose a certain number of neighbouring phi bins to search for SPs. 
I have set it to 0.025 in the ITk configuration because it improves the time performance by about 15% in the ITk PPP example, (when compared to the default value 0.085) without changing the physics performance. I still need to test it for SSS. @stephenswat @noemina

feat: deltaPhiMax variable from orthogonal seeding configurable with python 

---

Core/include/Acts/Seeding/BinnedSPGroup.hpp
Core/include/Acts/Seeding/BinnedSPGroup.ipp
Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/SeedingAlgorithm.hpp
Examples/Algorithms/TrackFinding/src/SeedingAlgorithm.cpp

Currently the SeedingAlgorithm creates the bin finders on every event. I don't think that's needed, but for const-reasons I have to change their argument types to be const everywhere.

refactor: Seeding algo level bin finders

---

Core/include/Acts/Seeding/EstimateTrackParamsFromSeed.hpp

#1912 broke our Athena build, but adding default arguments can fix it.

fix: Add default arguments to estimateTrackParamsfFromSeed

---

Examples/Python/python/acts/examples/reconstruction.py

The python logger in the `addSeeding` function did not respect the configured log level. This fixes this.

fix: Let `addSeeding` logger respect log level

---

Core/include/Acts/MagneticField/detail/SmallObjectCache.hpp

This generates a huge amount of compilation warnings during Acts Tag bumps in Athena (related only to the nomenclature) that may hide real warnings we should pay attention to.
Absolutely no change in the code behaviour

refactor: Change Variables Name in order not to start with _

---

Examples/Scripts/Python/full_chain_odd.py

currently we have mixed csv and root output for the simulation. this PR is fixing that

chore: odd full chain - only root output by default

---

Examples/Framework/include/ActsExamples/Framework/Sequencer.hpp
Examples/Framework/src/Framework/Sequencer.cpp

If Sequencer data flow checks are turned on, there's a use-after-move bug that this PR fixes.

fix: Sequencer use-after-move in sequencer data flow check

---

Examples/Python/python/acts/examples/itk.py
Examples/Python/tests/test_examples.py
Examples/Scripts/Python/full_chain_itk.py
Examples/Scripts/Python/itk_seeding.py

As a result of recent PRs and a Typo, the `itk_seeding.py` script was not running. 
Here are the changes:
- using an enum to specify the type of the input space points instead of relying on strings (typo-prones)
- scheduling of `SeedsToPrototracks` since now the seeding algorithm does not produce anymore prototracks
/cc @LuisFelipeCoelho

fix: itk_seeding script runs again

---

Core/include/Acts/Seeding/SeedFinderOrthogonal.ipp

in the orthogonal seeding we currently apply these cuts only to the bottom and top SPs

feat: add (phi, z) cuts to middle SP in orthogonal seeding

---

Core/include/Acts/Visualization/GeometryView3D.hpp
Core/src/Visualization/GeometryView3D.cpp

Added the `drawDetectorVolumeWithSurfaces` function that draws the detector volume with the sub-volumes and their surfaces . Any comments and recommendations are more than welcome. 
@andiwand @Matthewharri @asalzburger

feat: Added a function that draws the detector volume with inner surfaces

---

Core/include/Acts/TrackFitting/detail/GsfActor.hpp

If the weight cutoff is very high, it could happen that components are empty after applying the energy loss, and an assertion triggers. This fixes this and prints out a warning.

fix: GSF handles another case of empty components correctly

---

Examples/Python/python/acts/examples/itk.py

We have three vectors (of `std::size_t`) that call a reserve of these values. Reduce the number to 100 since it makes no sense we have 1000000000 seed candidates for a single middle SP ... not even for ITk at PU200
/cc @LuisFelipeCoelho

perf: Reduce memory consumption

---

Core/include/Acts/EventData/MultiTrajectory.hpp
Core/include/Acts/EventData/Track.hpp
Core/src/EventData/VectorTrackContainer.cpp
Tests/UnitTests/Core/EventData/TrackTests.cpp

This changes the track state ranges to return zero-length ranges in case the tip index is kInvalid. The VectorTrackContainer backend initializes the `tipIndex` to kInvalid, and so does the `addTrack`, so in principle this should always be consistent by default.
Fixes #1994

fix: Track state range is invalid if tip index is

---

Core/include/Acts/Seeding/SeedFinder.ipp
Core/include/Acts/Seeding/SeedFinderUtils.hpp
Core/include/Acts/Seeding/SeedFinderUtils.ipp

Defining a constructor makes the fillLineCircle function redundant

refactor: LinCircle constructor and no use of fill function

---

Core/include/Acts/Seeding/SeedFinder.ipp
Core/include/Acts/Seeding/SeedFinderConfig.hpp
Core/include/Acts/Seeding/SeedFinderOrthogonal.ipp

This PR moves the calculation of `m_config.maxScatteringAngle2 * m_config.sigmaScattering * m_config.sigmaScattering` to the seeding option since it can be done only once

refactor: move multipleScattering2 to seeding options

---

Core/include/Acts/Navigation/NextNavigator.hpp
Core/include/Acts/Propagator/DirectNavigator.hpp
Core/include/Acts/Propagator/MaterialInteractor.hpp
Core/include/Acts/Propagator/Navigator.hpp
Core/include/Acts/Propagator/detail/GenericDenseEnvironmentExtension.hpp

split off changes from my [calorimeter demo](https://github.com/acts-project/acts/compare/main...andiwand:tmp-calorimeter-demo?expand=1). this adds a shortcut for getting the current volume material from the navigator. since the new geometry has a different volume class we cannot reach the material in a generic way out of the box

refactor: navigator volume material handling

---

Core/include/Acts/Geometry/detail/DefaultDetectorElementBase.hpp
Examples/Detectors/GenericDetector/include/ActsExamples/GenericDetector/GenericDetectorElement.hpp
Examples/Detectors/GenericDetector/src/GenericDetectorElement.cpp
Examples/Detectors/TelescopeDetector/include/ActsExamples/TelescopeDetector/TelescopeDetectorElement.hpp
Examples/Detectors/TelescopeDetector/src/TelescopeDetectorElement.cpp
Plugins/Geant4/include/Acts/Plugins/Geant4/Geant4DetectorElement.hpp
Plugins/Geant4/src/Geant4DetectorElement.cpp
Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoDetectorElement.hpp
Tests/CommonHelpers/Acts/Tests/CommonHelpers/DetectorElementStub.hpp
Tests/UnitTests/Core/Geometry/AlignmentContextTests.cpp

This PR adds a non-const access to the associated `Surface` to the detector element interface and all derivates.
```c++
virtual Surface& surface() = 0;
```
Is now required to be implemented. It will allow for full const correctness of the new `Detector` geometry, having `non-const` object while detector creation (which will in turn allow for loading of material and setting of `GeometryID` and other associations, but require strict `const correctness` after geometry construction.
It removes already some now unnecessary `const_pointer_cast` or diversions via `MutableSurfacePtr` in the examples.

feat!: add non-cost access to Surface

---

Examples/Algorithms/TrackFitting/include/ActsExamples/TrackFitting/TrackFittingAlgorithm.hpp
Examples/Algorithms/TrackFitting/src/TrackFittingAlgorithm.cpp
Examples/Framework/include/ActsExamples/EventData/MeasurementCalibration.hpp
Examples/Framework/src/EventData/MeasurementCalibration.cpp
Examples/Python/python/acts/examples/reconstruction.py
Examples/Python/src/TrackFitting.cpp

Currently, the measurement calibrators in TrackFittingAlgorithm do not have access to cluster-level information. One widely-used pattern in the real world is to apply different calibrations depending on the cluster dimensions for instance, so this information is useful. This PR adds an optional input to the TrackFittingAlgorithm which is handed down through the MeasurementCalibrator interface. The reference to the cluster collection is boxed in a `std::optional<std::reference_wrapper>` to simplify the interface.
Ping @benjaminhuth for comments

feat: Add support for passing clusters to calibrator

---

Core/include/Acts/EventData/MultiTrajectory.hpp

Was using `unsigned long long` before, but that's not actually guaranteed to be `uint64_t` on all platforms

refactor: Use uint64_t explicitly in MultiTrajectory

---

Core/include/Acts/EventData/SourceLink.hpp
Core/include/Acts/TrackFitting/Chi2Fitter.hpp
Core/include/Acts/TrackFitting/GaussianSumFitter.hpp
Core/include/Acts/TrackFitting/KalmanFitter.hpp
Core/include/Acts/TrackFitting/detail/GsfActor.hpp

Backport 3918f38c6053e10202d43bea2dbfa281fa549f98 from #2095.
---
Closes #2000
the source links in the GFS went out of scope and caused segfaults
- this PR harmonizes the source link handling for the different fitters
- fixes a potential UB caused by parameter evaluation order
- fixes a potential dangling reference in `SourceLinkAdapterIterator`

fix: Dangling reference due to source link lifetime in fitters [backport #2095 to develop/v25.x]

---

Core/include/Acts/EventData/detail/TransformationFreeToBound.hpp
Core/src/EventData/TransformationFreeToBound.cpp

configurable tolerance for `transformFreeToBoundParameters` which is otherwise defaulted by the surface

refactor: Add tolerance to transformFreeToBoundParameters

---

Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp

That way updater and smoother logs will not be automatically silenced

chore: Wire loggers in CKF correctly

---

Core/include/Acts/Seeding/SeedFinderConfig.hpp
Examples/Algorithms/TrackFinding/src/SeedingAlgorithm.cpp

In case a misconfiguration of the `SeedFinderConfig`  happens, and the `seedFilter` is a nullptr, the code crashes.
This PR adds a protection against this eventuality. This happens in the `toInternalUnits` function, that now takes responsibility for checking the validity of its parameters.
It checks that the seedFilter is not a `nullptr` and that its config is already in internal units.

fix: Protection against wrong configuration of Seed finder config

---

Examples/Algorithms/Geant4/src/ParticleTrackingAction.cpp

One line change introducing `[[maybe_unused]]` for a value that is only checked in assert. 
This removes an `unused variable` warning with clang and MacOS.

fix: unused value appearing only in assert

---

Core/include/Acts/Utilities/VectorHelpers.hpp

missing include causing compilation issues

fix: include array in VectorHelpers.hpp

---

Fatras/include/ActsFatras/EventData/Hit.hpp

I've encountered FPEs in the calculation of the average direction of FATRAS hits.
Currently we do this:
- Divide four-momenta before and after divide by 2x the norm of the three-momentum vector
- Add both four-vectors, then take only the three-momentum out, then normalize thos
This fails if the norm of either of the three momenta is invalid or zero. I think Eigen has checks against this but we do the division manually.
I think this is equivalent to:
- Getting the normalized three-momenta
- Adding them and dividing by 2, then normalize again
Thoughts?

fix: FPE in FATRAS hit direction

---

.github/workflows/builds.yml

This should speed up subsequent builds even if there was a problem.

ci: Save ccache always right after build step

---

Examples/Algorithms/GeneratorsPythia8/ActsExamples/Generators/Pythia8ProcessGenerator.cpp
Examples/Algorithms/GeneratorsPythia8/ActsExamples/Generators/Pythia8ProcessGenerator.hpp
Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSelector.cpp
Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSelector.hpp
Examples/Python/python/acts/examples/simulation.py
Examples/Python/src/Pythia8.cpp
Examples/Python/src/TruthTracking.cpp

This allows to switch on detailed or short event info printing with Pythia8. The possibility to select particles by masses is added to the particle selection algorithm.

feat: pythia event info printing & particle selection with mass

---

.github/workflows/builds.yml
.gitlab-ci.yml

This further reduces the artifact size we have to pass between jobs

ci: Delete unit test and integration test binaries

---

Core/include/Acts/EventData/MultiTrajectory.hpp

This allows copying between MTJ backends by relaxing the template arguments.

refactor: Allow TrackState copyFrom for different MTJs

---

.github/labeler.yml

This adds new labels to the labeler plot. We introduce labels for identifying which state of the reconstruction sequence the PR is affecting, as well a label to check if a reference file has been changed (i.e. a change of performance)

ci: Add more labels to the labeler bot

---

CI/release.py

clean the `CI/release.py` up a bit and add print-outs to the exceptions.

refactor: remove duplicate function in `CI/release.py` and add print-outs

---

Tests/UnitTests/CMakeLists.txt
Tests/UnitTests/Core/EventData/CMakeLists.txt
Tests/UnitTests/Core/EventData/TrackTests.cpp
Tests/UnitTests/Core/EventData/TrackTestsExtra.cpp

We've observed the Track unit test executable to SEGFAULT during compilation. 
This seems to be a combination of different things in this compilation unit. I haven't been able to fully figure out if there's a single reason it gets triggered, but in local testing I've found that the problem goes away when I split out this test function into a separate compilation unit. I'm doing that here, and I need to make a small change to our CMake config to make that work.

fix: GCC segfault in TrackTests.cpp

---

Core/include/Acts/Utilities/Zip.hpp
Tests/UnitTests/Core/Utilities/CMakeLists.txt
Tests/UnitTests/Core/Utilities/ZipTests.cpp

This allows finally something like this for an arbitray amount of ranges / containers:
```c++
for(const auto &[a, b, c] : Acts::zip(ra, rb, rc)) {
// do something
}
```
Also adds unit test for this.

feat: Improve Acts::zip to take arbitrary number of ranges

---

Plugins/FpeMonitoring/include/Acts/Plugins/FpeMonitoring/FpeMonitor.hpp

I keep finding this kind of compilation issues...

fix: missing include of array in FpeMonitor.hpp

---

Fatras/include/ActsFatras/EventData/Particle.hpp
Tests/UnitTests/Fatras/EventData/ParticleTests.cpp
Tests/UnitTests/Fatras/Kernel/SimulationActorTests.cpp

Makes the state check for the particle more explicit

refactor: Drop bool conversion in favor of `isAlive` method in `Fatras::Particle`

---

Core/include/Acts/Geometry/TrackingGeometry.hpp
Core/src/Geometry/TrackingGeometry.cpp

This is necessary to forward the `shared_ptr` of the world volume to other modules like Geant4 particle killer

feat: `TrackingGeometry` gains `shared_ptr` world volume accessor

---

Examples/Algorithms/Geant4/include/ActsExamples/Geant4/Geant4Simulation.hpp
Examples/Algorithms/Geant4/include/ActsExamples/Geant4/ParticleKillAction.hpp
Examples/Algorithms/Geant4/src/Geant4Simulation.cpp
Examples/Algorithms/Geant4/src/ParticleKillAction.cpp
Examples/Python/python/acts/examples/simulation.py
Examples/Python/src/Geant4Component.cpp

This allows us to ignore secondary particles in the Geant4 simulation which should speed things up and remove noise when unnecessary

feat: Remove secondary particles in Geant4 simulation

---

docs/conf.py

#2256 was not sufficient. We have to ignore the root too

fix: Ignore all of http://eigen.tuxfamily.org

---

CI/physmon/workflows/physmon_ckf_tracking.py
CI/physmon/workflows/physmon_vertexing.py
Core/src/Material/Interactions.cpp
Core/src/TrackFitting/GainMatrixSmoother.cpp
Examples/Framework/include/ActsExamples/EventData/SimHit.hpp
Examples/Framework/include/ActsExamples/EventData/SimParticle.hpp
Examples/Scripts/Python/digitization.py
Examples/Scripts/Python/full_chain_odd.py

I pulled this out of https://github.com/acts-project/acts/pull/2086 since it is not relevant there but I would still like to merge them. These changes are random improvements across the code base which should not have any effects on CPU or physics performance.

chore: Accumulated small changes

---

Examples/Io/Root/src/RootTrajectoryStatesWriter.cpp

Minor (IMO) improvements to `RootTrajectoryStatesWriter`: align order of `res`, `err` and `pull` and use `std::sqrt`

chore: Rearrange `res/err/pull` and use `std::sqrt` in `RootTrajectoryStatesWriter`

---

Examples/Algorithms/GeneratorsPythia8/ActsExamples/Generators/Pythia8ProcessGenerator.cpp

For some odd reason, Pythia 8.310 introduces a new API for the `rndmEnginePtr` method. It now requires a shared pointer rather than a raw pointer. This commit adds support for this behaviour if ACTS is being compiled against a recent version of Pythia.

fix: Update to Pythia 8.310 API for random engines

---

Core/include/Acts/Surfaces/LineSurface.hpp
Core/src/Surfaces/LineSurface.cpp

Back to `col(2)` as it seems more optimal in terms of resources

perf: `LineSurface` back to `col(2)` for local z axis

---

.gitlab-ci.yml

workaround nvida apt repo error
```
Err:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
File has unexpected size (1127072 != 1126689). Mirror sync in progress? [IP: 152.199.20.126 443]
Hashes of expected file:
- Filesize:1126689 [weak]
- SHA256:7cee2584ca6d97b2f07018ba4f9c3c473fb4e299ed170968a1f8c99c090cc59f
- SHA1:4ee24fac5518a3fcc3702590a0dab32c95484c54 [weak]
- MD5Sum:593faff511765d11055c9919bf2e3bf8 [weak]
Release file created at: Thu, 17 Aug 2023 19:03:05 +0000
```
this should be reverted as soon as possible

ci: Hotfix `test_exatrkx_python`

---

Core/include/Acts/Surfaces/LineSurface.hpp
Core/src/Surfaces/LineSurface.cpp

second try after https://github.com/acts-project/acts/pull/2369
Back to `col(2)` as it seems more optimal in terms of resources

perf: `LineSurface` back to `col(2)` for local z axis #2

---

Examples/Python/python/acts/_adapter.py

Sometimes, the `setattr` in our special python constructor fails, and its not so easy to find out why. This should help by printing the key and the value that did not work together.

refactor: improve python error messages

---

Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp
Core/include/Acts/TrackFitting/GlobalChiSquareFitterError.hpp
Core/src/TrackFitting/CMakeLists.txt
Core/src/TrackFitting/GlobalChiSquareFitterError.cpp

This mostly adds the framework for the fitter specific error handling. Currently it only contains a single error case. During the next steps in development we can figure out which other errors might occur and they can be added easily.

feat: GlobalChiSquareFitterError framework for Gx2f

---

Core/include/Acts/Propagator/detail/GenericDenseEnvironmentExtension.hpp

`qOverP` accessor should be preferred over manual calculation
Pulled out from https://github.com/acts-project/acts/pull/2341

refactor: Use `qOverP` in dense environment

---

Core/include/Acts/TrackFitting/GaussianSumFitter.hpp
Core/include/Acts/TrackFitting/detail/GsfActor.hpp

This avoids reallocation of the component cache each call to the actor. Reduces runtime of the GSF Actor measurable (component convolution: 12% -> 9% of total actor time)

perf: Avoid some reallocations in GSF

---

Core/include/Acts/Navigation/DetectorNavigator.hpp
Core/include/Acts/Propagator/DirectNavigator.hpp
Core/include/Acts/Propagator/Navigator.hpp
Core/include/Acts/Propagator/StandardAborters.hpp
Examples/Python/python/acts/__init__.py
Tests/UnitTests/Fatras/Kernel/SimulationActorTests.cpp

Change the standard `EndOfWorldApproached` aborter to ask the `Navigator` and do not access directly the `currentVolume`.

feat: propagation end of world

---

Core/include/Acts/Surfaces/CylinderSurface.hpp
Core/include/Acts/Surfaces/DiscSurface.hpp
Core/include/Acts/Surfaces/PlaneSurface.hpp
Core/src/Surfaces/CylinderSurface.cpp
Core/src/Surfaces/DiscSurface.cpp
Core/src/Surfaces/PlaneSurface.cpp
Examples/Python/python/acts/__init__.py

Prompted through comments in #2439 
This PR harmonies the constructor signature for surfaces with detector elements and bounds, it fixes also a bug in the cylinder surface that a `shared_ptr` is first moved then assert checked, if this was the sole occurrence, e.g. by construction 
`Constructor(std::make_shared<Foo>` the assert would have always fired.

feat: harmonize shared ptr usage for surfaces with detector elements

---

.gitlab-ci.yml

We currently limit to `-j3`, presumably because we were running into memory consumption issues.
I'm playing with the sizing of the GitLab CI build VMs at the moment, and I'd like to see if we can go to the full core count at this point.

ci: Bump build procs in GitLab CI

---

Examples/Io/Root/src/RootParticleReader.cpp

Effectively only time was broken but I made the other units also explicit.

fix: Fix units in `RootParticleReader`

---

.gitlab-ci.yml

This reverts commit f6d9c0ae629320b9ccc8241634b7655a42b42875. We go back to -j3 to reduce OOM issues.

revert: Bump build procs in GitLab CI (#2474)

---

Core/include/Acts/TrackFitting/KalmanFitter.hpp

With `calculateTrackQuantities(track);` we reset `track.nMeasurements()` and `track.nHoles()`, no need to set them before.

refactor: remove obsolete assignments due to `calculateTrackQuantities()` 

---

Core/include/Acts/TrackFinding/MeasurementSelector.hpp

When selecting measurements for the next ckf step, only sort
the candidate track states with chi2 below the cut-off by chi2.
This is a minor improvement which reduces the track finding time
of the ckf in ttbar PU200 with the ITK detector by 1-2%. It does not
have any impact on the tracks found by the ckf.

perf: do not sort track state candidates with chi2 above cut-off.

---

Examples/Scripts/MaterialMapping/materialComposition.C

This has a fixed histogram bin range, and was default-constructing invalid elements that would then lead to a SEGFAULT when an element outside of the histogram range was to be filled.
This PR extends the histogram, and also adds a specific check and exception for the error case.
These do not have to be set manually.

fix: MaterialComposition analysis

---

Examples/Scripts/MaterialMapping/materialComposition.C

I don't think we actually need that at all.

fix: Remove TProfile max in material composition altogether

---

Core/include/Acts/Propagator/StandardAborters.hpp

`PathLimitReached` should not update the step length if it already reached its target
Pulled this out of https://github.com/acts-project/acts/pull/2518

fix: Fix and refactor `PathLimitReached`

---

Examples/Scripts/MaterialMapping/CMakeLists.txt
Examples/Scripts/MaterialMapping/MaterialComposition.cpp
Examples/Scripts/MaterialMapping/materialComposition.C

Changes the material composition script to optionally accept a region config in the form of a JSON config file like
```json
{
"beampipe": [
{
"rmin": 0,
"rmax": 24.4,
"zmin": -4000,
"zmax": 4000
}
],
"pixel": [
{
"rmin": 25,
"rmax": 200,
"zmin": -2400,
"zmax": 2400
}
],
"sstrips": [
{
"rmin": 202,
"rmax": 720,
"zmin": -3150,
"zmax": 3150
}
],
"lstrips": [
{
"rmin": 720,
"rmax": 1140,
"zmin": -3150,
"zmax": 3150
}
],
"solenoid": [
{
"rmin": 1160,
"rmax": 1200,
"zmin": -3000,
"zmax": 3000
}
],
"ecalbarrel": [
{
"rmin": 1250,
"rmax": 1500,
"zmin": -3050,
"zmax": 3050
}
],
"ecalendcap": [
{
"rmin": 315,
"rmax": 1500,
"zmin": 3200,
"zmax": 3450
},
{
"rmin": 315,
"rmax": 1500,
"zmin": -3450,
"zmax": -3200
}
]
}
```
for the example of the ODD. This then also allows to have multiple $rz$ regions …

feat: MaterialComposition plots with python config

---

Core/src/Surfaces/DiscTrapezoidBounds.cpp

This PR fixes the vertices calculation of a trapezoid in the local  frame (before the transformation).

fix: DiscTrapezoidBounds vertices

---

Core/src/Geometry/CuboidVolumeBuilder.cpp
Core/src/Geometry/LayerCreator.cpp

I noticed that the `CuboidVolumeBuilder` is not generating any envelope around the generated layer which results in overlapping surfaces which does not play nicely with navigation.
discovered in https://github.com/acts-project/acts/pull/2532

fix: Add envelope to `CuboidVolumeBuilder`

---

Core/include/Acts/Utilities/Result.hpp

Not sure why we do not have `const` access to `Acts::Result` but this is added here

refactor: Const access for `Acts::Result`

---

Examples/Io/Performance/ActsExamples/Io/Performance/CKFPerformanceWriter.cpp
Examples/Io/Performance/ActsExamples/Io/Performance/CKFPerformanceWriter.hpp

So far we do single-matching in the `CkfPerformanceWriter`, i.e., we associate to matched and fake based on the track purity of the reconstructed track. This is not always reliable.
This adds an option for double matching, which checks also the efficiency of the truth track.

feat: Add option for double-matching in CKF performance writer

---

Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp

We were discussing a bit (starting from #2511 ) if we can remove `effectiveProjector` from the collector in the GlobalChiSquareFitter, since it is not very efficient. This PR now removes it.

refactor: remove `effectiveProjector()` from `collector()` in GX2F

---

Core/include/Acts/Seeding/GNN_DataStorage.hpp
Core/include/Acts/Seeding/GNN_Geometry.hpp
Core/include/Acts/Seeding/GNN_TrackingFilter.hpp
Core/include/Acts/Seeding/SeedFinderFTF.hpp
Core/include/Acts/Seeding/SeedFinderFTF.ipp
Core/include/Acts/Seeding/SeedFinderFTFConfig.hpp
Core/include/Acts/TrackFinding/FasTrackConnector.hpp
Core/include/Acts/TrackFinding/RoiDescriptor.hpp
Core/src/TrackFinding/FasTrackConnector.cpp
Core/src/TrackFinding/RoiDescriptor.cpp
Examples/Algorithms/TrackFinding/src/SeedingFTFAlgorithm.cpp

clang tidy fixes after https://github.com/acts-project/acts/pull/2227

fix: Fixes after 2227

---

Core/include/Acts/Propagator/DirectNavigator.hpp

For a direct navigator we set the current surface to be the first surface in the surface sequence. This is done in the `DirectNavigator:Initializer::operator()`

fix: Set Current Surface as first surface for direct navigator

---

Core/include/Acts/Propagator/DirectNavigator.hpp

As the title says ... 
Point is that I noticed the when I was setting the start surface to be the first surface in `navSurfaces` the KF was correctly processing it doing its computations, but then it was stepping ahead and still searching for the first surface realizing it was behind and thus unreachable. With this the KF knows that surface has already been processed.

fix: Direct Navigator: Set surface iterator to next surface in case start surface is in the list

---

Core/src/Definitions/ParticleData.cpp

Previous ParticleHypothesis outputs couldn't display `eGamma` as supposed.

fix: pdg: eGamma for `<<` was incorrect

---

Core/CMakeLists.txt
Core/include/Acts/EventData/ChargeConcept.hpp
Core/include/Acts/EventData/MultiTrajectoryBackendConcept.hpp
Core/include/Acts/EventData/TrackContainerBackendConcept.hpp
Core/include/Acts/EventData/TrackStateProxyConcept.hpp
Core/include/Acts/Geometry/SurfaceVisitorConcept.hpp
Core/include/Acts/Utilities/Concepts.hpp
cmake/ActsCompilerOptions.cmake

This replaces the custom C++20 concepts detection mechanism at CMake level with the corresponding feature preprocessor define.

refactor: Use `__cpp_concepts` directly

---

.github/workflows/analysis.yml
CI/test_coverage
CI/test_coverage.py

Addresses and closes Issue #1211 
----------------------------------
The supposed problem was "Parallel processing of gcov data. ([#%s592](https://github.com/gcovr/gcovr/issues/592))" in gcov 5.1. This was already fixed in 5.2.
We need to add `--exclude-noncode-lines` due to a breaking change in gcovr 6.0, otherwise our coverage would change a lot (-0.33%):
New [--exclude-noncode-lines](https://gcovr.com/en/stable/manpage.html#cmdoption-gcovr-exclude-noncode-lines) to exclude noncode lines. Noncode lines are not excluded by default anymore. ([#%s704](https://github.com/gcovr/gcovr/issues/704), [#%s705](https://github.com/gcovr/gcovr/issues/705))
Closes #1211
Update the gcovr-call
----------------------
- remove use of local bundled version (files were removed some years ago)
- remove …

ci: Update to gcovr=6.0 and remove bundled-version support

---

Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp
docs/contribution/profiling.md

Fixes one undocumented parameter in the GX2F and a broken link.

docs: Doc fix for Gx2FitterOptions and 1 link

---

Core/include/Acts/TrackFitting/GaussianSumFitter.hpp
Core/include/Acts/TrackFitting/GsfError.hpp
Core/src/TrackFitting/GsfError.cpp

I'm actually not sure why I introduced this error type. Presumably, this happens when the smeared digitization smeares hits out-of-bounds...
Maybe we should prevent this in the future, but it should not fail in the GSF.

refactor: No error in GSF if start pars are out of bounds

---

Examples/Python/python/acts/examples/__init__.py

The summary of the FPE masks is quite verbose, and if the environment variable `ACTS_SEQUENCER_DISABLE_FPEMON` is set, one is probably not interested in this output.

refactor: Disable FPE mask printing if FPEMON  is disabled by envvar

---

Examples/Python/python/acts/__init__.py
Plugins/DD4hep/include/Acts/Plugins/DD4hep/DD4hepBinningHelpers.hpp
Plugins/DD4hep/include/Acts/Plugins/DD4hep/DD4hepBlueprint.hpp
Plugins/DD4hep/include/Acts/Plugins/DD4hep/DD4hepDetectorSurfaceFactory.hpp
Plugins/DD4hep/include/Acts/Plugins/DD4hep/DD4hepLayerStructure.hpp
Plugins/DD4hep/src/ConvertDD4hepDetector.cpp
Plugins/DD4hep/src/DD4hepBlueprint.cpp
Plugins/DD4hep/src/DD4hepDetectorStructure.cpp
Plugins/DD4hep/src/DD4hepDetectorSurfaceFactory.cpp
Plugins/DD4hep/src/DD4hepLayerStructure.cpp
Tests/UnitTests/Plugins/DD4hep/DD4hepCylinderLayerStructureTests.cpp
Tests/UnitTests/Plugins/DD4hep/DD4hepCylindricalDetectorTests.cpp
Tests/UnitTests/Plugins/DD4hep/DD4hepDiscLayerStructureTests.cpp

This PR adds the possibility that the internal layer structure, i.e. the contained surfaces - drive the dimension of the external volume shape.
E.g. in DD4hep, one could then write
```xml
<argument value="acts_volume_internals_measure: str = z,r"/>
<argument value="acts_volume_internals_clearance: double = pix_b_clear"/>
```
Which will trigger measuring the internal surface dimensions in z & r and add a clearance around it.

feat: improve DD4hep based detector building and add tests

---

Examples/Io/Performance/ActsExamples/Io/Performance/CKFPerformanceWriter.cpp
Examples/Io/Performance/ActsExamples/Io/Performance/CKFPerformanceWriter.hpp
Examples/Python/src/Output.cpp

Needed for GNN+CKF workflow.
Optionally writes additional info to a `TTree` like this:
```
event_nr         particle_id  matched
0            2    4503599677702144     True
1            2    4503599862251520     True
2            2    4503599929360384     True
3            2    4503599946137600    False
...
```

feat: Optional write out detailed matching infos in CKFPerformanceWriter

---

Core/include/Acts/Detector/Portal.hpp
Core/src/Detector/Portal.cpp
Core/src/Detector/PortalGenerators.cpp
Core/src/Detector/detail/CylindricalDetectorHelper.cpp
Plugins/Json/src/PortalJsonConverter.cpp
Tests/UnitTests/Core/Detector/DetectorVolumeTests.cpp
Tests/UnitTests/Core/Detector/PortalTests.cpp
Tests/UnitTests/Core/Navigation/NavigationStateTests.cpp
Tests/UnitTests/Core/Navigation/NavigationStateUpdatersTests.cpp
Tests/UnitTests/Plugins/Json/PortalJsonConverterTests.cpp

The shared-from-this functionality in `Portal` is only needed because `Portal::fuse` uses it to reset the other fuse partner to itself. This PR changes `Portal::fuse` into a static symmetric function which returns a new merged portal.
The input portals are invalidated.
It then removes the shared-from-this functionality from portal, as it is no longer needed.

refactor: Portal fusing and remove shared-from-this

---

Core/include/Acts/Geometry/CylinderVolumeBuilder.hpp
Examples/Detectors/GenericDetector/include/ActsExamples/GenericDetector/BuildGenericDetector.hpp
Examples/Detectors/TGeoDetector/src/TGeoDetector.cpp
Plugins/DD4hep/src/ConvertDD4hepDetector.cpp
Tests/CommonHelpers/Acts/Tests/CommonHelpers/CylindricalTrackingGeometry.hpp
Tests/UnitTests/Core/Geometry/SimpleGeometryTests.cpp
Tests/UnitTests/Core/Material/SurfaceMaterialMapperTests.cpp

This reverts commit 34bd984f66029ebe93697aab76e84c56a16f10c0 from #2759 as it breaks Athena compilation.

revert: Remove `volumeSignature` from geometry building

---

.gitlab-ci.yml

Also removes trailing whitespace in the gitlab configuration.

ci: Reduce expiry time for GitLab artifacts

---

CMakeLists.txt
Plugins/ActSVG/include/Acts/Plugins/ActSVG/IndexedSurfacesSvgConverter.hpp

This is a mini fix:
- updating the `ActsSVG` version to `v0.4.38` removes the warning:
```sh
z-rphi view detected!
z-rphi view detected!
z-rphi view detected!
z-rphi view detected!
z-rphi view detected!
z-rphi view detected!
```
caused by a `cout` in the `v0.4.35` version.
It also adds bin center displays.

fix: bump svg version (fix) and display bin centers

---

Core/include/Acts/Seeding/SpacePointGrid.ipp

Totally unnecessary copy of locally-defined objects (vector and axes). Can be simply moved instead.
Other changes:
- `config.zBinEdges` contains `float`s. No need to get reference when looping
- `std::max` returns same type of the two input arguments and `std::floor` returns a `float`. Thus `zBins` can already be defined as a `float` instead of `int`, thus avoiding a few `static_cast`s

fix: Move objects instead of copying

---

Core/include/Acts/Propagator/Navigator.hpp
Tests/IntegrationTests/PropagationBentTracks.cpp

This option is supposed to improve the navigation but can also cause regressions. Layers without bounds overlap with boundaries therefore we might end up outside the current tracking volume while targeting a layer. I propose that this should be rather fixed by the used with proper layer bounds that extend to the volume boundaries.

refactor!: Remove navigator layer bounds check option

---

Core/include/Acts/Material/GridSurfaceMaterial.hpp
Plugins/DD4hep/include/Acts/Plugins/DD4hep/DD4hepDetectorSurfaceFactory.hpp
Plugins/DD4hep/include/Acts/Plugins/DD4hep/DD4hepLayerStructure.hpp
Plugins/DD4hep/src/DD4hepBlueprintFactory.cpp
Plugins/DD4hep/src/DD4hepDetectorSurfaceFactory.cpp
Plugins/DD4hep/src/DD4hepLayerStructure.cpp
Tests/UnitTests/Plugins/DD4hep/DD4hepCylinderLayerStructureTests.cpp
docs/known-warnings.txt

This mini-PR fixes a type in 6 files & changes the name of the `GridSurfaceMaterial` frame class.

fix: typo fixes and name change

---

Core/include/Acts/TrackFitting/KalmanFitter.hpp

This is observed to break the KalmanFitter if run with the direct navigator, at least in some cases. To be followed up with a more robust solution.

fix: DirectNavigator causes incorrect propagation finalization

---

.policy.yml

This now applies the main review policy also to the `develop/v*` branches in addition to `main`.

chore: Change policy for regular reviews to include develop branches

---

Examples/Python/python/acts/examples/__init__.py

* Fix crash when `acts.examples.dump_args_calls()` is enabled before creating an `acts.examples.Sequencer()`
* More comprehensive argument printout

fix: Python dump_args_calls crash

---

CI/setup_cvmfs_lcg105.sh

The LXPLUS machines are slowly moving to [RHEL9](https://linux.web.cern.ch/rhel/). 
I use LCG cmvfs setup often to compile acts on lxplus. I've added a setup script to extend the setup of the correct environment on rhel9 machines and keeps the support for centos7/8 using LCG105. 
I successfully compiled and ran the odd full chain on RHEL9. 
In the future deprecated LCG setups should be cleaned.

build: Add cvmfs setup for LCG105 on centos7/8 and RHEL9 lxplus

---

Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.hpp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.ipp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFitter.hpp
Core/include/Acts/Vertexing/AdaptiveMultiVertexFitter.ipp
Core/include/Acts/Vertexing/FullBilloirVertexFitter.hpp
Core/include/Acts/Vertexing/FullBilloirVertexFitter.ipp
Core/include/Acts/Vertexing/IterativeVertexFinder.hpp
Core/include/Acts/Vertexing/IterativeVertexFinder.ipp
Core/include/Acts/Vertexing/TrackLinearizer.hpp
Core/include/Acts/Vertexing/VertexFitterConcept.hpp
Examples/Algorithms/Vertexing/include/ActsExamples/Vertexing/AdaptiveMultiVertexFinderAlgorithm.hpp
Examples/Algorithms/Vertexing/include/ActsExamples/Vertexing/IterativeVertexFinderAlgorithm.hpp
Examples/Algorithms/Vertexing/include/ActsExamples/Vertexing/VertexFitterAlgorithm.hpp
Examples/Algorithms/Vertexing/src/AdaptiveMultiVertexFinderAlgorithm.cpp
Examples/Algorithms/Vertexing/src/IterativeVertexFinderAlgorithm.cpp
Examples/Algorithms/Vertexing/src/VertexFitterAlgorithm.cpp
Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFinderTests.cpp
Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFitterTests.cpp
Tests/UnitTests/Core/Vertexing/FullBilloirVertexFitterTests.cpp
Tests/UnitTests/Core/Vertexing/IterativeVertexFinderTests.cpp
Tests/UnitTests/Core/Vertexing/ZScanVertexFinderTests.cpp

This allows removing the linearizer template from: 
- Billoir fitter
- ZScan finder
- IVF
- AMVFitter
Part of:
- #2842 
Blocked by:
- #2886

refactor!: Use `Delegate` for track linearizers

---

.gitlab-ci.yml

We've been getting OOM errors in the build again. This works around that.

ci: Reduce build job count to 2

---

Plugins/Geant4/include/Acts/Plugins/Geant4/Geant4SurfaceProvider.hpp
Tests/UnitTests/Plugins/Geant4/Geant4SurfaceProviderTests.cpp

Making the validation of the GDML file schema optional when parsing the files. 
Mainly added so that the tests could be decoupled from the state of the servers with the .xsd files.

fix: Geant4SurfaceProvider gdml schema validation fix

---

CI/physmon/phys_perf_mon.sh

Bash needs for the defaults the following syntax `VAR=${[number]:-default}` (`-` was missing). Now the variable `outdir` cannot be empty anymore and we don't need to check.
This does not change anything in the current setup, since we are always specifying both additional arguments.

fix(ci): default arguments definition in physmon

---

Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp
Core/include/Acts/TrackFitting/GlobalChiSquareFitterError.hpp
Tests/UnitTests/Core/TrackFitting/Gx2fTests.cpp

Returns an error, in case the number of measurements is too low for a fit.
This check takes into account the evaluated dimensions of the measurements. To fit, we need at least NDF+1 measurements. However, we n-dimensional measurements count for n measurements, reducing the effective number of needed measurements.
We might encounter the case, where we cannot use some (parts of a) measurements, maybe if we do not support that kind of measurement. This is also taken into account here.
`ndf = 4` is chosen, since this a minimum that makes sense for us, but a more general approach is desired.
We had in PR #2966 FPE Problems due to a division by zero in:
https://github.com/acts-project/acts/blob/a42f23b96876a0fdfba5a8ab1b6c90a9b1f2dc30/Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp#L716 …

feat(gx2f): Add new error `NotEnoughMeasurements`

---

Core/include/Acts/Vertexing/AdaptiveMultiVertexFitter.hpp
Core/include/Acts/Vertexing/ImpactPointEstimator.hpp
Core/include/Acts/Vertexing/IterativeVertexFinder.hpp
Core/include/Acts/Vertexing/VertexingError.hpp
Core/src/Vertexing/AdaptiveMultiVertexFitter.cpp
Core/src/Vertexing/CMakeLists.txt
Core/src/Vertexing/ImpactPointEstimator.cpp
Core/src/Vertexing/VertexingError.cpp
Tests/UnitTests/Core/Vertexing/ImpactPointEstimatorTests.cpp
Tests/UnitTests/Core/Vertexing/KalmanVertexUpdaterTests.cpp

This PR moves the code of the `ImpactPointEstimator` from the header into a compiled file. To allow this, I have to make some changes to the interface to remove templates.
In the process, I introduced `Eigen::Map<ActsDynamicVector>` as an argument to `getDistanceAndMomentum` and `getVertexCompatibility`.
Part of:
- #2842 
Blocked by:
- #2953

refactor!: `ImpactPointEstimator` moves to cpp file

---

Core/include/Acts/Vertexing/GaussianGridTrackDensity.hpp
Core/include/Acts/Vertexing/GridDensityVertexFinder.hpp
Core/src/Vertexing/CMakeLists.txt
Core/src/Vertexing/GaussianGridTrackDensity.cpp
Core/src/Vertexing/GridDensityVertexFinder.cpp
Tests/UnitTests/Core/Vertexing/AdaptiveMultiVertexFinderTests.cpp
Tests/UnitTests/Core/Vertexing/GaussianGridTrackDensityTests.cpp
Tests/UnitTests/Core/Vertexing/GridDensityVertexFinderTests.cpp

This PR moves 
- `GaussianGridTrackDensity`
- `GridDensityVertexFinder`
to cpp files. It has to refactor the interface a bit to make this possible, mostly, the grid sizes become runtime arguments instead of compile-time parameters. This then also changes the internal grid eigen objects to be dynamic, which I think should be fine because we essentially only do lookups on them.
Part of:
- #2842
Blocked by:
- #2971

refactor!: Move and Grid Density finders to cpp

---

Examples/Scripts/Python/full_chain_odd.py

- shuffle imports
- shuffle constants
- output directory argparse parameter

refactor: Tweak `full_chain_odd.py`

---

Core/include/Acts/Definitions/Direction.hpp
Core/include/Acts/Geometry/ConeVolumeBounds.hpp
Core/include/Acts/Geometry/CuboidVolumeBounds.hpp
Core/include/Acts/Geometry/CutoutCylinderVolumeBounds.hpp
Core/include/Acts/Geometry/CylinderVolumeBounds.hpp
Core/include/Acts/Geometry/GenericCuboidVolumeBounds.hpp
Core/include/Acts/Geometry/TrapezoidVolumeBounds.hpp
Core/include/Acts/Geometry/VolumeBounds.hpp
Core/src/Detector/PortalGenerators.cpp
Core/src/Geometry/AbstractVolume.cpp
Core/src/Geometry/ConeVolumeBounds.cpp
Core/src/Geometry/CuboidVolumeBounds.cpp
Core/src/Geometry/CutoutCylinderVolumeBounds.cpp
Core/src/Geometry/CylinderVolumeBounds.cpp
Core/src/Geometry/GenericCuboidVolumeBounds.cpp
Core/src/Geometry/TrackingVolume.cpp
Core/src/Geometry/TrapezoidVolumeBounds.cpp
Core/src/Visualization/GeometryView3D.cpp
Plugins/Json/include/Acts/Plugins/Json/PortalJsonConverter.hpp
Plugins/Json/src/PortalJsonConverter.cpp
Tests/UnitTests/Core/Geometry/ConeVolumeBoundsTests.cpp
Tests/UnitTests/Core/Geometry/CuboidVolumeBoundsTests.cpp
Tests/UnitTests/Core/Geometry/CutoutCylinderVolumeBoundsTests.cpp
Tests/UnitTests/Core/Geometry/CylinderVolumeBoundsTests.cpp
Tests/UnitTests/Core/Geometry/GenericCuboidVolumeBoundsTests.cpp
Tests/UnitTests/Core/Geometry/TrapezoidVolumeBoundsTests.cpp
docs/_extensions/lazy_autodoc.py

This PR:
1. Makes `OrientedSurface` a struct with member names
2. Remove the `OrientedSurfaces` typedef over a vector
3. Add aliases `AlongNormal` and `OppositeNormal` to the `Direction` type
I don't think this is breaking.

refactor: OrientedSurface improvements

---

CONTRIBUTING.rst
docs/contribution/contribution.md
docs/contribution/style_guide.md

The (empty) style guide seems to be unnecessary, since we already have a separate section [Code guidelines](https://acts.readthedocs.io/en/v33.0.0/codeguide.html) and also talk about formatting in the [Contribution guidelines](https://acts.readthedocs.io/en/v33.0.0/contribution/guide.html#contribution-guidelines).

docs: remove empty style guide and fix gender neutral language

---

docs/conf.py

After #2797 the white papers were missing in the read the docs build. Thanks @beomki-yeo for noticing.
https://acts--3067.org.readthedocs.build/en/3067/white_papers/index.html

docs: missing white papers section in RTD

---

Examples/Scripts/Python/MLAmbiguityResolution/train_ambiguity_solver.py
Examples/Scripts/Python/MLAmbiguityResolution/train_seed_solver.py

This PR fix an issue for the seed selection NN where the wrong network size would be written to the onnx file. The default network are unaffected as they where written before this mistake was introduced.

fix: Wrong network size written to onnx

---

Core/src/Utilities/TrackHelpers.cpp

Oversight which produces segfaults

fix: Fix `make_error_code(TrackExtrapolationErrorCategory)`

---

Core/src/TrackFitting/GainMatrixSmoother.cpp

chore: Improved debugging outputs for `GainMatrixSmoother`

---

Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp

refactor:  avoid creation of unused strings.
Currently a string used for verbose logs is created always, which can be avoided.

perf: Avoid creation of unused string in CKF

---

Examples/Python/src/ModuleEntry.cpp
Examples/Python/tests/test_base.py

Binds more version information to Python which can be used to differentiate between acts builds / installs.

feat: Bind version info to Python

---

docs/conf.py
docs/contribution/release.md

This stops us from merging, because the docs-build fails. We can revert this, when their certificate works again.

fix(ci): conventionalcommits.org SSL_ERROR_BAD_CERT_DOMAIN

---

Plugins/Podio/edm.yml

Since https://github.com/AIDASoft/podio/pull/556/ the mandatory schema_version does not just generate a warning anymore, but fails with an error. This will prevent CMake from configuring correctly with newer podio versions, in particular version 1 coming up.
This PR adds a schema_version of 1 to edm.yml.

fix: add schema_version to podio edm.yml

---

docs/conf.py

[CERN Document Server](https://cds.cern.ch/) is currently only reachable from within CERN:
> We're currently experiencing a surge in traffic to our systems. As a mitigation, the CDS website is temporarly available only from inside the CERN network. More information [here](https://cern.service-now.com/service-portal?id=outage&n=OTG0149709).

fix(ci): exclude unreachable cds.cern.ch from docs check

---

Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp
Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp
Core/include/Acts/TrackFitting/KalmanFitter.hpp
Core/include/Acts/TrackFitting/detail/KalmanUpdateHelpers.hpp

Instead of excluding some components from the track-state, we include only those needed:
- Prevents us from allocating unused components, in case we add new components to ACTS
- Makes it clearer, which components are used

refactor: set track state prop masks inclusively

---

Examples/Algorithms/Geant4/CMakeLists.txt
Examples/Algorithms/Geant4/include/ActsExamples/DDG4/DDG4DetectorConstruction.hpp
Examples/Algorithms/Geant4/include/ActsExamples/Geant4/GdmlDetectorConstruction.hpp
Examples/Algorithms/Geant4/include/ActsExamples/Geant4/RegionCreator.hpp
Examples/Algorithms/Geant4/include/ActsExamples/TelescopeDetector/TelescopeG4DetectorConstruction.hpp
Examples/Algorithms/Geant4/src/DDG4DetectorConstruction.cpp
Examples/Algorithms/Geant4/src/GdmlDetectorConstruction.cpp
Examples/Algorithms/Geant4/src/RegionCreator.cpp
Examples/Algorithms/Geant4/src/TelescopeG4DetectorConstruction.cpp
Examples/Python/python/acts/examples/simulation.py
Examples/Python/src/Geant4Component.cpp
Examples/Python/src/Geant4DD4hepComponent.cpp

I work with fast simulation for silicon detectors and I was interested to see how `G4ProductionCuts` affect the number of secondary particles. This may be useful also for other people so adding it here.
/cc @andiwand @paulgessinger

feat: Add basic regions support to G4 example

---

Plugins/DD4hep/src/DD4hepBlueprintFactory.cpp

This PR adds the functionality to set a container type geo id generator by variant parameter.

feat: allow for container geoID generator in DD4hep Plugin

---

Examples/Scripts/Python/full_chain_itk.py

We can make use of recent track finding improvements in the ITk full chain.
I am also switching the AMVF in to spare some CPU during execution with high pileup.

chore: Use recent track finding improvements in `full_chain_itk.py`

---

Core/src/Detector/DetectorBuilder.cpp

Putting the `IMaterialDecorator` call after the geometry Id assignment, as the decorators (e.g. `JsonMaterialDecorator`) rely on the Id already being present in the hierarchy map.

fix: Order of geometry Id/material assignment in the DetectorBuilder  

---

Examples/Algorithms/AmbiguityResolution/src/ScoreBasedAmbiguityResolutionAlgorithm.cpp
Plugins/Json/include/Acts/Plugins/Json/AmbiguityConfigJsonConverter.hpp

My local builds fails after https://github.com/acts-project/acts/pull/3139 which I think is caused by a more recent json version that includes `std::pair` `from_json` implementations which clash with win the overload resolution.

fix: Fix my local build after #3139

---

Examples/Algorithms/Fatras/src/FatrasSimulation.cpp

While debugging I usually add this manually. I think this can be the default behavior.

chore: Use Fatras log level for propagation

---

Core/include/Acts/EventData/MultiTrajectory.hpp
Core/include/Acts/EventData/TrackContainer.hpp
Core/include/Acts/EventData/VectorMultiTrajectory.hpp
Core/include/Acts/EventData/VectorTrackContainer.hpp
Plugins/Podio/include/Acts/Plugins/Podio/PodioDynamicColumns.hpp
Plugins/Podio/include/Acts/Plugins/Podio/PodioTrackContainer.hpp
Plugins/Podio/include/Acts/Plugins/Podio/PodioTrackStateContainer.hpp

This makes it easier for compile time known dynamic columns to add. Pulled out of https://github.com/acts-project/acts/pull/3161

refactor!: Use `std::string_view` for `addColumn` in track EDM

---

Core/include/Acts/Propagator/Navigator.hpp

The `startSurface` should never be null which is checked and protected against now

refactor: Simplify layer handling in `Navigator`

---

Core/src/Surfaces/AnnulusBounds.cpp

Move code to the left and by leveraging early return statements. Have a clear unconditional return statement at the end of the function.
Pulled out of https://github.com/acts-project/acts/pull/3170

refactor: Early exit for `AnnulusBounds::inside`

---

.github/workflows/analysis.yml

For about a week, we did not get any coverage reports added to PRs.
Reason was a failing upload, due to the codecov rate limit.
`[2024-05-24T09:08:19.271Z] ['error'] There was an error running the uploader: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: 429 - {'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 2453s.', code='throttled')}`
To keep the same coverage, we need to add the flag `disable_search: true`. Otherwise, around 1500 coverage files would be uploaded and increase our coverage from 50% to 85%. This solution was suggested in:
- https://github.com/codecov/codecov-action/issues/1354
Maybe we need to add the token as …

ci: bump codecov-action to v4

---

Examples/Io/Json/src/JsonDigitizationConfig.cpp
Tests/UnitTests/Fatras/Digitization/UncorrelatedHitSmearerTests.cpp

This PR fixes the previous PR I opened with the straw surfaces smearing https://github.com/acts-project/acts/pull/3197 because I realized that the` forcePositiveValues` parameter from json is not parsed successfully, since I did not add them in the `JsonConfiguration`. I am fixing with this PR (hopefully).

fix: Adding another parameter in the json configuration 

---

Core/include/Acts/Propagator/EigenStepper.hpp
Core/include/Acts/Propagator/EigenStepper.ipp

In https://github.com/acts-project/acts/pull/2846 I removed a constructor parameter which was used by Athena and maybe other clients. This would classify as a breaking change. To work around that I reintroduced the parameter and marked the constructor as deprecated.

fix: Fix breaking `EigenStepper` change

---

Core/src/Detector/CylindricalContainerBuilder.cpp
Core/src/Detector/DetectorBuilder.cpp

These are two fixes in the Detector building:
- volumes were not handed forward in the cylindrical building
- material was loaded only onto the surfaces but not portals

fix: material loading to portals, forwarding of volumes in detector building

---

README.md

After
- https://github.com/acts-project/acts/pull/3108
the badge did not update anymore. This was due to the wrong branch setting, after copying the suggestion from codecov. This removes any branch-specification and takes the default branch from ACTS.
Since the documentation of codecov is not super clear, it might be necessary also to add a token in the future like this:
```
[![codecov](https://codecov.io/gh/acts-project/acts/graph/badge.svg?token=INSERT_TOKEN_HERE)](https://codecov.io/gh/acts-project/acts)
```
The token (different from the upload token) can be found at https://app.codecov.io/gh/acts-project/acts/settings/badge (login required). It seems to work without token for now, so no reason to expose it to the public.

fix: codecov coverage badge - correct branch

---

Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp

This PR adds a delegate to the  CKF extensions. If this delegate is not set a default 
delegate will be used which behaves as the version without these commits.  
The delegate allows to provide a different implement for source link creation and 
measurement selection which is better suited for a particular use case. 
An example 
can be seen here: [goetzgaycken/acts:MeasurementSelector2.hpp:L501](https://github.com/goetzgaycken/acts/blob/34c37ac31bbe27d8bb776c1ba249f5c722bd5d84/Core/include/Acts/TrackFinding/MeasurementSelector2.hpp#L501)
It only creates track states for the finally selected measurements and simplifies the computations for the chi2 and uses
a more suitable interface for the calibrator. This allowed to reduce the time for the source link creation and measurement selection …

feat: introduce delegate for the sourcelink creation and the measurement selection

---

Core/include/Acts/Propagator/Navigator.hpp

Reverting #3217 as this has bigger implications in Athena than expected. The point where this fails at the moment is in a special extrapolation where the whole tracking geometry is "cut" by a cylinder after the first pixel barrel layer. Somehow the previous version of the code was able to handle this case, I am not sure how, since we are also violating our navigation concepts with overlaps there.
I would like to follow up on this on at a later stage where I will try to make the change sound with Athena before we bring it in. One idea is to make the `SurfaceReached` aborter more robust by giving it a state (if this is possible) about the intersections we are targeting. This should make it possible to remove the overstepping condition and to safely target cylinders with that aborter even if …

revert: Remove target volume estimation from `Navigator` #3217

---

Plugins/ActSVG/src/PortalSvgConverter.cpp

One-line swapping change.
correcting, after assigning does not make sense, you man!

fix: correct first, then draw for SVG portals

---

Core/include/Acts/Geometry/TrackingVolume.hpp
Core/src/Geometry/TrackingVolume.cpp

We'll get rid of the glue volume descriptor entirely anyway, but it doesn't hurt to switch to smart pointers regardless.

refactor: Use unique_ptr for GlueVolumeDescriptor

---

Examples/Python/CMakeLists.txt

This should allow `import acts.examples.geant4.geomodel` which was broken before.

fix: Put geomodel-G4 python bindings to correct place

---

Examples/Detectors/DD4hepDetector/src/DD4hepGeometryService.cpp

For testing purposes it is useful to disable DD4HEP logging if requested. While most of it can be disabled already some internal ROOT/DD4HEP code uses either ROOT logging or pure `std::cout`. This PR tries to silence also that.
Note that `std::cout` part is a bit hacky so I'm fine if this is not merged, but maybe somebody else would be interested in this.

feat: Silence DD4HEP if requested

---

Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/ExaTrkXPipeline.hpp
Plugins/ExaTrkX/src/ExaTrkXPipeline.cpp
Plugins/GeoModel/include/Acts/Plugins/GeoModel/GeoModelTree.hpp

These headers need to be included to build with GCC 14. Additional fixed a unused variable warning.

fix: Add some missing headers for GCC 14

---

Examples/Scripts/Python/truth_tracking_gsf.py
Examples/Scripts/Python/truth_tracking_gx2f.py
Examples/Scripts/Python/truth_tracking_kalman.py

- The ODD was never set correctly
- We usually want to run on the ODD and only have the generic for quick checks.
I put the import `from acts.examples.odd import getOpenDataDetector` under main, since usually, we want to call the `runTruthTrackingFITTERNAME()` from outside.

refactor: truth tracking examples: fix ODD setup and make default

---

Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp
Core/src/TrackFitting/GlobalChiSquareFitter.cpp
Examples/Algorithms/TrackFitting/include/ActsExamples/TrackFitting/TrackFitterFunction.hpp
Examples/Algorithms/TrackFitting/src/GlobalChiSquareFitterFunction.cpp
Examples/Python/python/acts/examples/reconstruction.py
Examples/Python/src/TrackFitting.cpp
Tests/UnitTests/Core/TrackFitting/Gx2fTests.cpp
docs/core/reconstruction/track_fitting.md

Instead of telling the fitter to fit some components like qop or T, we let it figure out, if there is enough information.

refactor!: (gx2f) remove `zeroField` option and make implicit

---

docs/_extensions/lazy_autodoc.py
docs/core/propagation.md

After https://github.com/acts-project/acts/pull/2849 and https://github.com/acts-project/acts/pull/2850 it is time to update the documentation of our navigators. I also included a line about the `DetectorNavigator`.
blocked by
- https://github.com/acts-project/acts/pull/2850

docs: Update navigators documentation

---

Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp

Somehow the GX2F was so perfect, that no errors occurred until I got today
```
terminate called after throwing an instance of 'std::bad_variant_access'
what():  std::get: wrong index for variant
```

fix(gx2f): forward propagation error

---

CONTRIBUTING.rst
Core/include/Acts/Utilities/BoundingBox.hpp
Core/include/Acts/Utilities/BoundingBox.ipp
README.md
docs/acts_project.md
docs/conf.py
docs/contribution/profiling.md
docs/getting_started.md
docs/white_papers.toml
docs/white_papers/how_to_add.md

I didn't update
- doxygen.org -> doxygen.nl, because the org page is their official intention
- http://mozilla.org/MPL/2.0/ -> https://www.mozilla.org/en-US/MPL/2.0/, because we have it in all headers like this.
- (contribution/guide: line  138) redirect  http://alistapart.com/article/the-art-of-the-commit - permanently to https://alistapart.com/article/the-art-of-the-commit/
- (contribution/guide: line   78) redirect  http://git-scm.com/docs/gittutorial - permanently to https://git-scm.com/docs/gittutorial
- (contribution/guide: line  138) redirect  http://chris.beams.io/posts/git-commit/ - permanently to https://cbea.ms/git-commit/
- ( getting_started: line    5) redirect  http://boost.org - permanently to https://www.boost.org/
- ( getting_started: line   37) redirect …

docs: update links to avoid redirects

---

docs/conf.py

- `eigen.tuxfamily.org` proofed itself to be quite unstable. Let's keep it in.
The rest seems to have fixed their issues with the certificates or we don't link to their pages anymore.
Thanks to @benjaminhuth on the idea with the extra comments, since git blame is annoying, when there is a refactoring.
- `cbea.ms` had a certificate problem [MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT](about:certerror?e=nssBadCert&u=https%3A//cbea.ms/&s=badStsCert&c=UTF-8&d=%20#certificateErrorDebugInformation). They fixed it apparently in the meantime (^.^)

docs: update linkcheck

---

Tests/UnitTests/Core/Propagator/NavigatorTests.cpp

The test-time for build_debug grew significantly after:
- https://github.com/acts-project/acts/pull/2849
- https://github.com/acts-project/acts/pull/2850
Before:
```
Start 127: Navigator
127/239 Test #127: Navigator ............................   Passed   22.29 sec
```
TryAllNavigator:
```
Start 128: Navigator
128/240 Test #128: Navigator ............................   Passed  1041.82 sec
```
TryAllOverstepNavigator:
```
Start 128: Navigator
128/240 Test #128: Navigator ............................   Passed  3994.42 sec
```
This PR reduces the number of tests with the try-all-references from 500 to 10. This results in a test time of around 200 sec.
Maybe we should adapt the test in the future to get more tests in a similar time.

test: reduce navigator tests with TryAll as reference

---

Plugins/GeoModel/src/detail/GeoModelBinningHelper.cpp

The GeoModelPlugin needed an update to the `detail::` removal from the axis.
This is it.

fix: GeoModelHelper update to remove of detail namespace

---

Examples/Algorithms/Vertexing/include/ActsExamples/Vertexing/AdaptiveMultiVertexFinderAlgorithm.hpp
Examples/Algorithms/Vertexing/src/AdaptiveMultiVertexFinderAlgorithm.cpp
Examples/Python/python/acts/examples/reconstruction.py
Examples/Python/src/Vertexing.cpp
Examples/Scripts/Python/full_chain_odd.py

Until now it was not possible to change the grid granularity of the `AdaptiveGridSeeder` for the `AMVF` which makes it hard to study effects of these parameters on the performance (physics and CPU). I am wiring these parameters here.
Example of how to use this
```
addVertexFitting(
...
vertexFinder=VertexFinder.AMVF,
seeder=acts.VertexSeedFinder.AdaptiveGridSeeder,
useTime=True,
spatialBinExtent=15.0 * u.um,
temporalBinExtent=19.0 * u.mm,
)
```

feat: Wire grid size for `AMVF` and `AdaptiveGridSeeder` to Python in Examples

---

Core/include/Acts/Surfaces/SurfaceMergingException.hpp
Core/src/Surfaces/CylinderSurface.cpp
Core/src/Surfaces/DiscSurface.cpp
Tests/UnitTests/Core/Surfaces/CylinderSurfaceTests.cpp
Tests/UnitTests/Core/Surfaces/DiscSurfaceTests.cpp

This switches the surface merging introduced in #3288 over to a dedicated exception `SurfaceMergingException`.

refactor(geometry): Surface merging uses custom exception

---

Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp

I stumbled over this during the Athena integration. Athena uses a different track container and track type. This messes up stuff with our templating.
Again a mistake resulting from premature optimisation.

fix(gx2f): compatible with non-Vector-TrackContainer (e.g. in Athena)

---

Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp
Examples/Io/Root/src/RootTrackSummaryWriter.cpp
Tests/UnitTests/Core/TrackFitting/Gx2fTests.cpp

`size_t`-columns are not supported in athena. This should be fine for the fitter, since we don't expect values larger than 2000 or so to be in there. Usually we have values around 4-6.

refactor(gx2f): change type of Gx2fnUpdateColumn to uint32_t (athena compatability)

---

Core/include/Acts/Geometry/GeometryContext.hpp
Core/include/Acts/Propagator/Navigator.hpp
Core/include/Acts/Surfaces/PerigeeSurface.hpp
Core/include/Acts/Surfaces/Surface.hpp
Core/include/Acts/Surfaces/SurfaceConcept.hpp
Core/src/Surfaces/PerigeeSurface.cpp
Core/src/Surfaces/Surface.cpp
Tests/UnitTests/Core/Surfaces/CylinderSurfaceTests.cpp
Tests/UnitTests/Core/Surfaces/PerigeeSurfaceTests.cpp
Tests/UnitTests/Core/Surfaces/StrawSurfaceTests.cpp
Tests/UnitTests/Plugins/Json/SurfaceJsonConverterTests.cpp

I'm adding a way that allows you to avoid having to write
```cpp
surface->toStream(gctx, std::cout);
std::cout << std::endl;
```
and instead write
```cpp
std::cout << surface->toStream(gctx) << std::endl;
```
This is done by returning a temporary helper struct that implements `operator<<`.

feat: `Surface::toStream` overload without stream argument

---

Core/include/Acts/Utilities/detail/Subspace.hpp
Tests/UnitTests/Core/Utilities/SubspaceTests.cpp

As an alternative to the existing `Acts::detail::FixedSizeSubspace` I implement `VariableSizeSubspace` which is very similar except that the actual size of the subspace can be runtime dependent.
Pulled out of https://github.com/acts-project/acts/pull/3107

feat: `VariableSizeSubspace`

---

.github/labeler.yml

allow the label bot to label a PR in a rst file has been modified

docs: Label as docs changes to rst files

---

CI/missing_include_check.sh
Core/include/Acts/EventData/GenericParticleHypothesis.hpp

I'm afraid this was left behind when we migrated to c++20

ci: Move missing include test from c++17 to c++20

---

docs/conf.py

This allows us to fix this without creating pull-requests every time anything goes down.

docs: Load linkcheck ignore patterns from URL

---

Examples/Python/python/acts/examples/simulation.py

Small rework of the `particles_selected` handling in Python. I create dedicated whiteboard entries for the different simulators and then alias them to `particles_selected`. This allows for reassignment of `particles_selected` later and moves the alias also to the post selection after simulation

refactor: Rework `particles_selected` handling in Python Examples

---

Core/src/EventData/VectorTrackContainer.cpp

Small fix otherwise `removeTrack` will cause assertions to fire later

fix: `VectorTrackContainer::removeTrack_impl`

---

Examples/Python/src/Propagation.cpp
Examples/Scripts/Python/propagation.py

This mini-PR allows to test and use the simply stepper from the Examples

feat: adding sympy stepper to python bindings

---

Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp

In the CKF we rely on a custom path limit handling and want to disable the one from the propagator. I think this was the case once with `StubPathLimitReached` being there but might have been overwritten with a merge failure.
Apart from that I tweak the error handling again to propagate them to the user.

fix: Improve CKF error handling and fix path limit abortion

---

.github/workflows/builds.yml

It appears that the MacOS build broke because of a change of the software stack of the runner. We do not have control over that so I rebuilt the dependencies in the hope this resolves the problem.

ci: Update MacOS dependencies

---

Core/include/Acts/Geometry/CuboidVolumeBuilder.hpp
Core/src/Geometry/CuboidVolumeBuilder.cpp

This lets us set in the config also other dimension than the previous `BinningValue::binX`. This is necessary, if we want to build a detector that is not parallel to the x-axis.
The default value stays `BinningValue::binX` to not break anything.
Volumes will be connected only in X-direction, since `BoundarySurfaceFace::positiveFaceYZ` is hardcoded. It might be possible to generalise this, but I didn't need that feature and it might overcomplicate the builder.

fix: select binning dimension in cuboid volume builder

---

.gitlab-ci.yml

When using CMake's FetchContent mechanism, the source code for those dependencies ends up in the `build/_deps/` directory, which was previously subject to analysis by clang-tidy, which can lead to errors rooted in external projects. This commit disables clang-tidy for that directory, resolving the issue.
This commit comes from #3117.

ci: Disable clang-tidy for external dependencies

---

.github/workflows/analysis.yml

https://github.com/acts-project/acts/pull/3135 broke `build_performance` which was not observed in the PR because this job only runs on the main branch

ci: Fix `build_performance` GitHub CI job after #3135

---

.github/workflows/builds.yml
.gitlab-ci.yml

The physmon job strangely fails with negative y errors for some ratio plot in the seeding, but only **sometimes**. This smells like a non-reproducibility. I'm bumping histcmp here which should have a guard against the negative values.

ci: bump histcmp to 0.6.7 to try to fix yerr issue

---

Examples/Framework/include/ActsExamples/Framework/Sequencer.hpp
Examples/Framework/src/Framework/Sequencer.cpp

- Add missing new line back in
- Rename to `csv` from `tsv`

fix: Add missing newline for `Sequencer` `timing.csv` in Examples

---

CONTRIBUTING.rst
docs/contribution/run_formatting.md

The image does not exist anymore.

docs: Remove link to clang-format image from docs

---

Core/src/Propagator/SympyStepper.cpp
Core/src/Propagator/codegen/sympy_stepper_math.hpp
codegen/generate_sympy_stepper.py

A missing B field is not correctly handled in the `SympyStepper` and can result in segmentation faults.
Fixes
- https://github.com/acts-project/acts/issues/3523

fix: Handle missing field in `SympyStepper`

---

Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp

Removes some unnecessary navigation limits from the GX2F.
Not necessary anymore, since we have the same limit already in the beginning of the actor.
This limit was set to abort the navigation, even if not all measurements have been found. The navigation in the GX2F is now stable enough, that we don't need this limit anymore

refactor(gx2f): remove outdated navigation abort conditions

---

Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp

This is causing FPEs in Athena which seem to originate from the ambiguity solver. I suspect that the reason is not setting `ndf` in the CKF which is then directly passed to the ambi in Athena

revert: "refactor: Remove `calculateTrackQuantities` from Core CKF (#3536)"

---

.github/pull_request_template.md
.pre-commit-config.yaml
CI/check_boost_test_macro.sh
CI/check_include_guards.py
CI/check_license.py
CI/check_pragma_once.sh
CI/check_type_t.py
CI/codespell_ignore.txt
CITATION.cff
CMakeLists.txt
CONTRIBUTING.rst
Fatras/include/ActsFatras/Digitization/PlanarSurfaceMask.hpp
Fatras/include/ActsFatras/Digitization/Segmentizer.hpp
Fatras/include/ActsFatras/Kernel/ContinuousProcess.hpp
Fatras/include/ActsFatras/Kernel/InteractionList.hpp
Fatras/include/ActsFatras/Kernel/Simulation.hpp
Fatras/include/ActsFatras/Kernel/detail/SimulationActor.hpp
Fatras/include/ActsFatras/Physics/ElectroMagnetic/PhotonConversion.hpp
Fatras/include/ActsFatras/Selectors/SelectorHelpers.hpp
Fatras/src/Digitization/DigitizationError.cpp
Fatras/src/Digitization/PlanarSurfaceDrift.cpp

Use pre-commit for more of our linting. I'm adding local-only hooks for most of the check scripts we run in the CI, and I'm adding a codespell hook.
The pre-commit CI job will now implicitly also run these checks, but I suggest we keep the dedicated jobs for now and remove them at a later time if we want.

ci: Add pre-commit hooks for most of our linting

---

Core/include/Acts/Propagator/EigenStepperDenseExtension.hpp
Tests/IntegrationTests/PropagationDenseConstant.cpp
Tests/UnitTests/Core/Propagator/EigenStepperTests.cpp
Tests/UnitTests/Core/Propagator/PropagatorTests.cpp
docs/core/propagation.md

During Athena integration I realized that the naming is a bit inconsistent with `EigenStepperDefaultExtension` and `EigenStepperDenseEnvironmentExtension`. I think `EigenStepperDenseExtension` fits better.

refactor!: Rename `EigenStepper` dense extension

---

Plugins/Detray/src/DetrayGeometryConverter.cpp

The geometry ID was not correctly added to the detray portals, this mini-PR fixes this.

fix: adding GeomentryId to detray portals

---

Core/include/Acts/Visualization/EventDataView3D.hpp
Core/include/Acts/Visualization/GeometryView3D.hpp
Core/include/Acts/Visualization/ViewConfig.hpp
Core/src/Visualization/GeometryView3D.cpp
Examples/Io/Obj/include/ActsExamples/Plugins/Obj/ObjTrackingGeometryWriter.hpp
Examples/Python/src/Obj.cpp
Tests/UnitTests/Core/Geometry/ProtoLayerHelperTests.cpp
Tests/UnitTests/Core/TrackFitting/Gx2fTests.cpp
Tests/UnitTests/Core/Visualization/EventDataView3DBase.hpp
Tests/UnitTests/Core/Visualization/PrimitivesView3DBase.hpp
Tests/UnitTests/Core/Visualization/TrackingGeometryView3DBase.hpp
Tests/UnitTests/Plugins/Geant4/Geant4DetectorSurfaceFactoryTests.cpp
Tests/UnitTests/Plugins/TGeo/TGeoArb8ConversionTests.cpp
Tests/UnitTests/Plugins/TGeo/TGeoBBoxConversionTests.cpp
Tests/UnitTests/Plugins/TGeo/TGeoTrd1ConversionTests.cpp
Tests/UnitTests/Plugins/TGeo/TGeoTrd2ConversionTests.cpp
Tests/UnitTests/Plugins/TGeo/TGeoTubeConversionTests.cpp

Allows removing the custom constructors that were used for convenience.

refactor: Make `ViewConfig` usable with designated initializers

---

Examples/Python/src/Framework.cpp

This PR allows to switch the dataflow check off, as this seemed to be unstable. 
It does not address the issue of false positive checking failures.

feat: broadcast dataflow check to python

---

CI/physmon/workflows/physmon_simulation.py
Core/include/Acts/Geometry/TrackingGeometry.hpp
Core/include/Acts/Geometry/TrackingVolume.hpp
Core/src/Geometry/TrackingGeometry.cpp
Core/src/Geometry/TrackingVolume.cpp
Core/src/Material/SurfaceMaterialMapper.cpp
Examples/Algorithms/MaterialMapping/include/ActsExamples/MaterialMapping/MappingMaterialDecorator.hpp
Examples/Io/Root/src/RootMaterialWriter.cpp
Examples/Python/src/Geometry.cpp
Examples/Scripts/Python/full_chain_odd.py
Examples/Scripts/Python/full_chain_odd_LRT.py
Plugins/Json/src/MaterialMapJsonConverter.cpp
Tests/UnitTests/Core/Propagator/NavigatorTests.cpp

- Remove the beamline surface from `TrackingGeometry` (essentially unused)
- Remove unneeded shared ptr access to the highest volume
- `TrackingGeometry` holds the world volume as a mutable

refactor: TrackingGeometry interface cleanup

---

Examples/Python/src/Base.cpp

This aligns the algebra API in python more closely with the C++ one. While I don't want to add too much binding code, I think it's preferable to stick to the Eigen API rather than make up extra custom API just for the sake of exposing it to Python.
To this end, I'm exposing more constructors for the `Vector` classes, and adding `Translation3` and `AngleAxis3` as Python types, and allow operators for multiplication and so on between transforms.
At the same time, I'm using this PR to also align some enums we expose to the C++ ones.

refactor: Improved Python bindings for algebra types

---

Core/include/Acts/EventData/MultiTrajectory.hpp

This small PR adds an post-increment operator to the multitrajectory iterator, as well as `cbegin` and `cend` methods.

feat: Improvements to multitrajectory iterators

---

CMakeLists.txt
cmake/ActsExternSources.cmake

This PR synchronises the versions between `_acts_<external>_version` and the `cmake/ActsExternalSources.cmake` file, they have diverged at many places.

chore: synchronize versions

---

Core/src/Geometry/GridPortalLinkMerging.cpp
Core/src/Geometry/Portal.cpp
Core/src/Geometry/PortalLinkBase.cpp
Core/src/Surfaces/CylinderSurface.cpp
Core/src/Surfaces/DiscSurface.cpp

Reduces the output level for some outputs. Some where erroneously WARNINGs, some were DEBUG where VERBOSE makes more sense.

refactor(geo): Portal(Link)+Surface verbosity reduction

---

Core/include/Acts/Utilities/GraphViz.hpp
Core/src/Utilities/CMakeLists.txt
Core/src/Utilities/GraphViz.cpp
Tests/UnitTests/Core/Utilities/CMakeLists.txt
Tests/UnitTests/Core/Utilities/GraphVizTests.cpp

Adds some helper types to work with GraphViz output.
This allows writing code like 
```cpp
Node node1{.id = "node1",
.label = "Node 1",
.shape = Shape::Ellipse,
.style = {Style::Filled}};
ss << node1;
Node node2{.id = "node2",
.label = "Node 2",
.shape = Shape::Rectangle,
.style = {Style::Dashed}};
Edge edge = {.from = node1, .to = node2, .style = Style::Dashed};
ss << edge;
```
and get valid GraphViz output.

feat(util): Add GraphViz helper types

---

Examples/Algorithms/Digitization/include/ActsExamples/Digitization/DigitizationAlgorithm.hpp
Examples/Algorithms/Digitization/include/ActsExamples/Digitization/DigitizationConfig.hpp
Examples/Algorithms/Digitization/src/DigitizationAlgorithm.cpp
Examples/Python/src/Digitization.cpp

The current ditigization algorithm makes a round-trip from simulated hits to cells to clusters to measurements, but it doesn't allow us to keep the intermediate cell data to test custom clusterization implementations such as the one in traccc. This PR adds to additional flags to the digitization algorithm configuration, namely `doClusterization` and `doOutputCells`. The first flag enables or disables the clusterization, and the second one enables the saving of intermediate cell data. Also adds relevant data handles.

feat: Allow digitization to save cells

---

Core/include/Acts/TrackFitting/MbfSmoother.hpp
Core/src/TrackFitting/MbfSmoother.cpp

refactor: Reduce abuse of auto in mbf smoother

---

docs/misc/spack.md

The current Spack documentation recommends a Spack spec which can be used to build ACTS and all its plugins; this is useful but, as we encountered over the weekend, also takes a lot of build time. As such, I wanted to add additional instructions for a simplified Spack build which only allows you to build the core ACTS library.

docs: Add minimal Spack spec for ACTS core

---

Core/include/Acts/EventData/Seed.hpp
Core/include/Acts/EventData/Seed.ipp
Tests/UnitTests/Core/EventData/CMakeLists.txt
Tests/UnitTests/Core/EventData/SeedEdmTests.cpp

Future support for seeds created from `N` space points, with `N >= 3`.
The seed EDM naturally support the possibility of requiring more than 3 space points, so the Seed class is now templated on both the external space point type and the required number of space points: `Seed<external_spacepoint_t, N>`.
By default `N == 3`, and there is a requirement that `N >= 3`.
The default values is to avoid a breaking change in the code.
This PR requires https://github.com/acts-project/acts/pull/3432

feat: Support seed from N space points

---

Examples/Io/Json/include/ActsExamples/Io/Json/JsonSurfacesReader.hpp
Examples/Io/Json/src/JsonSurfacesReader.cpp
Examples/Python/src/Json.cpp

This PR adds a function to the `JsonSurfacesReader` that allows to read in a flat container rather than a Hierarchy map:
```python
>>> import acts
>>> from acts import examples
>>> sOptions = acts.examples.SurfaceJsonOptions()
>>> sOptions.inputFile = "some_sensitive_mod.json"
>>> sOptions.jsonEntryPath = ["surfaces"]
>>> surfaces = acts.examples.rreadSurfaceVectorFromJson(sOptions)
>>> print(len(surfaces))
16668
>>> geoContext = acts.GeometryContext()
>>> viewConfig = acts.ViewConfig()
>>> acts.examples.writeSurfacesObj(surfaces, geoContext, viewConfig, "some-surfaces.obj")
```
will work with this out of the box.

feat: adding possibility to read flat surface container

---

Tests/UnitTests/Core/TrackFitting/Gx2fTests.cpp

we forgot to remove this after removing the corresponding unit test.

test(gx2f): remove ToyDetectorYdirection relic

---

Core/include/Acts/Propagator/MultiEigenStepperLoop.hpp
Tests/UnitTests/Core/Propagator/MultiStepperTests.cpp
docs/core/reconstruction/track_fitting.md

After https://github.com/acts-project/acts/pull/3521 we also want to change the default and remove the weighted mean reduction as it is unstable.
This pull request primarily focuses on removing the `WeightedComponentReducerLoop` struct and its associated functionality from the `MultiEigenStepperLoop` class and its tests. The changes simplify the codebase by eliminating the weighted component reduction logic and replacing it with the `MaxWeightReducerLoop`.
* [`Core/include/Acts/Propagator/MultiEigenStepperLoop.hpp`](diffhunk://#diff-2ec4ab79520c414c4eb526d00ede45a6a10f8eeba06398d81c315f9be5686e9eL48-L145): Removed the `WeightedComponentReducerLoop` struct and its methods, which were responsible for reducing the multicomponent state by summing weighted values.
* …

refactor!: Remove mean reduction from `MultiEigenStepperLoop`

---

CI/test_coverage.py

Fix following messages:
```console
/__w/acts/acts/build/../CI/test_coverage.py:44: SyntaxWarning: invalid escape sequence '\d'
map(int, re.match("gcovr (\d+\.\d+)", gcovr_version_text).group(1).split("."))
/__w/acts/acts/build/../CI/test_coverage.py:66: SyntaxWarning: invalid escape sequence '\.'
excludes = ["-e", "../Tests/", "-e", ".*json\.hpp"]
```

fix: Fix Warning messages

---

Core/include/Acts/Geometry/Extent.hpp
Tests/UnitTests/Core/Geometry/ExtentTests.cpp

This pull request introduces a new constructor for the `ExtentEnvelope` struct using a helper struct for designated initialization, and includes corresponding unit tests to ensure its functionality. The most important changes include the addition of the `Arguments` helper struct, the new constructor, and a new test case in the unit tests.
Enhancements to `ExtentEnvelope` struct:
* [`Core/include/Acts/Geometry/Extent.hpp`](diffhunk://#diff-82ced51a7d9c573938c161066e15e9d21194b2ca79b3033d8519b1317e6d18d6R77-R103): Added a new helper struct `Arguments` for designated initializer construction and a corresponding constructor in `ExtentEnvelope` to utilize this struct.
Unit tests:
* [`Tests/UnitTests/Core/Geometry/ExtentTests.cpp`](diffhunk://#diff-ec39444b2939b7caa485e011248f941d88a3d46a9e57f38 …

feat(geo): Extent designated initialization

---

Tests/UnitTests/Core/EventData/CMakeLists.txt
Tests/UnitTests/Core/EventData/SpacePointContainerEdmTests.cpp
Tests/UnitTests/Core/Seeding/SeedFinderTest.cpp

Adds some unit test for the space point edm, with also checks on the types
Requires https://github.com/acts-project/acts/pull/3689 to compile (already merged)

feat: Add test for space point edm

---

Core/include/Acts/Seeding/SeedFinder.hpp
Core/include/Acts/Seeding/SeedFinder.ipp

Seeding is done one bin at a time. Where the bin corresponds to the area where the middle space point candidate may be.
That means that all middle space points processed by each call of `createSeedsForGroup` belong to the same bin and thus have the same z-bin.
In case a `rRangeMiddleSP` vector is provided by the user (that is the case where the radius validity range changes according to the z-bin), we have to retrieve from the middle space point the z-bin and then the right validity range. In the current code this is done for every middle space point in the bin! 
We can do it only once.

refactor: Only compute middle range once per bin

---

Core/include/Acts/Geometry/CompositePortalLink.hpp
Core/include/Acts/Geometry/GridPortalLink.hpp
Core/include/Acts/Geometry/TrivialPortalLink.hpp
Core/src/Geometry/CompositePortalLink.cpp
Core/src/Geometry/GridPortalLink.cpp
Core/src/Geometry/Portal.cpp
Core/src/Geometry/PortalLinkBase.cpp
Core/src/Geometry/TrivialPortalLink.cpp
Tests/UnitTests/Core/Geometry/PortalLinkTests.cpp
Tests/UnitTests/Core/Geometry/PortalTests.cpp

This PR does three things:
- `PortalLinkBase::merge` **no longer** does merging of grids or trivials into a combined grid. This has been observed to lead to accumulating floating point imprecision.
- `CompositePortalLink` gets a method to make a grid **if** (and only if) it is composed of a set of `TrivialPortalLink`s.
- `Portal::fuse` will attempt to convert `CompositePortalLink`s composed of only `TrivialPortalLink`s to a single `GridPortalLink` before fusing it with the other portal.
In combination, this avoids the floating point issues and produces correctly sized grids.
Part of #3502.
---
This pull request introduces several enhancements and bug fixes to the `Core/include/Acts/Geometry` module, focusing on improving the `CompositePortalLink` and `GridPortalLink` classes. The most …

feat: Delayed Grid construction for Portals

---

Core/include/Acts/Geometry/CylinderVolumeBounds.hpp
Core/include/Acts/Geometry/PortalShell.hpp
Core/src/Geometry/PortalShell.cpp
Examples/Python/src/Base.cpp
Examples/Python/src/Geometry.cpp
Tests/UnitTests/Core/Geometry/PortalShellTests.cpp

This is a collection of python bindings bits that have accumulated.
Related #3502.
---
This pull request includes several updates to the `Acts` geometry and Python binding code. The most important changes involve the introduction of new enums and the addition of Python bindings for new geometry classes and methods.
* Added `Face` enum to `CylinderVolumeBounds` to describe possible faces of a cylinder volume. (`Core/include/Acts/Geometry/CylinderVolumeBounds.hpp`)
* Refactored `PortalShellBase` to use the `Face` enum from `CylinderVolumeBounds` instead of defining its own. (`Core/include/Acts/Geometry/PortalShell.hpp`)
* Added new binning values to the `addBinning` function in `Base.cpp`. (`Examples/Python/src/Base.cpp`)
* Extended `addGeometry` function to include new methods and enums …

refactor: Python binding bits and pieces

---

Core/src/Detector/detail/BlueprintDrawer.cpp
Examples/Python/src/GeoModel.cpp
Plugins/GeoModel/include/Acts/Plugins/GeoModel/GeoModelBlueprintCreater.hpp
Plugins/GeoModel/src/GeoModelBlueprintCreater.cpp

This PR adds the option to create a dot graph from GeoModel in the Gen2 geometry, which will help debugging as long as Gen2 is alive and around.

feat: adding dot graph possibility

---

Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp
Core/include/Acts/TrackFinding/MeasurementSelector.ipp

Combines the handling of material, measurements and holes in the Core CKF.
---
This pull request includes several changes to the `CombinatorialKalmanFilter` class in the `Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp` file to improve error handling, state management, and logging. Additionally, there is a minor change in the `MeasurementSelector` class to handle empty measurement candidates more gracefully.
* Added checks and logging for empty active branches to ensure the filter stops correctly when no branches are active. (`Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp`) [[1]](diffhunk://#diff-55dd901875f5a87b6a9fee495de245296efbfd45aa9f9483036bcd299a277e09R583-R590) [[2]](diffhunk://#diff-55dd901875f5a87b6a9fee495de245296efbfd45aa9f9483036bcd299a277e09R660-R …

refactor: Combine material, measurement and hole handling in Core CKF `filter`

---

Core/src/Geometry/TrackingVolume.cpp

This is not actually correct, as the boundary surfaces are created unconditionally.

fix: Incorrect sanity check in TrackingVolume removed

---

Core/include/Acts/Seeding/SeedFinder.ipp

One of the criterion used in doublet finding relies on computing the minimal distance between the origin and the straight line connecting the two points of the doublet. This distance is compared against a maximum impact parameter (`impactMax`) provided by the user. 
Let's consider for instance the middle-top doublet search. 
In the attached image:
- `A` is the origin
- `B` is the middle space point, thus `AB = rM` (radius of middle space point) 
- `C` is the top space point
What the code does is to compute `BD` (`xNewFrame` in the code) and `CD` (`yNewFrame` in the code)  and then a simple geometric similarity to compute the impact parameter. 
The code currently does: `Im / CD = AB / BD`, where `Im` is the impact parameter we are trying to compute.  Thus `Im = (AB * CD) / BD <= …

docs: Add comment on computation of impact parameter from the doublet

---

CMakePresets.json
Examples/Framework/src/Framework/Sequencer.cpp
Plugins/FpeMonitoring/CMakeLists.txt
Plugins/FpeMonitoring/include/Acts/Plugins/FpeMonitoring/FpeMonitor.hpp
Plugins/FpeMonitoring/src/FpeMonitor.cpp

This PR
- Changes the way FPE monitoring configures `boost::stacktrace`: the fallback to `addr2line` is dropped as that doesn't work anyway
- Change explicit `-Werror` in the CI to `CMAKE_COMPILE_WARNING_AS_ERROR=ON`
- This is not applied in `try_compile`, which would otherwise cause false negatives because there are warnings we don't control.
- Add a static method in `FpeMonitor` that returns if `backtrace` / symbolization support is on or not.
- Make the sequencer fail early if it's configured to run the FPE monitor, has masks configured and symbolization is not supported.

fix: FPE monitoring boost discovery, addr2line fallback

---

Core/include/Acts/EventData/GenericBoundTrackParameters.hpp
Core/include/Acts/EventData/GenericCurvilinearTrackParameters.hpp
Core/include/Acts/EventData/GenericFreeTrackParameters.hpp
Core/include/Acts/EventData/TransformationHelpers.hpp
Core/src/EventData/TransformationHelpers.cpp
Tests/UnitTests/Core/EventData/BoundTrackParametersTests.cpp
Tests/UnitTests/Core/EventData/CurvilinearTrackParametersTests.cpp
Tests/UnitTests/Core/EventData/FreeTrackParametersTests.cpp

Add helper functions to reflect track parameters. This is useful when seed parameters are estimated for the spacepoints in reverse direction which is necessary for strip seeds.
---
This pull request introduces functionality to reflect track parameters for both bound and free track parameters in the Acts framework. The key changes include adding new methods to reflect parameters and the corresponding implementation to handle the reflection logic.
* [`Core/include/Acts/EventData/GenericBoundTrackParameters.hpp`](diffhunk://#diff-b3a2aaa0a0f138a1b44e7e6494aae4f8b905ad83716a4253bbea6446623f0eb1R253-R263): Added `reflectInplace` and `reflect` methods to `GenericBoundTrackParameters` to enable in-place reflection and returning reflected parameters.
* …

feat: Allow reflection of track parameters

---

.github/workflows/analysis.yml
.github/workflows/builds.yml
.gitlab-ci.yml

- reset all the `ccache` caches by bumping `CCACHE_KEY_SUFFIX` up to `r2`
- rework key naming scheme
- GitHub `ccache-${{ runner.os  }}-${{ github.job }}-${{ env.CCACHE_KEY_SUFFIX }}-${{ github.sha }}`
- GitLab `ccache-${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}-${CCACHE_KEY_SUFFIX}`
- GitLab: restore cache from main branch if there is none for the current branch

ci: Reset `ccache` caches

---

CI/check_unused_files.py

These 2 files don't exist anymore, so we don't need them anymore in the exclude-list.

chore: update exclude list for unused files

---

Core/include/Acts/Utilities/DelegateChainBuilder.hpp

fix: Make callable args universal references

---

README.md

This is a relic from codecov. We fully switched to sonarcloud.

chore: change coverage badge from codecov to sonarcloud

---

Core/include/Acts/Seeding/SeedFinder.hpp

The concept definition was not generic enough to cover for cases with `N != 3ul`

fix: Wrong definition of the constraint

---

Core/include/Acts/Seeding/SeedFinderOrthogonal.hpp

Uses `getDummyLogger` to restore the default constructor for the orthogonal seed finder. See #3807.

fix: Restore Orthogonal seedfinder default constructor

---

Core/include/Acts/Geometry/PortalShell.hpp
Core/src/Geometry/PortalShell.cpp
Tests/UnitTests/Core/Geometry/PortalShellTests.cpp

This renames the `connectOuter` method in `PortalShell` to just `fill`, because that is more descriptive of what it actually does.
Part of #3502

refactor: rename PortalShell connect outer to fill

---

.gitlab-ci.yml

These are already set with ``:
```
{
"name": "gitlab-ci-clangtidy",
"displayName": "GitLab-CI",
"inherits": "ci-common",
"cacheVariables": {
"ACTS_BUILD_ODD": "OFF",
"ACTS_BUILD_EXAMPLES_PYTHON_BINDINGS": "OFF",
"ACTS_RUN_CLANG_TIDY": "ON"
}
},
```

chore: remove redundant cmake flags

---

Core/include/Acts/EventData/detail/TestSourceLink.hpp
Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp
Core/include/Acts/TrackFitting/KalmanFitter.hpp

After @CarloVarni's update in https://github.com/acts-project/traccc/pull/765, I became unable to build [traccc](https://github.com/acts-project/traccc) with [oneAPI 2025.0.0](https://www.intel.com/content/www/us/en/developer/articles/release-notes/intel-oneapi-toolkit-release-notes.html). 😦 
The issue being solved here is of the type:
```
[159/737] Building CXX object Core/CMakeFiles/ActsCore.dir/src/TrackFitting/GlobalChiSquareFitter.cpp.o
FAILED: Core/CMakeFiles/ActsCore.dir/src/TrackFitting/GlobalChiSquareFitter.cpp.o
/software/intel/oneapi-2025.0.0/compiler/2025.0/bin/compiler/clang++  --gcc-toolchain=/software/gcc/13.3.0/x86_64-el9 -DActsCore_EXPORTS -I/home/krasznaa/ATLAS/projects/acts/acts/Core/include -I/home/krasznaa/ATLAS/projects/acts/build-oneapi/Core -isystem …
```

fix: oneAPI 2025 Fixes, main branch (2024.11.11.)

---

Examples/Io/Root/src/RootMaterialTrackReader.cpp
Examples/Io/Root/src/RootParticleReader.cpp
Examples/Io/Root/src/RootTrackSummaryReader.cpp
Examples/Io/Root/src/RootVertexReader.cpp
Examples/Scripts/TrackingPerformance/TreeReader.h

Extending the fix from here https://github.com/acts-project/acts/pull/3870 to other places.
See also discussion here https://mattermost.web.cern.ch/acts/pl/gp9mw1y1njr4bjxmbhurk1b4me
blocked by
- https://github.com/acts-project/acts/pull/3870

fix: Estimate entry size before sorting in ROOT readers

---

Core/include/Acts/Utilities/Logger.hpp

This popped up as a warning in the ATLAS build:
```
/builds/acts/acts-athena-ci/acts-install/include/Acts/Utilities/Logger.hpp:485:61: warning: Non reentrant function 'localtime' called. For threadsafe applications it is recommended to use the reentrant replacement function 'localtime_r'. [localtimeCalled]
std::strftime(buffer, sizeof(buffer), m_format.c_str(),
localtime(&t));
```

fix: User `localtime_r` instead of `localtime`

---

Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp

I think outputs that run on every single event should generally not be INFO.

refactor: Reduce abort output in GX2F to DEBUG

---

Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp

Check expected measurement during track finding before marking state as hole
@andiwand

fix: Add check on expected measurements on surface before marking as hole

---

Examples/Detectors/ITkModuleSplitting/include/ActsExamples/ITkModuleSplitting/ITkModuleSplitting.hpp
README.md
docs/license.rst

We had the docs test failing quite frequently during the last week, like in here: https://github.com/acts-project/acts/actions/runs/11990353442/job/33427764861?pr=3896 due to
```
(         license: line    4) broken    http://mozilla.org/MPL/2.0/ - 404 Client Error: Not Found for url: https://www.mozilla.org/en-US/mpl/2.0/
```
It seems, that mozilla forwards http sometimes to the wrong address with everything lovercase, which makes problems with `mpl` vs `MPL`.

docs: remove http-relics for license

---

Core/include/Acts/Material/BinnedSurfaceMaterial.hpp
Core/include/Acts/Material/GridSurfaceMaterial.hpp
Core/include/Acts/Material/HomogeneousSurfaceMaterial.hpp
Core/include/Acts/Material/HomogeneousVolumeMaterial.hpp
Core/include/Acts/Material/ISurfaceMaterial.hpp
Core/include/Acts/Material/Material.hpp
Core/include/Acts/Material/MaterialSlab.hpp
Core/include/Acts/Material/ProtoSurfaceMaterial.hpp
Core/src/Material/BinnedSurfaceMaterial.cpp
Core/src/Material/HomogeneousSurfaceMaterial.cpp
Core/src/Material/HomogeneousVolumeMaterial.cpp
Core/src/Material/Material.cpp
Core/src/Material/MaterialSlab.cpp
Examples/Io/Root/src/RootMaterialTrackWriter.cpp
Plugins/Json/include/Acts/Plugins/Json/MaterialJsonConverter.hpp
Tests/UnitTests/Core/Material/GridSurfaceMaterialTests.cpp
Tests/UnitTests/Core/Material/HomogeneousSurfaceMaterialTests.cpp
Tests/UnitTests/Core/Material/ISurfaceMaterialTests.cpp
Tests/UnitTests/Core/Material/MaterialSlabTests.cpp

Accumulated changed from https://github.com/acts-project/acts/pull/3862
- use namespaces in source files
- remove operator overloads (breaking)
- move some implementations to source

chore!: Clean some Material code

---

Core/include/Acts/Propagator/MultiEigenStepperLoop.hpp
Core/include/Acts/Propagator/MultiEigenStepperLoop.ipp
Core/include/Acts/TrackFitting/detail/GsfActor.hpp
Core/include/Acts/Utilities/Intersection.hpp
Core/src/Surfaces/ConeSurface.cpp
Core/src/Surfaces/CylinderSurface.cpp
Core/src/Surfaces/DiscSurface.cpp
Core/src/Surfaces/LineSurface.cpp
Core/src/Surfaces/PlaneSurface.cpp
Tests/UnitTests/Core/Surfaces/SurfaceIntersectionTests.cpp
Tests/UnitTests/Core/Utilities/IntersectionTests.cpp

I believe such an alias is increasing confusing. I propose to remove `IntersectionStatus::missed` and replace it by `IntersectionStatus::unreachable`

refactor!: Remove alias `IntersectionStatus::missed`

---

.pre-commit-config.yaml

The pre-commit hook that checks for leftover conflict markers introduced in #3708 calls git diff. While this works well in general, I am running into an edge case where git is failing to determine that it is not being run in a TTY, causing it to fire up a pager which, in turn, causes pre-commit to hang as it waits for the pager to close. This commit fixes this issue by adding the `--no-pager` flag to the git command.

fix: Explicitly disable paging in pre-commit hook

---

.gitlab-ci.yml

This reverts commit 494bbb864edd1710d2bc357bf86efa5aa6526857.
CERN Harbor has a 1/2 day maintenance window going on: https://cern.service-now.com/service-portal?id=outage&n=OTG0153808
PLEASE DESCRIBE YOUR CHANGES.
THIS MESSAGE ENDS UP AS THE COMMIT MESSAGE.
DO NOT USE @-MENTIONS HERE!

revert: "ci: Use CERN registry cache in GitLab CI"

---

Examples/Io/Podio/src/PodioReader.cpp

Add timing to the read method of PODIO reader.

refactor: PodioReader uses scoped timer

---

Core/include/Acts/Utilities/ScopedTimer.hpp
Core/src/Utilities/ScopedTimer.cpp

Use nanoseconds in timer utility to get useful outputs out of the averaging timers.

refactor: Timer utility: use nanoseconds internally

---

cmake/ActsCompilerOptions.cmake

This reverts commit 52f80a47fb3c7fb5091659a748f1e7edae58a45e.
This is causing issues in the Athena build. i'll come back to this next week.

revert: build: Add compile check for std::format (originally #4415)

---

Core/include/Acts/EventData/SpacePointContainer2.hpp
Core/include/Acts/EventData/SpacePointProxy2.hpp
Core/include/Acts/Seeding2/CylindricalSpacePointGrid2.hpp
Core/src/Seeding2/CylindricalSpacePointGrid2.cpp
Examples/Algorithms/TrackFinding/src/GridTripletSeedingAlgorithm.cpp

- Allow to use `CylindricalSpacePointGrid2` without using the new space point EDM
- I would like to assign space points to the grid with a different EDM and then copy to the new EDM resulting in sorted ranges
- Add documentation

refactor: Improve flexibility of `CylindricalSpacePointGrid2`

---

Core/include/Acts/Geometry/MaterialDesignatorBlueprintNode.hpp
Core/src/Geometry/MaterialDesignatorBlueprintNode.cpp
Core/src/Geometry/detail/MaterialDesignator.hpp

refactor(gen3): Material designator node takes arbitrary surface material

---

CMakeLists.txt

Find vecmem before setting up the libraries that need it.
So that a pre-built vecmem installation could be used together with algebra-plugins
and detray being built by this project.
[traccc](https://github.com/acts-project/traccc) was already working, as its setup came after that of vecmem already.
The way to trigger these issues is like the following:
- First one needs to build/install [vecmem](https://github.com/acts-project/vecmem) on its own. Like:
```
[bash][atspot01]:acts > ls vecmem-1.18.0*
vecmem-1.18.0:
benchmarks  cmake  CMakeLists.txt  core  cuda  hip  LICENSE  README.md  sycl  tests
vecmem-1.18.0-build:
bin             cmake_install.cmake  CPackSourceConfig.cmake  DartConfiguration.tcl  lib       Testing
CMakeCache.txt  core …
```

build: VecMem Setup Fix

---

Core/src/Utilities/AxisDefinitions.cpp

In ePIC we noticed (upon upgrading to v39) that our material map json geometry did not get the correct `AxisPhi` and `AxisZ` binning directions (instead we got `AxisX`). This turned out to be due to the incorrect parsing of the `binPhi` and `binZ` fields. In particular, the iterator `it` in `s_legacyBinningValueNames` cannot be compared to `s_axisDirectionNames.begin()` (a different vector) to get the index.
This PR introduces an early return when the `name` is found in the `s_legacyBinningValueNames` vector. I confirmed that with this fix the json output indeed changes `CylinderBounds` from:
```json
"binUtility": {
"binningdata": [
{
"bins": 144,
"max": 3.1415927410125732,
"min": -3.1415927410125732,
"option": "closed",
"type": "equidistant",
"value": "AxisX"
},
{
"bins": 10,
"max": 0.0, …
```

fix: take iterator distance within vector in AxisDefinitions

---

Core/include/Acts/Seeding2/BroadTripletSeedFinder.hpp
Core/include/Acts/Seeding2/DoubletSeedFinder.hpp
Core/src/Seeding2/BroadTripletSeedFinder.cpp
Core/src/Seeding2/DoubletSeedFinder.cpp
Examples/Algorithms/TrackFinding/src/GridTripletSeedingAlgorithm.cpp

With https://github.com/acts-project/acts/pull/4447 the sorting requirement of the `DoubletSeedFinder` becomes an option. The same can now be done for the `BroadTripletSeedFinder`. This generalizes the use of the `BroadTripletSeedFinder` and will be beneficial for the module map approach.
blocked by
- https://github.com/acts-project/acts/pull/4447

refactor: Generalize sorting requirement for `BroadTripletSeedFinder`

---

CI/dependencies/select_lockfile.py

The retry logic currently only works for HTTPError. I'm observing URLError in CI now, so I'm including this exception in the retry logic as well now.

chore: Lockfile selection script also retries on URLError

---

.github/workflows/builds.yml

Since recent container upgrade we are seeing build failures. This allows to bypass the erroneous process until we figure out a proper fix.
cc @paulgessinger

ci: hotfix for eic-shell failures

---

Core/include/Acts/EventData/SpacePointContainer2.hpp

I had problems compiling, due to the spaceship operator being called on a span

fix: change implementation of the spaceship operator when using span

---

Core/include/Acts/EventData/TrackStateType.hpp

Add a new `TrackStateFlag` value, namely `SplitHitFlag`, that allows identifying cases where an underlying measurement is _rightfully_ shared between states from different tracks. This is like `SharedHitFlag` but for situations where it has been determined that the underlying measurement is "shareable", e.g. if it originates from multiple particles.

feat: Add a TrackStateFlag for split hits

---

Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/TensorRTEdgeClassifier.hpp
Plugins/ExaTrkX/src/TensorRTEdgeClassifier.cpp

Use counting semaphore instead, should improve performance, since waiting time can be O(ms). But was never benchmarked.

refactor: Avoid spin lock in TensorRT inference

---

CMakeLists.txt

Empirically, this is the lowest version the code currently supports

build: Set GeoModel minimum version to 6.8.0

---

.github/workflows/milestone.yml
.merge-sentinel.yml

ci: Add synchronize trigger for milestone check

---

Core/include/Acts/Seeding2/detail/CandidatesForMiddleSp2.hpp
Core/src/Seeding2/BroadTripletSeedFilter.cpp
Core/src/Seeding2/detail/CandidatesForMiddleSp2.cpp

```c++
// This is for the case when the weights from different seeds
// are same. This makes cpu & cuda results same
```
Since CUDA implementations are not part of ACTS anymore this can be dropped

chore: Remove stable sorting from `CandidatesForMiddleSp2`

---

Core/include/Acts/Geometry/ContainerBlueprintNode.hpp

Include missing `PortalShell.hpp` in `ContainerBlueprintNode.hpp`
I encountered this issue when including `ContainerBlueprintNode.hpp` from outside the ACTS build. The header defines members of type `std::unique_ptr<PortalShellBase>` but does not include `PortalShell.hpp`, which leads to incomplete type errors.
This can easily be worked around downstream by adding the missing include in the external translation unit, but fixing it upstream ensures the header is self-contained and prevents future build issues.

fix: Include missing PortalShell.hpp header

---

Core/src/Seeding2/BroadTripletSeedFilter.cpp
Core/src/Seeding2/TripletSeedFinder.cpp

- cleanup
- `SortedInCotTheta` vs `SortedByCotTheta`
- `const` consistency
- `2.` vs `2`
- perf
- this version achieves similar (within measurement error of about ~1%) performance as the original ACTS code
- it seems to me that the performance depends on auto vectorization which appears to be very fragile

perf: Cleanup and optimize strip triplet formation in `Seeding2`

---

Plugins/Gnn/CMakeLists.txt

I figured out that at least in the compile flags of the CUDA compilation units there seems to be the `-G` option present, which enables full device debug info. By specifying `-dopt=on` I hope that we only generate limited debug information, according to NVCC documentation.
I did not see a significant change in latencies, but it feels saver to have this flag on.

fix: GNN change CUDA optimization flag
