- Core/include/Acts/Utilities/AnnealingUtility.hpp
- Core/src/Utilities/AnnealingUtility.cpp
Adds missing acts namespace in AnnealingUtility
> Add missing acts namespace in AnnealingUtility

- .codecov.yml
This should allow for small changes that we don't care about.
See #72.
> Add codecov tolerance threshold of 0.1%

- codecov.yml
Not sure what's wrong but the codecov configuration is either not picked up or not correct. Trying a variation of it.
> Attempt to fix codecov configuration

- .github/wip.yml
This should enable the WIP label
> Add config for W I P app

- Core/include/Acts/Surfaces/DiscTrapezoidBounds.hpp
> Fix access stereo variable in DiscTrapezoidBounds

- Core/include/Acts/Propagator/EigenStepper.hpp
- Core/include/Acts/Propagator/StraightLineStepper.hpp
- Core/include/Acts/Surfaces/detail/DiscSurface.ipp
- Core/include/Acts/Surfaces/detail/Surface.ipp
- Core/src/Propagator/detail/CovarianceEngine.cpp
This PR fixes the jacobian from free to curvilinear coordinates as it was missing components as was revealed by #86.
> Fix jacobian from free to curvilinear coordinates

- Examples/Run/Common/include/ACTFW/Options/CommonOptions.hpp
- Examples/Run/Common/src/CommonOptions.cpp
Cherry pick of #116 (see a detailed description there), supersedes the latter.
> Introduce response file technology

- Core/include/Acts/Visualization/EventDataVisualization.hpp
- Core/include/Acts/Visualization/GeometryVisualization.hpp
- Core/include/Acts/Visualization/detail/ObjVisualization.ipp
- Tests/UnitTests/Core/Visualization/CMakeLists.txt
- Tests/UnitTests/Core/Visualization/EventDataVisualizationBase.hpp
- Tests/UnitTests/Core/Visualization/EventDataVisualizationTests.cpp
- Tests/UnitTests/Core/Visualization/PrimitivesVisualizationBase.hpp
- Tests/UnitTests/Core/Visualization/PrimitivesVisualizationTests.cpp
- Tests/UnitTests/Core/Visualization/SurfaceVisualizationBase.hpp
- Tests/UnitTests/Core/Visualization/SurfaceVisualizationTests.cpp
- Tests/UnitTests/Core/Visualization/VisualizationTester.hpp
- Tests/UnitTests/Core/Visualization/VisualizationTests.cpp
- Tests/UnitTests/Core/Visualization/VolumeVisualizationBase.hpp
- Tests/UnitTests/Core/Visualization/VolumeVisualizationTests.cpp
This is the third part of the visualisation update, it adds
- ability to display track parameters and measurements
- primitives such as covariances, vectors, arrows, segments
Needs #91 to be merged first.
> Visualization EventData

- Examples/Framework/CMakeLists.txt
- Examples/Framework/include/ACTFW/Validation/DuplicationPlotTool.hpp
- Examples/Framework/include/ACTFW/Validation/EffPlotTool.hpp
- Examples/Framework/include/ACTFW/Validation/FakeRatePlotTool.hpp
- Examples/Framework/include/ACTFW/Validation/ResPlotTool.hpp
- Examples/Framework/include/ACTFW/Validation/TrackSummaryPlotTool.hpp
- Examples/Framework/src/Validation/DuplicationPlotTool.cpp
- Examples/Framework/src/Validation/EffPlotTool.cpp
- Examples/Framework/src/Validation/FakeRatePlotTool.cpp
- Examples/Framework/src/Validation/ResPlotTool.cpp
This PR includes the changes:
- Fix the inconsistent naming of the plotting tools
- Add the duplication plotting tool
> Add duplication plot tool

- Core/include/Acts/TrackFinder/CombinatorialKalmanFilter.hpp
This PR implements a minor change to CKF:
- When the target surface cannot be reached for a smoothed track (this could happen for a bad quality track), the CKF will return an error.
> Return ERROR for target surface reaching failure in CKF

- Examples/Detectors/DD4hepDetector/CMakeLists.txt
- Examples/Detectors/DD4hepDetector/compact/Calorimeter/Calorimeter_LAR.xml
- Examples/Detectors/DD4hepDetector/compact/materials.xml
- Examples/Detectors/DD4hepDetector/src/Calorimeter/Calorimeter_barrel.cpp
A DD4hep dummy calorimeter for material mapping and propagation test.
Loosely base on the ATLAS LAr, only a barrel was implemented.
> Dummy calorimeter

- Core/include/Acts/Geometry/CylinderVolumeBuilder.hpp
- Core/include/Acts/Geometry/CylinderVolumeHelper.hpp
- Core/include/Acts/Geometry/LayerArrayCreator.hpp
- Core/include/Acts/Geometry/LayerCreator.hpp
- Core/src/Geometry/CylinderVolumeBuilder.cpp
- Core/src/Geometry/CylinderVolumeHelper.cpp
This one replaces #199 - it's just a cherry picked version of the original, but now on top of master.
> Remove smaller/bigger macros cherry pick

- Examples/Algorithms/Geant4/include/ActsExamples/Geant4/GeantinoRecording.hpp
- Examples/Algorithms/Geant4/src/GeantinoRecording.cpp
- Examples/Detectors/DD4hepDetector/include/ACTFW/DD4hepDetector/DD4hepGeometryService.hpp
- Examples/Run/Geant4/RunSimGeantinoRecording.cpp
This fixes several incorrect pointer manipulations in the `ActsSimGeantinoRecording` example.
Fixes #204 .
Fixes #205 .
> ActsSimGeantinoRecording example fixes

- docs/getting_started.md
Small fix in description how to set up the documentation generation.
> Fix in doc installation description

- CMakeLists.txt
- Examples/Framework/CMakeLists.txt
- Examples/Framework/src/Utilities/Paths.cpp
- docs/getting_started.md
> Use std::filesystem instead of boost::filesystem

- Core/include/Acts/Geometry/Extent.hpp
- Core/include/Acts/Geometry/ProtoLayer.hpp
- Core/src/Geometry/LayerCreator.cpp
- Core/src/Geometry/ProtoLayer.cpp
Backport of #246 for `v0.25.01`
> ProtoLayer/Extent changes (backport)

- Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.ipp
See #250, this PR targets master with the correct source branch now.
FYI @paulgessinger
> Change seed vertex break condition in AMVF

- Core/include/Acts/EventData/SingleBoundTrackParameters.hpp
- Core/include/Acts/EventData/SingleCurvilinearTrackParameters.hpp
- Core/include/Acts/Material/HomogeneousVolumeMaterial.hpp
- Core/include/Acts/Surfaces/DiscTrapezoidBounds.hpp
- Core/include/Acts/Utilities/BinAdjustmentVolume.hpp
- Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.ipp
- Core/include/Acts/Vertexing/GaussianGridTrackDensity.ipp
- Core/include/Acts/Vertexing/IterativeVertexFinder.ipp
- Core/include/Acts/Visualization/GeometryView.hpp
- Examples/Detectors/DD4hepDetector/include/ACTFW/DD4hepDetector/DD4hepGeometryService.hpp
This (hopefully) fixes the remaining compiler warnings that show up in #267.
> Fix compiler warnings (final, version N, with sparkles)

- .github/workflows/builds.yml
- .github/workflows/checks.yml
- .github/workflows/coverage.yml
It read `releases/**` when it should have read `release/**`.
> Fix pattern for which branches trigger WF on PR

- .github/workflows/builds.yml
- .github/workflows/checks.yml
- .github/workflows/coverage.yml
Bump the container images to fix the LCG-based builds.
> Bump CI container images to v3

- Core/include/Acts/Fitter/KalmanFitter.hpp
- Core/include/Acts/Propagator/AtlasStepper.hpp
- Core/include/Acts/Propagator/EigenStepper.hpp
- Core/include/Acts/Propagator/EigenStepper.ipp
- Core/include/Acts/Propagator/StepperConcept.hpp
- Core/include/Acts/Propagator/StraightLineStepper.hpp
- Core/include/Acts/TrackFinder/CombinatorialKalmanFilter.hpp
- Core/src/Propagator/StraightLineStepper.cpp
- Tests/UnitTests/Core/Propagator/AtlasStepperTests.cpp
- Tests/UnitTests/Core/Propagator/NavigatorTests.cpp
- Tests/UnitTests/Core/Propagator/StepperTests.cpp
- Tests/UnitTests/Core/Propagator/StraightLineStepperTests.cpp
This PR groups multiple assignments of stepper and navigator state member variables into a function/lambda.
> Reinitialisation methods for state objects

- Core/include/Acts/Seeding/Seedfinder.ipp
@czangela made me aware of a bug in the Seeding, here's the fix.
> fix order by radius expected in sp input

- .github/stale.yml
As discussed in the meeting, the stale bot should also look and handle PRs with this change.
> Remove the restriction to issues

- docs/conf.py
- docs/core/core.rst
- docs/core/seeding.rst
- docs/figures/seeding/3Dcoordinates.svg
- docs/figures/seeding/r-zCoordinates.svg
- docs/figures/seeding/x-yCoordinates.svg
Due to multiple comments regarding the understandability of the track seeding code I added documentation that separates and explains the different calculations in the code.
> Add Track Seeding Documentation

- Examples/Algorithms/Geant4/CMakeLists.txt
- Examples/Algorithms/Geant4/include/ActsExamples/Geant4/Geant4Options.hpp
- Examples/Algorithms/Geant4/include/ActsExamples/Geant4/GeantinoRecording.hpp
- Examples/Algorithms/Geant4/src/Geant4Options.cpp
- Examples/Algorithms/Propagation/include/ACTFW/Propagation/PropagationOptions.hpp
- Examples/Run/Geant4/CMakeLists.txt
- Examples/Run/Geant4/DD4hep/CMakeLists.txt
- Examples/Run/Geant4/DD4hep/DD4hepGeantinoRecording.cpp
- Examples/Run/Geant4/GdmlGeantinoRecording.cpp
- Examples/Run/Geant4/GeantinoRecordingBase.hpp
This PR creates a `GeantinoRecordingBase.h` and then consequently splits off:
* a `DD4hep` example
* a `GDML` example
> Introduce GDML based GeantinoRecording example

- Core/include/Acts/Seeding/Seedfinder.ipp
Pierfrancesco pointed out this comment is wrong
> fix: correct calculation in comment (code unaffected)

- Examples/Scripts/CKF_timing_vs_mu.py
- Examples/Scripts/CKF_timing_vs_mu.sh
- Examples/Scripts/KF_timing.py
- Examples/Scripts/KF_timing.sh
This PR updates the script for the KF timing test. It also adds the scripts for running the CKF timing test.
> perf: Add scripts for CKF timing test

- AUTHORS
This PR updates the author list. I also reordered the names
alphabetically by last names. Let me know if there are any mistakes.
> chore: Update author list

- Examples/Run/Fatras/CMakeLists.txt
- Examples/Run/Fatras/TelescopeFatrasExample.cpp
- Examples/Run/Reconstruction/CMakeLists.txt
- Examples/Run/Reconstruction/TelescopeRecCKFTracks.cpp
- Examples/Run/Reconstruction/TelescopeRecTruthTracks.cpp
This PR adds the executable for simulation and reco with the telescope-like detector.
> feat: Add fatras and reco examples for telescope detector

- Examples/Algorithms/Digitization/include/ActsExamples/Digitization/DigitizationAlgorithm.hpp
- Examples/Algorithms/Digitization/src/DigitizationAlgorithm.cpp
- Examples/Framework/include/ActsExamples/EventData/Cluster.hpp
- Examples/Io/Root/CMakeLists.txt
- Examples/Io/Root/include/ActsExamples/Io/Root/RootMeasurementWriter.hpp
- Examples/Io/Root/src/RootMeasurementWriter.cpp
- Examples/Run/Fatras/Common/FatrasDigitization.cpp
- Fatras/include/ActsFatras/Digitization/Channelizer.hpp
- Fatras/include/ActsFatras/Digitization/UncorrelatedHitSmearer.hpp
This superseds #682 with a clean rebase, the content, however, remains the same.
> feat: update root writer for digitization

- Examples/Run/Digitization/CMakeLists.txt
- Examples/Run/Digitization/TGeoDigitizationExample.cpp
This mini PR adds the `TGeoDigitizationExample` analog to all other examples in the `AcsExamples`.
> feat: adding TGeo digitization example

- Examples/Scripts/MaterialMaping/configureMap.py
- Examples/Scripts/MaterialMaping/writeMapConfig.py
This PR update the mapping script to take into account the change to the key used in the Json conversion. This will solve issue #733
> fix: update mapping script 

- Examples/Algorithms/Geant4DD4hep/src/DD4hepDetectorConstruction.cpp
- Examples/Detectors/DD4hepDetector/src/DD4hepGeometryService.cpp
Fixes #730 . I now consider this to be a clean fix.
> fix: Make ActsSimGeantinoRecordingDD4hep less verbose

- thirdparty/OpenDataDetector/config/odd-material-mapping.config
This overwrites the configuration file in the open data detector.
> feat: adding OpenDataDetector configurations

- thirdparty/OpenDataDetector/config/odd-digi-smearing-config.json
- thirdparty/OpenDataDetector/xml/OpenDataDetector.xml
This PR adds a config file for the digitization (smearing first) and updates the binning of the `ProtoMaterial` at construction.
> feat: adding config files and update binning for ODD

- Examples/Algorithms/Fatras/src/FatrasAlgorithm.cpp
- Examples/Algorithms/GeneratorsPythia8/ActsExamples/Generators/Pythia8ProcessGenerator.cpp
- Examples/Framework/include/ActsExamples/EventData/Index.hpp
- Examples/Io/Csv/src/CsvParticleReader.cpp
Ran into yet more problems similar to #796 , so let's just change all of them.
@baschlag can you review?
Thanks!
L-G
> fix: Examples: change all calls to adopt_sequence to insert

- README.md
> chore: Update readme to add metric tracker badge

- Core/src/Geometry/Layer.cpp
- Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvTrackingGeometryWriter.hpp
- Examples/Io/Csv/src/CsvOutputData.hpp
- Examples/Io/Csv/src/CsvTrackingGeometryWriter.cpp
This PR adds a new output file for Geometry in the CSV writing:
* layer/volume objects are written to CSV
> feat:  csv volume layer writer

- CI/release.py
- CI/release_requirements.txt
This is the release script I've been using for about half a year. This doesn't run automatically at all, and right now I don't think it's very important as I can just run it manually. This PR is to add this version to the main branch, so I have to do less switching around when making a release.
> chore: Update release script

- Examples/Framework/CMakeLists.txt
- Examples/Framework/include/ActsExamples/Framework/Sequencer.hpp
- Examples/Framework/src/Framework/Sequencer.cpp
> fix: Make examples sequencer compatible with modern TBB

- Tests/Benchmarks/SolenoidFieldBenchmark.cpp
The solenoid B field benchmark goes out of bounds when subsequent positions along a straight line are tested. This fixes this by precomputing the positions only until they leave the interpolation volume, and running on these inputs.
This also revealed a bug that since the benchmark tools run the benchmark a number of times (500 here, I believe), but the starting position was not reset, the steps continued further and further outward. This should be fixed now as well.
The timing results do not seem to change substantially.
Closes #847
> fix: Solenoid B field benchmark goes out of bounds

- Core/include/Acts/Geometry/CylinderVolumeBuilder.hpp
but has been annoying me greatly.
> fix: Typo that I have been looking at for 4 years but never fixed

- Examples/Io/Csv/src/CsvTrackingGeometryWriter.cpp
This PR includes a fix to the CsvTrackingGeometry writer that did omit passive layer volumes.
> fix: let CsvVolumeLayer writer also write passive surfaces

- Examples/Io/Root/include/ActsExamples/Io/Root/RootPropagationStepsWriter.hpp
- Examples/Io/Root/src/RootPropagationStepsWriter.cpp
This PR adds a single additional value to the `RootPropagationStepWriter` which helps checking the material loading onto a geometry.
> feat: flag material if found

- Examples/Algorithms/Geant4HepMC/src/EventAction.cpp
Should fix https://github.com/acts-project/acts/issues/877
Edit: In combination with #910 it will produce a readable output in the tests described in #877.
> fix: HepMC3 G4 event action correctly builds even record

- .zenodo.json
- CITATION.cff
This is used to create a zenodo entry for releases.
> chore: Add zenodo info file

- Examples/Io/NuclearInteractions/src/detail/NuclearInteractionParametrisation.cpp
Prevent out of bounds access. Should fix #914
> fix: SEGFAULT in NuclearInteractionParametrisation

- CMakeLists.txt
Update CMakeLists.txt to solve  #886.
> build: Let CMake use FindBoost.cmake first

- Examples/Algorithms/Digitization/share/default-smearing-config-telescope.json
This PR adds the smearing config file for the telescope detector.
> perf: Add tele digi file

- Core/include/Acts/Visualization/GeometryView3D.hpp
- Core/src/Visualization/GeometryView3D.cpp
- Examples/Io/Obj/include/ActsExamples/Plugins/Obj/ObjTrackingGeometryWriter.hpp
- Examples/Io/Obj/src/ObjTrackingGeometryWriter.cpp
Previously, they would always write to `$PWD` which is not desirable.
> feat: GeometryView3D can write to specified outputDir

- .github/workflows/builds.yml
> ci: Remove 3 cvmfs based CI builds

- .kodiak.toml
This bot reacts to a special label `automerge` on PRs and will
1. Keep the PR up-to-date
2. Wait for all required statuses to succeed (including approval)
3. Squash and merge into `main` once that's done
This should allow us to wait less on the manual update-wait-merge cycle.
> ci: Add kodiak bot configuration

- CI/release.py
This makes GitHub automatically assemble a contributor list at the
bottom of the release.
> ci: Make the release script add author handles to changelog items

- Core/include/Acts/Seeding/SpacePointGrid.ipp
Fixes the issue: https://github.com/acts-project/acts/issues/1111
> fix: ensure there is at least one zBin

- Examples/Scripts/Python/itk.py
Improving the description of the ITk geometry parameters in the python file.
This fixes as well the issue #1149, caused by the wrong configuration of the HGTD extends.
Fixes #1149
> fix: Updating itk description in python, fixes issue #1149

- Core/src/Propagator/detail/CovarianceEngine.cpp
This commit optimizes some of the Eigen usage in the covariance engine, specifically in the critical path for the propagation examples. The first optimisation we make is to introduce a tiled matrix multiplication method, which takes 2i×2j matrices, and performs four i×j multiplications instead, which Eigen can optimize far more easily. Secondly, we reduce the number of floating point operations performed by working with smaller submatrices wherever possible.
On my machine, the following performance is achieved in the propagation example before this patch: 53.555595 ms/event. After this patch, we take 43.750143 ms/event. This performance gain is independent from the performance gain of #1181.
> perf: Optimize Eigen usage in covariance engine

- .github/workflows/builds.yml
In #1182 I unfortunately set the wrong CMake option to turn the forces
assertions on.
This PR should fix this.
> ci: Turn on FORCE_ASSERTIONS

- Examples/Detectors/TelescopeDetector/include/ActsExamples/TelescopeDetector/TelescopeDetector.hpp
- Examples/Detectors/TelescopeDetector/src/TelescopeDetector.cpp
- Examples/Python/CMakeLists.txt
- Examples/Python/src/Detector.cpp
- Examples/Scripts/Python/truth_tracking_telescope.py
closes #1225.
I also included a small example script, which uses the `runTruthTracking()` from `truth_tracking.py`.
> feat: Python bindings for Telescope Detector

- .merge-sentinel.yml
> ci: Fix sentinel yml

- CITATION.cff
> docs: correct affiliation in CITATION.cff

- docs/core/propagation.md
minor corrections to the doc we added yesterday
> docs: minor corrections

- docs/core/propagation.md
I was too late, to comment on some things in [PR #1405](https://github.com/acts-project/acts/pull/1405/), therefore a new PR.
> docs: minor corrections. followup to PR #1405

- .github/workflows/analysis.yml
- .github/workflows/builds.yml
- .github/workflows/checks.yml
- .github/workflows/docs.yml
This is needed for backporting.
> ci: Backport a number of CI / docs config updates

- Core/include/Acts/Propagator/Propagator.ipp
- Core/include/Acts/Propagator/detail/LoopProtection.hpp
- Tests/UnitTests/Core/Propagator/LoopProtectionTests.cpp
Backport 1fd479b487e121ea78bea0fa073386edd139667c from #1490.
---
> refactor: loop protection as a function [backport #1490 to develop/v19.x]

- Core/include/Acts/Utilities/Logger.hpp
- Core/src/Utilities/Logger.cpp
- docs/core/logging.md
This mainly adds information on the logging thresholds configuration.
> docs: Update logging doc, add info on thresholds

- Examples/Scripts/Python/full_chain_itk.py
- Examples/Scripts/Python/full_chain_odd.py
- align odd full chain with itk full chain
see #1513
> refactor: improve full_chain_odd.py example

- Examples/Scripts/Python/full_chain_itk.py
- Examples/Scripts/Python/full_chain_odd.py
Backport e5d19700e5daa9d60922a2402fe61308eefb7639 from #1538 
---
- align odd full chain with itk full chain
see #1513
> refactor: improve full_chain_odd.py example [backport #1538 to develop/v19.x]

- Examples/Io/Performance/ActsExamples/Io/Performance/CKFPerformanceWriter.cpp
- Examples/Io/Performance/ActsExamples/Io/Performance/CKFPerformanceWriter.hpp
- Examples/Scripts/Optimization/Optuna_tuning.py
- Examples/Scripts/Optimization/Orion_tuning.py
- Examples/Scripts/Optimization/ckf.py
- docs/howto/run_ckf_auto_tuning.rst
Backport 8fbf7de9e82022c6fd1415427ca98a7c952e9c1d from #1541
---
The Optuna and Orion optimization algorithms are used to auto-tune some parameters of seeding algorithm and performance has been checked on the CKF algorithm.
Also includes #1560
> feat: Added Optimization Scripts [backport of #1541 to develop/v19.x]

- Examples/Io/Root/include/ActsExamples/Io/Root/RootVertexPerformanceWriter.hpp
- Examples/Io/Root/src/RootVertexPerformanceWriter.cpp
- Examples/Python/python/acts/examples/reconstruction.py
Backport 9b793b2da22036a992d015a4f755162ca9d7383f from #1567.
---
- deduplicate code
- improve doc
- make track selector optional
> refactor: simplify RootVertexPerformanceWriter [backport #1567 to develop/v19.x]

- .github/workflows/builds.yml
- .github/workflows/report.yml
- CI/physmon/comment_template.md
This attempts to add a workflow that comments details of the physmon result on the relevant PR.
> ci: Add reporting to physmon

- Examples/Algorithms/Geant4/include/ActsExamples/Geant4/SensitiveSurfaceMapper.hpp
- Examples/Algorithms/Geant4/src/Geant4Simulation.cpp
- Examples/Algorithms/Geant4/src/SensitiveSurfaceMapper.cpp
until now the geant4 surface mapper only supports translations. this PR adds rotation support as needed in https://github.com/acts-project/acts/pull/1638/
> feat: handle geant4 rotations

- Examples/Io/Root/src/RootMaterialTrackWriter.cpp
- Examples/Io/Root/src/RootParticleWriter.cpp
- Examples/Io/Root/src/RootPlanarClusterWriter.cpp
- Examples/Io/Root/src/RootPropagationStepsWriter.cpp
- Examples/Io/Root/src/RootSimHitWriter.cpp
- Examples/Io/Root/src/RootSpacepointWriter.cpp
- Examples/Io/Root/src/RootTrackParameterWriter.cpp
- Examples/Io/Root/src/RootTrajectoryStatesWriter.cpp
- Examples/Io/Root/src/RootTrajectorySummaryWriter.cpp
- Examples/Io/Root/src/RootVertexPerformanceWriter.cpp
align the closing mechanism of the root writers
some writer did not close the file which will result in empty files before the destructor is called
> fix: and refactor root writer closing

- Core/include/Acts/Utilities/RangeXD.hpp
- Tests/UnitTests/Core/Propagator/AuctioneerTests.cpp
> fix: missing includes

- AUTHORS
After seeing #1781 I would also like to add myself to the authors list. Unfortunately I was a few seconds to late to hop on #1781 :D
> docs: update AUTHORS file

- Plugins/Geant4/include/Acts/Plugins/Geant4/Geant4Converters.hpp
- Plugins/Geant4/src/Geant4Converters.cpp
- Tests/UnitTests/Plugins/Geant4/Geant4ConvertersTests.cpp
This PR is a prerequisite for the the MS mockup station, it allows to do straw tube creation from Geant4.
> feat: Geant4 line/straw tube conversion capability

- Examples/Algorithms/Geant4/src/SensitiveSurfaceMapper.cpp
this way the user can (hopefully) understand why surfaces are not mapped correctly
> refactor: improve g4 sensitive surface mapper logging

- docs/conf.py
This sneaked in with https://github.com/acts-project/acts/pull/1845
> fix: format docs/conf.py

- Core/include/Acts/Geometry/Extent.hpp
- Core/include/Acts/Geometry/KDTreeTrackingGeometryBuilder.hpp
- Core/include/Acts/Geometry/TrackingGeometryBuilder.hpp
- Core/src/Geometry/TrackingGeometryBuilder.cpp
- Examples/Detectors/Geant4Detector/include/ActsExamples/Geant4Detector/Geant4Detector.hpp
- Examples/Detectors/Geant4Detector/src/Geant4Detector.cpp
- Examples/Python/python/acts/examples/simulation.py
- Examples/Python/src/Geant4Component.cpp
- G4 detector was not able to handle geoid hooks
- sneaked in some cleanups - we can break this out if necessary
> feat: wire geoid hooks in g4 detector

- Examples/Scripts/Python/full_chain_odd.py
> fix: Add rho-cut to the ParticleSelector for g4 ODD

- Examples/Scripts/Python/full_chain_itk.py
> fix: Apply particle filter change to full_chain_itk.py

- Core/include/Acts/EventData/VectorTrackContainer.hpp
- Examples/Algorithms/TrackFinding/src/AmbiguityResolutionAlgorithm.cpp
- Examples/Algorithms/TrackFinding/src/TrackFindingAlgorithm.cpp
- Examples/Algorithms/TrackFitting/src/TrackFittingAlgorithm.cpp
- Examples/Algorithms/TrackFittingChi2/src/TrackFittingChi2Algorithm.cpp
- Examples/Algorithms/Utilities/src/TracksToTrajectories.cpp
- Examples/Framework/include/ActsExamples/EventData/Track.hpp
- Examples/Framework/include/ActsExamples/EventData/Trajectories.hpp
Also includes a fix of a missing method in the ConstVectorTrackContainer class.
> refactor: Improved const-correctness for TrackContainer in Examples

- Core/include/Acts/TrackFitting/detail/KalmanUpdateHelpers.hpp
- Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSmearing.cpp
- Examples/Detectors/GenericDetector/include/ActsExamples/GenericDetector/GenericDetectorElement.hpp
- Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoDetectorElement.hpp
improves some minor doc and printouts
> chore: improve some doc and prints

- thirdparty/actsvg/CMakeLists.txt
This is the new ACTSVG version for facilitating the debugging of multi-wire chamber setups, such as the ATLAS MDT cambers.
An example display for such as setup is attached, and can with this version be implemented within ACTS:
> chore: new ACTSVG version for MS chambers

- Core/include/Acts/Material/MaterialCollector.hpp
- Core/include/Acts/Propagator/DirectNavigator.hpp
- Core/include/Acts/Propagator/MaterialInteractor.hpp
- Core/include/Acts/Propagator/SurfaceCollector.hpp
- Core/include/Acts/Propagator/VolumeCollector.hpp
- Core/include/Acts/Propagator/detail/SteppingLogger.hpp
- Fatras/include/ActsFatras/Kernel/detail/SimulationActor.hpp
- Tests/UnitTests/Core/Propagator/KalmanExtrapolatorTests.cpp
- Tests/UnitTests/Core/Propagator/PropagatorTests.cpp
"observer" functions are not called if there is a proper actor function
> refactor: remove dead actor code

- Core/include/Acts/Propagator/AbortList.hpp
- Core/include/Acts/Propagator/ActionList.hpp
- Core/include/Acts/Propagator/Propagator.ipp
- Core/include/Acts/Propagator/detail/abort_list_implementation.hpp
- Core/include/Acts/Propagator/detail/action_list_implementation.hpp
- Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp
- align param order
- improve naming
> refactor: align actor/aborter param order

- Examples/Python/python/acts/examples/itk.py
Recently I changed deltaZMax in ITk configuration, but I should have changed only for PPP and not for SSS as well.
@CarloVarni I believe this is the reason for the higher number of SSS seeds that we were seeing. Sorry for that
> fix: bug in ITk config

- Core/include/Acts/Seeding/SeedFinderUtils.ipp
This PR reduces duplicated calculations in `xyzCoordinateCheck` function.
> refactor: SSS xyzCoordinateCheck calculations

- .gitlab-ci.yml
Also renames the exatrkx jobs to include the name explicitly.
> ci: Fix ccache usage in GitLab CI job

- Core/include/Acts/EventData/TrackStatePropMask.hpp
- Examples/Algorithms/TrackFitting/src/RefittingCalibrator.cpp
> fix: Add missing include and fix warning for GCC 13

- .github/workflows/builds.yml
Backport 24101373581399a0af828833024a3912e983ac68 from #2080.
---
> ci: Fix git lfs installation [backport #2080 to develop/v25.x]

- CI/physmon/comment_template.md
fixes bug that sneaked in with #2130
> fix: Fix physmon comment template after #2130

- .github/workflows/builds.yml
Remove .o files from build directory tarball
> ci: Don't package .o files

- docs/conf.py
Ignore `eigen.tuxfamily.org` which is down atm
> docs: Ignore if `eigen.tuxfamily.org` is online

- CMakeLists.txt
minor formatting change in our central `CMakeLists.txt`
> chore: Improve CMake formatting

- .github/workflows/analysis.yml
- .github/workflows/builds.yml
- .gitlab-ci.yml
This only runs on the main branch, so is hard to test. I hope this works now.
> ci: Physmon memory monitoring push fix

- Examples/Python/python/acts/examples/__init__.py
> fix: Remove erroneously added print

- docs/conf.py
> fix: Quick fix docs by ignoring pythia.org

- Core/include/Acts/Seeding/SeedFinder.ipp
While looping over the doublets, we find the first SP inside the radius region of interest and update the iterator so we don't need to look at the other SPs again. That mean that we have changed the middle space point (which are sorted in radius) and the radius lower bound has moved accordingly.
However, if that is the last bottom or top spaceport in that grid bin, we continue and we don't move the lower bound. This means that we will continue looking at some spacepoints unnecessarily.
This PR is intended to fix that and update the lower bound also for these cases.
@CarloVarni @noemina let me know if you have a better suggestion on how to fix this
I tested this and improves slightly ~4% performance for ttbar 200 pileUp
> fix: small bug when avoiding iterations while looking for dublets

- Examples/Python/python/acts/_adapter.py
> feat: Really make patched python constructors accept pathlib Paths

- Core/include/Acts/EventData/GenericBoundTrackParameters.hpp
- Core/include/Acts/EventData/GenericCurvilinearTrackParameters.hpp
- Core/include/Acts/EventData/GenericFreeTrackParameters.hpp
Pulled out of https://github.com/acts-project/acts/pull/2341
> feat: Angle accessors for track params and easy position for curvilinear

- Examples/Python/python/acts/__init__.py
- Examples/Scripts/Python/material_recording.py
This PR adds arguments parser to the `material_recording` and allows thus to run from GDML file as well.
> feat: allow gdml for material recording

- Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSmearing.cpp
> fix: Add check if RNG provided instead of nullptr dereference

- Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/TrackFindingAlgorithm.hpp
- Examples/Algorithms/TrackFinding/src/TrackFindingAlgorithm.cpp
- Examples/Python/python/acts/examples/reconstruction.py
- Examples/Python/src/TrackFinding.cpp
Moved a hardcoded parameter to the config and wired backward flag
Pulled this out of https://github.com/acts-project/acts/pull/2518
> feat: Add maximum propagation steps to CKF Examples algorithm

- Tests/UnitTests/Core/TrackFitting/Gx2fTests.cpp
While debugging https://github.com/acts-project/acts/pull/2534 I encountered a few problems with the GX2F test which I try to fix here.
- make volume big enough to fit all the surfaces
- introduce envelope
- remove volume material
- lower case variable name
> test: Refactor GX2F test

- Examples/Algorithms/TrackFindingExaTrkX/include/ActsExamples/TrackFindingExaTrkX/TrackFindingAlgorithmExaTrkX.hpp
- Examples/Algorithms/TrackFindingExaTrkX/src/TrackFindingAlgorithmExaTrkX.cpp
- Examples/Python/src/ExaTrkXTrackFinding.cpp
- Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/BoostTrackBuilding.hpp
- Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/CugraphTrackBuilding.hpp
- Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/ExaTrkXPipeline.hpp
- Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/OnnxEdgeClassifier.hpp
- Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/OnnxMetricLearning.hpp
- Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/Stages.hpp
- Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/TorchEdgeClassifier.hpp
- Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/TorchMetricLearning.hpp
- Plugins/ExaTrkX/src/BoostTrackBuilding.cpp
- Plugins/ExaTrkX/src/CugraphTrackBuilding.cpp
- Plugins/ExaTrkX/src/ExaTrkXPipeline.cpp
- Plugins/ExaTrkX/src/OnnxEdgeClassifier.cpp
- Plugins/ExaTrkX/src/OnnxMetricLearning.cpp
- Plugins/ExaTrkX/src/TorchEdgeClassifier.cpp
- Plugins/ExaTrkX/src/TorchMetricLearning.cpp
- Plugins/ExaTrkX/src/buildEdges.cpp
Some new small features for Exa.TrkX plugin and algorithm
* Allow to measure timing
* add a device hint to select GPU device
* Add mutex to run save in MT environments
> feat: Add timing, device hint and mutex to ExaTrkX plugin

- Core/include/Acts/Propagator/ConstrainedStep.hpp
Fixes an oversight in https://github.com/acts-project/acts/pull/2532
> perf: Improve `ConstrainedStep` footprint after #2532

- Examples/Algorithms/TrackFindingExaTrkX/include/ActsExamples/TrackFindingExaTrkX/PrototracksToParameters.hpp
- Examples/Algorithms/TrackFindingExaTrkX/src/PrototracksToParameters.cpp
- Examples/Python/src/ExaTrkXTrackFinding.cpp
> fix: fix bugs and improve docs for prototracks-to-parameters algorithm

- Examples/Io/Json/src/JsonDigitizationConfig.cpp
@asalzburger I think this was a small copy paste error in https://github.com/acts-project/acts/pull/663 otherwise the branch would be unreachable.
> fix: `Digitization::Digital` in `to_json()` was skipped

- .merge-sentinel.yml
This breaks the review, so will merge this manually.
> ci: Change name of required policy bot approval

- Core/include/Acts/Vertexing/FullBilloirVertexFitter.hpp
- Core/include/Acts/Vertexing/ImpactPointEstimator.hpp
- Examples/Python/python/acts/__init__.py
- Plugins/DD4hep/include/Acts/Plugins/DD4hep/DD4hepBinningHelpers.hpp
This PR fixes the doc build, 2 PRs sneaked parameters in.
> fix: undocumented parameters

- .zenodo.json
There are lots of "burgs" in Germany...
> fix: zenodo wrong affiliation

- Examples/Algorithms/TrackFindingExaTrkX/include/ActsExamples/TrackFindingExaTrkX/TrackFindingAlgorithmExaTrkX.hpp
- Examples/Algorithms/TrackFindingExaTrkX/src/TrackFindingAlgorithmExaTrkX.cpp
- Examples/Io/Csv/CMakeLists.txt
- Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvExaTrkXGraphWriter.hpp
- Examples/Io/Csv/src/CsvExaTrkXGraphWriter.cpp
- Examples/Python/src/ExaTrkXTrackFinding.cpp
- Examples/Python/src/Output.cpp
- Plugins/ExaTrkX/CMakeLists.txt
- Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/ExaTrkXPipeline.hpp
- Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/TorchGraphStoreHook.hpp
- Plugins/ExaTrkX/src/ExaTrkXPipeline.cpp
- Plugins/ExaTrkX/src/TorchGraphStoreHook.cpp
- Plugins/ExaTrkX/src/TorchTruthGraphMetricsHook.cpp
- Tests/UnitTests/Plugins/ExaTrkX/ExaTrkXMetricHookTests.cpp
Allows to export the Graph after the GNN to a csv file. Needed for the GNN+CKF workflow
> feat: Graph export for Exa.TrkX

- Plugins/ExaTrkX/src/TorchEdgeClassifier.cpp
For the case of 0 chunks. The value of the chunk option is actually questionable, but this should be addressed at a different point.
> perf: Improve edge classifier performance

- Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp
> revert: Give CKF BranchStopper access to TrackState

- .github/workflows/iwyu.yml
- CI/iwyu/README.md
- CI/iwyu/filter.yaml
adding some documentation and fix the params
> fix: Document and fix IWYU

- .github/workflows/iwyu.yml
#2765 was not sufficient looking at https://github.com/acts-project/acts/actions/runs/7102359442/job/19332529370
we really need an absolute path https://github.com/acts-project/acts/actions/runs/7103710691/job/19337031841
> fix: Fix IWYU mapping file

- CMakeLists.txt
- Examples/Python/src/Svg.cpp
- Examples/Scripts/Python/detector_creation.py
- Plugins/ActSVG/src/PortalSvgConverter.cpp
- Plugins/ActSVG/src/SurfaceSvgConverter.cpp
Thi mini-PR:
- increases to ACTSVG version `v0.4.40`
- adds selections for drawings 
- avoids double-drawing of portals
> feat: adding drawing selections and decorations

- .policy.yml
tries to fix a problem with #2914
> fix: unknown escape character in policy

- Core/src/TrackFitting/GlobalChiSquareFitterError.cpp
I forgot to add the error message in PR #2981.
> fix(gx2f): add error message to `NotEnoughMeasurements`

- Examples/Python/tests/test_examples.py
- Examples/Scripts/Python/full_chain_odd.py
Makes the chain more configurable and changes the default pile-up for ttbar to 200.
> refactor: Make pile-up configurable for `full_chain_odd.py` and change default to 200

- Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp
On its own, this counter does nothing, but we will need it later for holes, outliers, and material.
> feat(gx2f): add counter `processedStates`

- Core/include/Acts/EventData/detail/MultiTrajectoryTestsCommon.hpp
- Tests/UnitTests/Benchmarks/BenchmarkTools.cpp
- Tests/UnitTests/Core/Propagator/BoundToCurvilinearConversionTests.cpp
- Tests/UnitTests/Core/Utilities/AlgebraHelpersTests.cpp
removes those missed in:
- https://github.com/acts-project/acts/pull/3229
> test: remove missed unused boost includes 

- .github/workflows/checks.yml
- .pre-commit-config.yaml
- CI/physmon/workflows/physmon_ckf_tracking.py
- Examples/Python/python/acts/examples/__init__.py
- Examples/Scripts/Optimization/ckf.py
- Examples/Scripts/Python/Auto-tuning/Orion/material_mapping_optimisation.py
- Examples/Scripts/Python/MLAmbiguityResolution/match_good_track-seed.py
- Examples/Scripts/Python/ckf_tracks.py
- Examples/Scripts/Python/full_chain_itk.py
- Examples/Scripts/Python/full_chain_itk_Gbts.py
- Examples/Scripts/Python/material_mapping.py
There were some changes in the if-else-handling.
Also changes the pre-commit mirror to a mypyc which should be 2x faster
> ci: update black-version and pre-commit mirror

- Core/include/Acts/EventData/ChargeConcept.hpp
- Examples/Io/Root/src/RootMaterialWriter.cpp
- Identity comparison in concept
- Possible dereference of nullpt in RootMaterialWriter
> chore: Fix two issues raised by sonar

- Core/include/Acts/Seeding/SeedFinderGbts.ipp
Division was causing FPE in GBTS test in Athena (in MR)
> fix: fixing division that was causing FPE

- Examples/Python/src/Base.cpp
- cmake/ActsExternSources.cmake
> chore: Bump pybind11 to v2.13.1

- Core/include/Acts/Propagator/DirectNavigator.hpp
This can cause an out-of-bounds-exception.
> fix: Comparison error in DirectNavigator

- CMakeLists.txt
Bump minimum Eigen version to v3.4.0
> build: Bump minimum Eigen version to v3.4.0

- Examples/Scripts/MaterialMapping/GeometryVisualisationAndMaterialHandling.py
- Examples/Scripts/MaterialMapping/material_comparison.py
- Examples/Scripts/Python/material_mapping_core.py
- Examples/Scripts/Python/material_validation_core.py
This mainly allows using these scripts when not all plugins are built. Some additional refactoring and improvement of error messages.
> refactor: Conditional import & refactor in python scripts related to material mapping

- CMakeLists.txt
Error by default was a bit aggressive.
> build: Downgrade boost version error to warning

- Core/include/Acts/Geometry/Polyhedron.hpp
- Core/include/Acts/Geometry/Volume.hpp
- Core/include/Acts/Surfaces/Surface.hpp
- Core/include/Acts/Utilities/BoundingBox.hpp
- Core/include/Acts/Utilities/BoundingBox.ipp
- Core/include/Acts/Visualization/IVisualization3D.hpp
- Core/include/Acts/Visualization/ObjVisualization3D.hpp
- Core/include/Acts/Visualization/PlyVisualization3D.hpp
- Core/include/Acts/Visualization/ViewConfig.hpp
- Core/include/Acts/Visualization/detail/ObjVisualization3D.ipp
- Core/include/Acts/Visualization/detail/PlyVisualization3D.ipp
- Core/src/Geometry/Polyhedron.cpp
- Core/src/Geometry/Volume.cpp
- Core/src/Surfaces/Surface.cpp
- Core/src/Visualization/GeometryView3D.cpp
- Examples/Algorithms/Geant4/src/SensitiveSurfaceMapper.cpp
- Examples/Io/Csv/src/CsvSeedWriter.cpp
- Examples/Io/Json/src/JsonSurfacesWriter.cpp
- Examples/Python/src/Obj.cpp
- Examples/Python/src/Output.cpp
- Tests/UnitTests/Core/Geometry/LayerCreatorTests.cpp
- Tests/UnitTests/Core/Geometry/ProtoLayerHelperTests.cpp
- Tests/UnitTests/Core/Utilities/BoundingBoxTest.cpp
- Tests/UnitTests/Core/Visualization/Visualization3DTests.cpp
- Tests/UnitTests/Plugins/Geant4/Geant4DetectorSurfaceFactoryTests.cpp
This PR 
- Moves some of the visualization logic from helper functions into member functions (`Surface`, `Volume`, Polyhedron`)
- Updates the `Color` struct used in `ViewConfig` to be more versatile.
> refactor: Visualization3D location and API

- Core/include/Acts/Seeding/SeedFinder.hpp
- Core/include/Acts/Seeding/SeedFinder.ipp
- Core/include/Acts/Seeding/detail/CylindricalSpacePointGrid.hpp
- Core/include/Acts/Seeding/detail/CylindricalSpacePointGrid.ipp
- Core/include/Acts/Seeding/detail/UtilityFunctions.hpp
- Examples/Algorithms/TrackFinding/src/SeedingAlgorithm.cpp
Add some concept in order to request specific requirements on objects/functions used by the seeding
> refactor: Add some requirements

- .github/workflows/builds.yml
Not sure why, but the URL does not work directly with a variable.
related to:
- https://github.com/acts-project/acts/pull/3782
> ci: dependency URL not set correctly

- Core/include/Acts/Seeding/SeedFilter.hpp
- Core/include/Acts/Seeding/SeedFilter.ipp
- Core/include/Acts/Seeding/SeedFinder.hpp
- Core/include/Acts/Seeding/SeedFinder.ipp
- Core/include/Acts/Seeding/detail/CylindricalSpacePointGrid.hpp
- Core/include/Acts/Seeding/detail/CylindricalSpacePointGrid.ipp
- Examples/Algorithms/TrackFinding/src/SeedingAlgorithm.cpp
- Tests/UnitTests/Core/Seeding/SeedFinderTest.cpp
Adding some `VERBOSE` statements in the  seeding, from Grid creation and Filling to seed finder and filter.
> refactor: Improve log in seeding 

- cmake/ActsCodegen.cmake
> fix: Codegen uv aarch64 install

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/setup.sh
- .gitignore
- CI/check_unused_files.py
> chore: Add devcontainer configuration

- Examples/Algorithms/Geant4/src/SensitiveSurfaceMapper.cpp
> fix: Do not make a copy in SensitiveSurfaceMapper

- Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/MuonHoughSeeder.hpp
- Examples/Algorithms/TrackFinding/src/MuonHoughSeeder.cpp
- Examples/Framework/include/ActsExamples/EventData/MuonHoughMaximum.hpp
- Examples/Framework/include/ActsExamples/EventData/MuonSegment.hpp
- Examples/Framework/include/ActsExamples/EventData/MuonSpacePoint.hpp
- Examples/Io/Csv/src/CsvOutputData.hpp
- Examples/Python/src/TrackFinding.cpp
- Update the format of the doxygen comments from /** @brief --> /// @brief
- Make the number of bins in the hough plane configurable
Tagging @andiwand, @paulgessinger
> chore: Update doxygen documentation format

- Core/include/Acts/Seeding2/DoubletSeedFinder.hpp
- Core/src/Seeding2/DoubletSeedFinder.cpp
- Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/GridTripletSeedingAlgorithm.hpp
- Examples/Algorithms/TrackFinding/src/GridTripletSeedingAlgorithm.cpp
Ports https://github.com/acts-project/acts/pull/4463 to `Seeding2`
@noemina
> feat: Extend experiment cuts for doublet formation in `Seeding2`

- .github/workflows/release.yml
- CI/cliff.toml
- CI/release.sh
- Update git cliff version
- Avoid using deprecated variable in template
- Add upload of tarball as an explicit asset to the release
> ci: Update release workflow

- Core/include/Acts/Seeding/detail/CompSpacePointAuxiliaries.hpp
- Core/include/Acts/Seeding/detail/CompSpacePointAuxiliaries.ipp
- Tests/UnitTests/Core/Seeding/StrawLineResidualTest.cpp
- Add helper functions to calculate the chi square of a space point w.r.t. a line without instantiating a CompSpacePointAuxiliaries object
> feat: CompSpacePointAuxiliaries - Add functions to calculate chi2 directly

- Examples/Algorithms/TrackFinding/src/SeedingOrthogonalAlgorithm.cpp
> fix: Decrease debug output level to DEBUG for event frequency

- Core/include/Acts/Seeding/detail/CompSpacePointAuxiliaries.hpp
- Core/include/Acts/Seeding/detail/CompSpacePointAuxiliaries.ipp
- Core/include/Acts/Seeding/detail/FastStrawLineFitter.hpp
- Core/include/Acts/Seeding/detail/FastStrawLineFitter.ipp
- Core/src/Seeding/CMakeLists.txt
- Core/src/Seeding/FastStrawLineFitter.cpp
- Tests/UnitTests/Core/Seeding/CMakeLists.txt
- Tests/UnitTests/Core/Seeding/FastStrawLineFitTests.cpp
- Introduce new fitter class to fit a straight 2D line to a set of straw measurement.
Closure test without smearing:
997536 / 1000000 passed selection below
number of iterations against the inclanation angle
Closure test with smearing:
mean chi2 against the inclanation angle
Tagging: @AJPfleger, @andiwand, @paulgessinger, @dimitra97, @goblirsc
> feat: Fast line fitter for straws

- .github/workflows/sonarcloud.yml
> ci: Another attempt to get sonar working again

- Tests/UnitTests/Plugins/DD4hep/CMakeLists.txt
- Tests/UnitTests/Plugins/DD4hep/DD4hepCylindricalDetectorGen3Tests.cpp
> test: New unit test for building Gen3 geometry of a cylindrical detector from DD4Hep

- Core/include/Acts/Definitions/Algebra.hpp
- Core/include/Acts/Definitions/Alignment.hpp
- Core/include/Acts/Definitions/Common.hpp
- Core/include/Acts/Definitions/Direction.hpp
- Core/include/Acts/Definitions/ParticleData.hpp
- Core/include/Acts/Definitions/TrackParametrization.hpp
- Core/include/Acts/Definitions/Units.hpp
> docs: Fix doxygen warnings in Definitions

- Core/include/Acts/Navigation/DetectorNavigator.hpp
- Core/include/Acts/Navigation/InternalNavigation.hpp
- Core/include/Acts/Navigation/MultiLayerNavigation.hpp
- Core/include/Acts/Navigation/MultiLayerNavigationPolicy.hpp
- Core/include/Acts/Navigation/NavigationDelegate.hpp
- Core/include/Acts/Navigation/NavigationState.hpp
- Core/include/Acts/Navigation/NavigationStateUpdaters.hpp
- Core/include/Acts/Navigation/NavigationStream.hpp
- Core/include/Acts/Navigation/PortalNavigation.hpp
> docs: Fix doxygen warnings in Navigation

- Core/include/Acts/MagneticField/ConstantBField.hpp
- Core/include/Acts/MagneticField/InterpolatedBFieldMap.hpp
- Core/include/Acts/MagneticField/MagneticFieldError.hpp
- Core/include/Acts/MagneticField/MultiRangeBField.hpp
- Core/include/Acts/MagneticField/SolenoidBField.hpp
> docs: Fix doxygen warnings in magnetic field

- Core/include/Acts/Material/AccumulatedSurfaceMaterial.hpp
- Core/include/Acts/Material/AccumulatedVolumeMaterial.hpp
- Core/include/Acts/Material/BinnedSurfaceMaterial.hpp
- Core/include/Acts/Material/BinnedSurfaceMaterialAccumulater.hpp
- Core/include/Acts/Material/GridSurfaceMaterial.hpp
- Core/include/Acts/Material/HomogeneousSurfaceMaterial.hpp
- Core/include/Acts/Material/HomogeneousVolumeMaterial.hpp
- Core/include/Acts/Material/ISurfaceMaterial.hpp
- Core/include/Acts/Material/IVolumeMaterial.hpp
- Core/include/Acts/Material/Interactions.hpp
- Core/include/Acts/Material/InterpolatedMaterialMap.hpp
- Core/include/Acts/Material/Material.hpp
- Core/include/Acts/Material/MaterialComposition.hpp
- Core/include/Acts/Material/MaterialGridHelper.hpp
- Core/include/Acts/Material/MaterialInteraction.hpp
- Core/include/Acts/Material/MaterialMapUtils.hpp
- Core/include/Acts/Material/MaterialMapper.hpp
- Core/include/Acts/Material/MaterialSlab.hpp
- Core/include/Acts/Material/MaterialValidater.hpp
- Core/include/Acts/Material/PropagatorMaterialAssigner.hpp
- Core/include/Acts/Material/ProtoSurfaceMaterial.hpp
- Core/include/Acts/Material/ProtoVolumeMaterial.hpp
- Core/include/Acts/Material/SurfaceMaterialMapper.hpp
- Core/include/Acts/Material/TrackingGeometryMaterial.hpp
- Core/include/Acts/Material/VolumeMaterialMapper.hpp
- Core/include/Acts/Material/interface/IAssignmentFinder.hpp
- Core/include/Acts/Material/interface/ISurfaceMaterialAccumulater.hpp
> docs: Fix doxygen warnings in Material

- Core/include/Acts/EventData/Charge.hpp
- Core/include/Acts/EventData/GenericBoundTrackParameters.hpp
- Core/include/Acts/EventData/GenericFreeTrackParameters.hpp
- Core/include/Acts/EventData/GenericParticleHypothesis.hpp
- Core/include/Acts/EventData/MeasurementHelpers.hpp
- Core/include/Acts/EventData/MultiComponentTrackParameters.hpp
- Core/include/Acts/EventData/MultiTrajectory.hpp
- Core/include/Acts/EventData/MultiTrajectoryHelpers.hpp
- Core/include/Acts/EventData/ParticleHypothesis.hpp
- Core/include/Acts/EventData/ProxyAccessor.hpp
- Core/include/Acts/EventData/SeedContainer2.hpp
- Core/include/Acts/EventData/SeedProxy2.hpp
- Core/include/Acts/EventData/SpacePointColumnProxy2.hpp
- Core/include/Acts/EventData/SpacePointContainer2.hpp
- Core/include/Acts/EventData/SpacePointData.hpp
- Core/include/Acts/EventData/SpacePointMutableData.hpp
- Core/include/Acts/EventData/SpacePointProxy2.hpp
- Core/include/Acts/EventData/SubspaceHelpers.hpp
- Core/include/Acts/EventData/TrackContainer.hpp
- Core/include/Acts/EventData/TrackParameters.hpp
- Core/include/Acts/EventData/TrackProxy.hpp
- Core/include/Acts/EventData/TrackStatePropMask.hpp
- Core/include/Acts/EventData/TrackStateProxy.hpp
- Core/include/Acts/EventData/TrackStateType.hpp
- Core/include/Acts/EventData/Types.hpp
> docs: Fix doxygen warnings in EventData

- Plugins/DD4hep/include/ActsPlugins/DD4hep/ConvertDD4hepDetector.hpp
- Plugins/DD4hep/include/ActsPlugins/DD4hep/DD4hepBlueprintFactory.hpp
- Plugins/DD4hep/include/ActsPlugins/DD4hep/DD4hepDetectorElement.hpp
- Plugins/DD4hep/include/ActsPlugins/DD4hep/DD4hepIdentifierMapper.hpp
- Plugins/DD4hep/include/ActsPlugins/DD4hep/DD4hepLayerBuilder.hpp
- Plugins/DD4hep/include/ActsPlugins/DD4hep/DD4hepLayerStructure.hpp
- Plugins/DD4hep/include/ActsPlugins/DD4hep/DD4hepMaterialHelpers.hpp
- Plugins/Geant4/include/ActsPlugins/Geant4/Geant4DetectorElement.hpp
- Plugins/Geant4/include/ActsPlugins/Geant4/Geant4DetectorSurfaceFactory.hpp
- Plugins/Geant4/include/ActsPlugins/Geant4/Geant4PhysicalVolumeSelectors.hpp
> docs: Fix doxygen warnings in the DD4hep plugin

- Plugins/Onnx/include/ActsPlugins/Onnx/OnnxRuntimeBase.hpp
> docs: Fix doxygen warning in ONNX plugin

- Plugins/Gnn/include/ActsPlugins/Gnn/Stages.hpp
- Plugins/Gnn/include/ActsPlugins/Gnn/Tensor.hpp
> docs: Fix doxygen warnings in the GNN plugin
